### ISSUE TITLE
Paired devices not visible in Gnome Shell

### ISSUE THREAD

**Issue by gmmp** [andyholmes/gnome-shell-extension-gsconnect#135] opened 2018-05-31 03:37 UTC
![image](https://user-images.githubusercontent.com/16728548/40759754-ffc17f50-64c5-11e8-9088-8a557f8ce237.png)
im using ubuntu1804 gnome 3.28 xorg.
clipboard(both pc and phone) and other function work ok,but just can't see the phone paired in 'Moible Devices' menu.so i can't browse my phone's files at my ubuntu.

**Comment by andyholmes** [comment] 2018-05-31 03:47
This seems like it might be a duplicate of #117, can you tell me what icon set you are using and if you have updated it recently?

**Comment by gmmp** [comment] 2018-05-31 05:53
icons 'SoftNumix' from Numix theme.not updated util last month.
i have tried change my icons to default 'Adwaita', restart gnome by alt+f2 'restart'.still can't see deivce

**Comment by gmmp** [comment] 2018-06-01 02:11
good news,maybe after installed system update of today.phone device icon show in the user menu,never show before,finally can browser phone files!but still can't see in the mobile device dropdown😂
![image](https://user-images.githubusercontent.com/16728548/40817207-ca6d35ce-6583-11e8-9727-ec18341ca515.png)

**Comment by andyholmes** [comment] 2018-06-01 03:12
Are you using the latest version (v11) from the releases page? That might help with these problems.

**Comment by gmmp** [comment] 2018-06-01 08:12
yes,i'm using verison 11.and the icon disappeared😂.i will send comment when i figure out how it show and disappear.
![image](https://user-images.githubusercontent.com/16728548/40829415-f385c3ae-65b5-11e8-9bb8-bcdaf686fa3f.png)

**Comment by ferdnyc** [comment] 2018-06-10 10:51
Just one thing I wanted to point out:
> good news,maybe after installed system update of today.phone device icon show in the user menu,never show before,finally can browser phone files!but still can't see in the mobile device dropdown

You may be aware of this, but when "Show Indicators" is activated in the extension preferences the individual device entries are **moved** from the User menu to the top bar. So, not seeing them in the "Mobile Devices" dropdown is normal unless you turn off "Show Indicators" to move the device entries back into the User menu.

Other than that, your system sure is using a strange icon, even when it did show up. I wonder if the size might be causing an issue? I'm also using the Adwaita icon theme (Fedora's default), and here's what the panel looks like for me in both Indicator and User Menu forms:

![screenshot from 2018-06-10 06-44-29](https://user-images.githubusercontent.com/538020/41200838-0f6c7f52-6c7a-11e8-910e-f7e99c2b0ed5.png)
![screenshot from 2018-06-10 06-44-19](https://user-images.githubusercontent.com/538020/41200839-11853c84-6c7a-11e8-891d-be96b14c30e6.png)

The `gtk3-icon-browser` tool (part of the `gtk3-devel` package under Fedora) might be helpful in examining the icons available in the current theme. Here's what a search for "phone" looks like on my system:

![screenshot from 2018-06-10 06-44-41](https://user-images.githubusercontent.com/538020/41200846-4039c04a-6c7a-11e8-862b-e43fa34d1fb0.png)

(As you can see, the icons match.)

**Comment by AbelVM** [comment] 2018-08-24 09:01
Hi, I'm experimenting the same issue. Ubuntu 18.04.1 + GSconnect 12 here, HiDPi screen. I've tested all the Gnome themes (default, materia, arc, etc.) and icons sets (default, paper, papyrus, etc.) I have installed, and while all functionality is there, I can't see my device in the top bar or the submenu, regardless of the settings:

![screenshot from 2018-08-24 10-50-43](https://user-images.githubusercontent.com/9017165/44575679-ceb49000-a78c-11e8-995a-bca4efdd711b.png)

**Comment by joearcher** [comment] 2018-09-18 19:07
Same issue for me. 18.04 with GSConnect 12. I've tried lots of icon sets and the standard theme. I don't see the device in the user menu, or an icon on my top bar when "show indicators" is activated. All other functionality seems fine. My phone is paired, and I see notifications etc.

**Comment by andyholmes** [comment] 2018-09-19 05:14
Are you sure KDE Connect isn't installed or running?

    $ pidof kdeconnectd

See also: [Network Service Failed](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Troubleshooting#network-service-failed)

**Comment by joearcher** [comment] 2018-09-19 07:38
@andyholmes I definitely don't have kde connect running.

The two tests on the Network Service Failed page show the following...
    lsof -i UDP:1716
    COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
        gjs     1513  joe   18u  IPv4  32167      0t0  UDP *:1716

    ss -lup sport = :1716
    State          Recv-Q          Send-Q                    Local Address:Port                   Peer Address:Port         
    UNCONN         15232           0                               0.0.0.0:1716                        0.0.0.0:*             users: 
    (("gjs",pid=1513,fd=18))

**Comment by andyholmes** [comment] 2018-09-19 07:50
Are there any errors in the debug log for Gnome Shell? You can turn that on in the About page, although you'll probably have to enable and disable the extension to catch any errors.

**Comment by joearcher** [comment] 2018-09-19 07:56
It doesn't appear so, after enabling debug mode, then disabling and re-enabling the extensions I see this in the extension tab of the terminal:

    [gsconnect@andyholmes.github.io]: enabling extension
    [gsconnect@andyholmes.github.io]: extension.SystemIndicator._serviceAppeared()
    [gsconnect@andyholmes.github.io]: extension.SystemIndicator._deviceAdded(/org/gnome/Shell/Extensions/GSConnect/Device/206b46d23b67dc09)

**Comment by andyholmes** [comment] 2018-09-19 08:03
Hmm, I think there should be some `_sync()` messages at least, but if there are no errors it must be something theme or icon related. Do you also have a HiDPI screen?

**Comment by joearcher** [comment] 2018-09-19 08:37
@andyholmes Nope just a 16:9 1920 x 1080. I'll have to try some more themes.

**Comment by andyholmes** [comment] 2018-09-19 08:42
The instance that it was an icon theme problem, I believe it ended up being old icon files in `~/.local/share/icons` that were overriding the system ones. Without an error, the only other thing I can think is to use the object selector in Looking Glass (<kbd>Alt</kbd>+<kbd>F2</kbd> and `lg`) and see if you can "mouse-over" where the panel indicator should be.

**Comment by joearcher** [comment] 2018-09-19 09:53
@andyholmes I get nothing in the panel using Looking Glass where the icon should be (show indicators is enabled), it just outlines the whole panel or the visible user-menu icons.

**Comment by andyholmes** [comment] 2018-10-26 20:45
Can anyone confirm that this issue still exists on v13, or if it used to affect you and now doesn't?

**Comment by ferdnyc** [comment] 2018-10-27 07:41
> Can anyone confirm that this issue still exists on v13, or if it used to affect you and now doesn't?

I encountered it when I _upgraded_ to v13 via extensions.gnome.org, and the extension failed to function after, but following a system reboot GSConnect is functional again. So, it looks like it was a one-time failure on upgrade.

**Comment by ferdnyc** [comment] 2018-10-27 07:42
(Sorry, deleted my previous comment. I was discussing the wrong issue.)

**Comment by gmmp** [comment] 2018-10-27 07:57
> Can anyone confirm that this issue still exists on v13, or if it used to affect you and now doesn't?

i hvae tried v13, still can't see the paired devices in dropdown menu mobile devices. but show at the head menu.
![image](https://user-images.githubusercontent.com/16728548/47601289-e6b0c600-da00-11e8-8fdf-72572f1f8cae.png)
![image](https://user-images.githubusercontent.com/16728548/47601295-f03a2e00-da00-11e8-847a-70581d96f9ef.png)

**Comment by andyholmes** [comment] 2018-10-27 14:37
> i hvae tried v13, still can't see the paired devices in dropdown menu mobile devices. but show at the head menu.

Okay, is that including if you toggle the "Display Mode" option in settings? Like if it's set to _"Panel"_ it does show the indicators, but if it's set to _"User Menu"_ it does not show in the dropdown?

**Comment by joearcher** [comment] 2018-10-27 15:45
Confirmed as fixed for me.

**Comment by gmmp** [comment] 2018-10-28 01:48
I toggle the  display mode option ,devices show in drop down. Thanks,problem fixed.

**Comment by andyholmes** [comment] 2018-10-28 13:11
Alright, I'll close this one since it seems to be fixed for everyone.

**Closed by andyholmes** 2018-10-28 13:11 UTC
Labels: help wanted, needs info
