### ISSUE TITLE
Unable to browse SD card

### ISSUE THREAD

**Issue by didierga** [andyholmes/gnome-shell-extension-gsconnect#48] opened 2018-02-16 00:22 UTC
My phone is a Motorola Moto G 3nd Gen running Android 6.0.1 and KDE Connect 1.7.1

Using MConnect and KDE-Connect I can browse both internal storage and SD card

Unfortunately using GSConnect 9 I can browse internal storage but  I cannot browse SD card.

**Comment by andyholmes** [comment] 2018-02-16 21:55
Hi, I don't have a device with an SDCard myself, however all browseable directories are reported by the app itself.

Could you tell me in what way you can't browse? I the SDCard not visible in the list of directories the shell extension offers? Or does it just fail to browse when you open it in nautilus?

**Comment by didierga** [comment] 2018-02-17 13:58
I have 5 choices in GSConnect "browse files" menu (translated from french)
- SD Card
- Pictures from camera (SD Card)
- Internal storage
- Pictures from camera (Internal storage)
- Unmount

When I click on "Internal storage" or "Pictures from camera (Internal storage)" I open a Nautilus window

When I click "SD Card" or "Pictures from camera (SD Card)" nothing happen but I have messages in log. See attached file. 

Command "tree -d /run/user/1000/gsconnect/"' shows only internal storage and no the SD card.

[gsconnect#48.log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1733723/gsconnect.48.log)

**Comment by andyholmes** [comment] 2018-02-27 06:29
Sorry I haven't had time to come back to this. I have a feeling this may be related to PR #40 which was submitted by @getzze, although I'm unsure. Something that might help is if you could post the debug message from the app which would look something like this:

```js
{
    "id": 1518956413092,
    "type":"kdeconnect.sftp",
    "body": {
        "ip": "192.168.1.71",
        "port": 1743,
        "user": "kdeconnect",
        "password": "UzcNCrI7T668JyxUFjOxQncBPNcO",
        "path": "/storage/emulated/0",
        "multiPaths": ["/storage/emulated/0","/storage/emulated/0/DCIM/Camera"],
        "pathNames":["All files","Camera pictures"]
    }
}
```

**Comment by didierga** [comment] 2018-02-27 19:36
I hope it's that you need.....


JS LOG: [gsconnect@andyholmes.github.io]: SFTP: mount()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(adb7ba6ff2123456, {"id":0,"type":"kdeconnect.sftp.request","body":{"startBrowsing":true}})
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(adb7ba6ff2123456)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1519759123456,"type":"kdeconnect.sftp","body":{"ip":"192.168.1.14","port":1739,"user":"kdeconnect","password":"6f0mtqzboYPDCGoM7bkp3123456","path":"/storage/emulated/0","multiPaths":["/storage/1968-1234","/storage/1968-1234/DCIM/Camera","/storage/emulated/0","/storage/emulated/0/DCIM/Camera"],"pathNames":["Carte SD","Images de l'appareil photo(Carte SD)","Stockage interne","Images de l'appareil photo(Stockage interne)"]}}
JS LOG: Received from 'motorola'
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: _prepare()
JS LOG: Sftp: Warning: Permanently added '[192.168.1.14]:1739' (DSA) to the list of known hosts.

**Comment by andyholmes** [comment] 2018-03-01 07:39
Thanks, that was exactly what I needed, since I don't have a device with an SD card. In fact, getzze kindly submitted a PR fixing this even before you posted it :)

I'm still quite aways from releasing v10, but it should be possible for you to patch this yourself simply by overwriting `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js` with the [current file from master](https://raw.githubusercontent.com/andyholmes/gnome-shell-extension-gsconnect/master/src/service/plugins/sftp.js), since I assume you'd like to start using this now.

Currently master as a whole is broken, so don't try to build straight from master.

**Comment by getzze** [comment] 2018-03-01 10:19
@andyholmes I had not seen that this was working well in kdeconnect for desktop when I sent you my previous patch :). This should be working with PR #54.
@didierga Indeed, changing the `sftp.js` file in your local extension folder should solve the problem.

**Comment by didierga** [comment] 2018-03-01 12:49
There is some progress, GSConnect works now like MConnect with the same small problem on SD card display. GSConnect lists 4 places to display. Using USB cable, I placed a jpg file in each place to be sure there is something  to display.

Internal
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/emulated/0
It is OK, I can browse internal files system

Internal pictures from camera
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/emulated/0/DCIM/Camera
It is OK, I see jpg in the DCIM/Camera directory

SD Card
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234
It is BAD, I see an empty directory and I dont see any files on SD card

SD Card pictures from camera
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234/DCIM/Camera
It is now OK, I see jpg in DCIM/Camera on SD card

Thanks for you work !

**Comment by andyholmes** [comment] 2018-03-03 10:37
Hi, I'm planning a v9 bugfix release that will be distributed on the Gnome Extensions website, so if possible we should try and get to the bottom of the 3rd test you did (if it is a GSConnect problem and not sshfs/kdeconnect):

> SD Card
> /run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234
> It is BAD, I see an empty directory and I dont see any files on SD card

I have a feeling this may be sshfs or kdeconnect misbehaving, but if you could re-run the test and check the debug output for any helpful errors, maybe we can fix this one.

**Comment by didierga** [comment] 2018-03-03 11:46
I assume it is a permission problem.

When using GSConnect, I browse "Camera picture (SD Card)", I open a shell in that directory.
Using pwd I see this directory is 
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234/DCIM/Camera
and I can list content of this directory with no problem using ls command

I do the same to browse "SD Card" but I don't get the content of this directory but an empty nautilus window. Opening a shell and using pwd I see this directory is
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234
When I try to list the content of this directory with ls I get "Permission denied"

For internal storage, using ls I can list content of following directories with no problem:
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/emulated/0/
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/emulated/0/DCIM/camera

**Comment by getzze** [comment] 2018-03-03 13:48
I am using LineageOS 14.1 (based on AOSP 7.1) and it is working correctly, so probably it's a problem on the android side and not GSConnect.
When you open "Camera picture (SD Card)" in Nautilus, can you go to the parent folder? In your case '/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234/DCIM/'

**Comment by didierga** [comment] 2018-03-03 14:56
Yes, I can cd to parent directory unitil SD card root directory but I can list files in it !

$ pwd
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234/DCIM/Camera
$ ls
IMG_20170101_010101001.jpg
$ cd ..
$ pwd
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234/DCIM
$ ls
Camera
$ cd ..
$ pwd
/run/user/1000/gsconnect/adb7ba6ff2123456/storage/1968-1234
$ ls
ls: lecture du répertoire '.': Operation not permitted

**Comment by andyholmes** [comment] 2018-03-03 15:05
@didierga The plugin should make all mounted directories 0700 (read-write-execute owner only), could you run a quick `ls -Rla /run/user/1000/gsconnect/` to confirm?

**Comment by didierga** [comment] 2018-03-03 15:19
At this time directory is mounted with 0500 mode !

$ ls -Rla /run/user/1000/gsconnect/
/run/user/1000/gsconnect/:
total 0
drwx------.  3 qwerty qwerty 60  3 mars  12:01 .
drwx------. 34 qwerty qwerty 700  3 mars  16:12 ..
dr-x------.  1 qwerty qwerty 0 16 févr.  1970 adb7ba6ff2123456

/run/user/1000/gsconnect/adb7ba6ff2123456:
ls: lecture du répertoire '/run/user/1000/gsconnect/adb7ba6ff2123456': Operation not permitted
total 0

**Comment by getzze** [comment] 2018-03-03 15:36
I got two different outputs:

$ ls -Rla /run/user/1000/gsconnect/
/run/user/1000/gsconnect/:
total 0
drwx------  3 serv0 serv0  60 Mar  3 10:48 .
drwx------ 28 serv0 serv0 600 Mar  3 13:30 ..
drwx------  2 serv0 serv0  40 Mar  3 10:48 45ca5ee945bcf60

/run/user/1000/gsconnect/45ca5ee945bcf60:
total 0
drwx------ 2 serv0 serv0 40 Mar  3 10:48 .
drwx------ 3 serv0 serv0 60 Mar  3 10:48 ..

And 2min later:

$ ls -Rla /run/user/1000/gsconnect/
/run/user/1000/gsconnect/:
total 0
drwx------  3 serv0 serv0  60 Mar  3 10:48 .
drwx------ 28 serv0 serv0 600 Mar  3 13:30 ..
d--x------  1 serv0 serv0   0 Aug 14  1970 45ca5ee945bcf60

/run/user/1000/gsconnect/45ca5ee945bcf60:
ls: reading directory '/run/user/1000/gsconnect/45ca5ee945bcf60':
Permission denied
total 0


In both cases I could access my SDcard, so I don't think it is a problem.

Can you access the `storage` subfolder ?

$ ls -la /run/user/1000/gsconnect/45ca5ee945bcf60/storage/
total 0
dr-x------ 1 serv0 serv0 0 Jan  1  1970 A66E-18EE
d--x------ 1 serv0 serv0 0 Aug 28  2017 emulated
d--x------ 1 serv0 serv0 0 Feb 23 08:50 self


2018-03-03 15:19 GMT+00:00 DidierG <notifications@github.com>:

**Comment by andyholmes** [comment] 2018-03-03 17:15
I never noticed that; I guess sshfs is mapping the remote permissions to even the root mount directory. A shot in the dark, but since it's only occurring with the SD card root maybe it's a problem with vfat permissions on the android side?

Out of curiosity, are both of you using sdcards formatted as fat32/vfat? Or are you using a linux fs like ext4?

**Comment by didierga** [comment] 2018-03-04 00:37
So I removed my SD card from phone and I put it in a USB card reader. This is that I get....
==================================
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
---/---
sdc      8:32   1    29G  0 disk 
└─sdc1   8:33   1    29G  0 part /run/media/qwerty/1968-1234
$ ll /run/media/qwerty/1968-1234
total 224
drwxr-xr-x.  4 qwerty qwerty 32768 12 févr. 17:05  Android
drwxr-xr-x.  4 qwerty qwerty 32768 12 févr. 17:19  DCIM
drwxr-xr-x.  2 qwerty qwerty 32768 12 févr. 17:02  LOST.DIR
drwxr-xr-x. 50 qwerty qwerty 32768 24 févr. 23:45  Music
drwxr-xr-x.  5 qwerty qwerty 32768 12 févr. 21:11  Pictures
$ cd /run/media/qwerty
$ ll
total 32
drwxr-xr-x. 10 qwerty qwerty 32768  1 janv.  1970 1968-1234
==================================
$ sudo file -sL /dev/sdc1
/dev/sdc1: DOS/MBR boot sector, code offset 0x58+2, OEM-ID "android ", sectors/cluster 64, reserved sectors 54, sectors/track 16, heads 4, sectors 60872704 (volumes > 32 MB), FAT (32 bit), sectors/FAT 7429, reserved 0x1, serial number 0x196818e4, unlabeled
==================================
$ sudo fdisk -l /dev/sdc
Disque /dev/sdc : 29 GiB, 31167873024 octets, 60874752 secteurs
Unités : secteur de 1 × 512 = 512 octets
Taille de secteur (logique / physique) : 512 octets / 512 octets
taille d'E/S (minimale / optimale) : 512 octets / 512 octets
Type d'étiquette de disque : dos
Identifiant de disque : 0x00000000

Périphérique Amorçage Début      Fin Secteurs Taille Id Type
/dev/sdc1    *         2048 60874751 60872704    29G  c W95 FAT32 (LBA)
==================================

This SD card has been formated in phone using Androïd utility.

**Comment by getzze** [comment] 2018-03-04 09:15
Mine is also in fat32.
Can you access (and ls) other subfolders of your sdcard, other than DCIM I mean? To see if it's DCIM that has special read permissions or if it's the root folder that has restrictions.

**Comment by getzze** [comment] 2018-03-04 09:43
I checked my permissions using termux in my phone:

$ ls -al /storage/
total 33
drwxr-xr-x    5 root     root           100 Feb 23 08:50 .
drwxr-xr-x   20 root     root             0 Aug 14  1970 ..
drwxrwx--x   13 root     sdcard_r     32768 Jan  1  1970 A66E-18EE
drwx--x--x    4 root     sdcard_r      4096 Aug 28  2017 emulated
drwxr-x--x    2 root     root            60 Feb 23 08:50 self


My sdcard is 771, like `/storage/emulated/0/` (I have to be root to see this one):

titan:/ # ls -al /storage/emulated/
total 3
drwx--x--x  4 root sdcard_rw 4096 2017-08-28 12:15 .
drwxr-xr-x  5 root root       100 2018-02-23 08:50 ..
drwxrwx--x 32 root sdcard_rw 4096 2018-02-23 09:34 0

Notice that `/storage/emulated/` has not read/write access for group members and `ls` doesn't work there on my computer.
$ ls -la /run/user/1000/gsconnect/45ca5ee945bcf60/storage/emulated 
ls: reading directory '/run/user/1000/gsconnect/45ca5ee945bcf60/storage/emulated': Permission denied
total 0

What about you? Are you also root?

**Comment by didierga** [comment] 2018-03-04 20:09
I opened /run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/DCIM/Camera in a shell then I changed do /run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234

From this directory I can list
/run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/DCIM/Camera 
/run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/DCIM
/run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/Music
/run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/Pictures
but I can't  list
/run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234

I can also using mkdir create new directory /run/user/1000/gsconnect/adb7ba6ff21654e1/storage/1968-1234/Test, list it then using rmdir delete it.

The problem is definitively only on the root directory of the SD card.

**Comment by andyholmes** [comment] 2018-03-05 04:57
Well, I'm pretty confident at this point that this is not caused by GSConnect and is either the Android SFTP server, `sshfs` or KDE Connect.

I'm going to tag this as upstream and mark it closed since two other bugs have been fixed on this thread, but I encourage you to keep discussing or post any new information that seems relevant to this issue in case there's a chance we can implement a workaround.

**Closed** 2018-03-05 04:58 UTC
Labels: needs info, upstream

**Comment by didierga** [comment] 2018-03-05 09:32
Have a look at: https://bugs.kde.org/show_bug.cgi?id=377058

**Comment by getzze** [comment] 2018-03-05 10:37
Did you try to `ls` with the path of comment 6?

2018-03-05 9:32 GMT+00:00 DidierG <notifications@github.com>:
