### ISSUE TITLE
Version 12 forks a lot of python3 processes

### ISSUE THREAD

**Issue by rocky7x** [andyholmes/gnome-shell-extension-gsconnect#178] opened 2018-08-26 12:23 UTC
Hi,

On Manjaro, when I've upgraded to version 12 of this extension, it eats up a lot of RAM by forking numerous python3 processes. Version of Gnome-shell is 3.28.3. Even when I disable the extension, the python3 processes remain running. The file running inside the python3 process is /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py. Any idea what's wrong?

**Comment by rocky7x** [comment] 2018-08-26 15:04
Changing some details: it's not version 12, it's also 11.2 So probably it's not a problem of upgraded GSConnect, but of upgraded python 3, which causes this. Any idea?

**Comment by rocky7x** [comment] 2018-08-27 13:29
This is the python trace:
Traceback (most recent call last):
  File "~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py", line 290, in _on_quiescent
    for phone_number in self.get_phone_numbers(folk):
  File "~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py", line 326, in get_phone_numbers
    for key, details in get_iterator(phone_numbers):
  File "~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py", line 207, in __iter__
    for it in _GeeIterator.__iter__(self):
RuntimeError: generator raised StopIteration

**Comment by rocky7x** [comment] 2018-08-27 14:57
OK I've found the root-cause for this: https://www.python.org/dev/peps/pep-0479/ 
It's an intentional behavior in Python 3.7. The line 207: for it in _GeeIterator.__iter__(self): must have an exception catch for StopIteration, something like:
```
try:
    line += next(lines)
    except StopIteration:
    return
```

**Comment by andyholmes** [comment] 2018-08-31 03:38
Hi, thanks for tracking this down and figuring out the cause. I'm working to get the rewrite in shape to merge before another release is out, so this won't be fixed before then.

You could try tossing an `except` clause in there to see if it helps, since it won't be overwritten by an update. I don't have Python 3.7 yet, but if Manjaro is Arch you could ask the maintainer of the AUR package to downstream a patch, or I could push the small fix to master and they can rebuild the package from there as v12-1 or v12.1 or something.

In the rewrite there's much better handling of spawned processes, so I think the error would be caught and not cause this problem. I'll mark this as bug and tag it to wip-rewrite so I remember and we can revisit this when it's merged (soon I hope!).

**Comment by andyholmes** [comment] 2018-09-11 23:02
**Sorry, I typed this up awhile ago and it was sitting in an open tab not sent!**

After reading that link you posted, I think the fix is actually quite simple. `_GeeIterator()` actually has to raise `StopIteration` explicitly, so just replacing it with `return` should fix this.

You can just replace it with sed and restart the service:

```sh
$ sed -i -e 's/raise\ StopIteration/return/g' ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py
$ kill $(ps aux | grep '[d]aemon.js' | awk '{print $2}')
```

Let me know if that fixes it, since I don't have python-3.7 to test. If you didn't realize before, you can just run the script directly with `python3` as well.

**Comment by rocky7x** [comment] 2018-09-19 12:20
Hi,

I've finally had some time to check it. Seems that the fix did the trick, the process ends OK, when I run it using the python3 command. Also the processes doesn't seem to build up anymore. If I notice any problems, I'll come back. For the time being it seems to be OK. Thanks a lot for taking the time to fix it.

**Comment by andyholmes** [comment] 2018-09-22 12:49
I'm going to close this now since I've forward ported the fix and merged the rewrite. Thanks for your help.

**Closed by andyholmes** 2018-09-22 12:49 UTC
Labels: bug
