### ISSUE TITLE
Xiaomi Redmi S2 SMS dont sync multiple apps tested

### ISSUE THREAD

**Issue by coco33920** [andyholmes/gnome-shell-extension-gsconnect#586] opened 2019-08-13 08:37 UTC
**Describe the bug**
SMS dont sync with Xiaomi Redmi S2 ( using standard SMS app, Android Message and SMS/MMS ) did you know a working sms application ? I searched on the internet for people with the same smartphone and i does not find any apps.

**Steps To Reproduce:**
Receive and sync the SMS with the device

**Expected behavior**

The sync.

**Screenshots**

![image](https://user-images.githubusercontent.com/17108449/62926860-ac5cbd80-bdb5-11e9-8100-13038ca7a5f1.png)

**Support Log**

GSConnect Version: 24
GSConnect Install: user
GJS: 15201
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Tue 2019-05-07 08:24:29 CEST, end at Tue 2019-08-13 10:34:24 CEST. --
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:22 gjs[2280]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
août 13 10:34:24 gjs[2280]: GtkDialog mapped without a transient parent. This is discouraged.

**System Details (please complete the following information):**

 - **GSConnect version:** [24]
   - **Installed from:** [Zip]
 - **GNOME/Shell version:** [3.28]
 - **Distro/Release:** [Ubuntu 18.04]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [Xiaomi Redmi S2]
 - **KDE Connect app version:** [1.12.93]

**Additional Notes:**

I will test with another device.

**Comment by ferdnyc** [comment] 2019-08-13 23:55
@coco33920 I'm going to close this as a duplicate of #320, which tracks the lack of SMS history availability on various devices.

Long story short, there's nothing GSConnect can do about the issue. Either the KDE Connect app is able to retrieve SMS history, or it's not. On some devices it's not, and unfortunately it sounds like yours may be one of those. But there's more information about the problem in general at #320, and at the KDE Connect bug it links to.

**Closed by ferdnyc** 2019-08-13 23:55 UTC

**Comment by maxerbox** [comment] 2019-11-10 23:01
Fixed in KDE Connect: https://invent.kde.org/kde/kdeconnect-android/commit/4a0c53610f5b8f82162bda0a2ac81d789f00e64a
