### ISSUE TITLE
Can't mount storage mobile phone to my desktop

### ISSUE THREAD

**Issue by gillesMioni** [andyholmes/gnome-shell-extension-gsconnect#496] opened 2019-03-21 06:58 UTC
[gsconnect.GBBCZZ.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2991129/gsconnect.GBBCZZ.txt)

I've installed the last version of gsconnect on my desktop ( Debian 10 4.19.16-1 x86_64) and kdeconnect from f-droid repository on my mobile phone samsung S7 Edge (androïd v8)
When I click from my desktop phone icon then I click on screen icon to mount storage, nothing happens.

**Comment by andyholmes** [comment] 2019-03-21 12:28
> JS ERROR: Could not load extension _gsconnect@andyholmes.github.io: Error: uuid "gsconnect@andyholmes.github.io" from metadata.json does not match directory name "_gsconnect@andyholmes.github.io"

Seems like you've installed gsconnect to the wrong directory (leading underscore in filepath). However, the bug you report is a duplicate of #491 (SFTP: Gvfs broken in kdeconnect-android 1.12).

**Closed by andyholmes** 2019-03-21 12:28 UTC
Labels: duplicate
