### ISSUE TITLE
Wrong name associated with SMS messages

### ISSUE THREAD

**Issue by didierga** [andyholmes/gnome-shell-extension-gsconnect#761] opened 2020-02-05 20:32 UTC
Hi,
My problem is the following: in the received messages list, when message sender is not in my contact list, a name of my contacts list, always the same, is dispayed in place of the phone number of the message sender.
I use GS Connect 31.
Thanks for your help.

**Comment by andyholmes** [comment] 2020-02-11 00:29
Sorry, I haven't had a chance to look at the code for this yet. Are the two phone numbers similar by chance? Eg. `555-4444` and `5554`?

**Comment by didierga** [comment] 2020-02-13 23:32
I investigated this problem.
Phone number are not similar between messages.
When the name is wrong, its always the same name who is displayed and I dont understand why.
Do you transfer full contacts list from phone to computer and in this case is it possible to display this list on computer ?

**Comment by ferdnyc** [comment] 2020-02-14 00:43
@didierga Yeah, if you take a look around `$HOME/.cache/gsconnect/`, pretty much everything retrieved locally should be in there.

(I'm not 100% sure what's current or what the formats are anymore, the structure's evolved a bunch over the years and it's been so long since I had a phone where SMS worked — stupid Samsung.)

**Comment by didierga** [comment] 2020-02-14 01:15
Bingo !

What I did:
- I located the file %HOME/.cache/gsconnect/1234567890/contacts.json
- I browsed this file and I located the wrong name who was displayed always
- In the data associated to this name I had two number fields: one in correct format and the other with just a hyphen -
- I went on the phone and I deleted this second number with only hyphen
- I renamed the file %HOME/.cache/gsconnect/1234567890/contacts.json in OLD
- I dissociated phone and computer
- I logged out - logged in in gnome
- I associated phone and computer back
- This recreated the file %HOME/.cache/gsconnect/1234567890/contacts.json
- Names displayed are now right !

Thanks for your help !

**Comment by ferdnyc** [comment] 2020-02-14 03:46
Glad you got it sorted out! Closing this as it was actually caused by bad data on the phone — **#NotOurFault** :wink:

**Closed by ferdnyc** 2020-02-14 03:46 UTC
