### ISSUE TITLE
Use desktop-focused interfaces for mobile notifications where possible

### ISSUE THREAD

**Issue by gausie** [andyholmes/gnome-shell-extension-gsconnect#373] opened 2018-12-03 09:11 UTC
**Is your feature request related to a problem? Please describe.**
When I get a notification from an app that has a web interface (Whatsapp, Telegram, Signal, Facebook messenger) I might rather respond using that interface

**Describe the solution you'd like**
When I click on a phone notification from one of those services, it opens the appropriate web interface in my web browser

**Describe alternatives you've considered**
It might also want to look for local applications that can handle the request (for example I have a Signal desktop client)

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org

**Comment by gausie** [comment] 2018-12-03 15:38
I don't think it would be unreasonable to keep a list of the most common application -> website links.

I turned off notifications from the desktop apps to avoid duplicates, but I see that that is not what many people would do.

**Comment by andyholmes** [comment] 2018-12-03 16:30
I'll have a look when I get the chance, but as I said the information passed by notifications may not be sufficient to identify the sending application.

Keep in mind that some applications may have translated names or the notification title may not be the name of the application, as is the case with some SMS apps where it is the contact name.

**Comment by ferdnyc** [comment] 2019-01-06 07:07
> I don't think it would be unreasonable to keep a list of the most common application -> website links.

Even if that is reasonable (I'm not so sure, there are a **lot** of web apps out there), the problem is that wouldn't really be enough. When you click on a notification from an app with a web interface, you'd want to load _that notification_ in the browser — or at least the list of notifications. But there's no way for GSConnect to link to anything like that, there isn't enough information in the notification. We could only link to "the site" in general, which seems insufficient.

Clicking (for example) a YouTube notification and being dumped at just https://youtube.com/ would be a pretty poor experience. (To say nothing of the bigger problem, when the browser doesn't even have an active session logged in to the user's account on the site.)

**Comment by andyholmes** [comment] 2019-01-23 16:52
I'm going to close this, since I don't think it's possible to reliably determine the notifying application or how to open the appropriate desktop application with the information available in the notification. It's for the same reason than SMS notifications can't open to the corresponding conversation in the messaging app.

**Closed by andyholmes** 2019-01-23 16:52 UTC
Labels: enhancement, maybe
