### ISSUE TITLE
Notification actions

### ISSUE THREAD

**Issue by ai** [andyholmes/gnome-shell-extension-gsconnect#207] opened 2018-09-25 05:57 UTC
In Android most of the notifications have a list of actions:

![p4aa8](https://user-images.githubusercontent.com/19343/45995411-005b9800-c066-11e8-9c90-8fdb2394b26a.png)

And GNOME Shell notifications support actions:

![banners-expanded](https://user-images.githubusercontent.com/19343/45995464-28e39200-c066-11e8-900e-f28b35c9d405.png)

Let’s combine them:

1. Check KDE Connect API  for passing actions list. If it does not support it, we can open an issue there.
2. Pass actions to GNOME Shell notification API and process action’s click event.

**Comment by andyholmes** [comment] 2018-09-25 06:12
This change would have to happen upstream in the KDE Connect project, since actions aren't passed with packets currently.

**Comment by ai** [comment] 2018-09-25 06:15
Do you know how to report a feature request to them? (Or to subscribe for updates if it was already created)

**Comment by andyholmes** [comment] 2018-09-25 06:30
In the readme there are links to KDE Connect resources.

**Comment by ai** [comment] 2018-09-25 06:48
The issue was reported in 2016 without any response from developers 😞

https://bugs.kde.org/show_bug.cgi?id=366475

**Comment by andyholmes** [comment] 2018-10-16 00:55
Upstream tasks:
* Android: https://phabricator.kde.org/D12294
* Desktop: https://phabricator.kde.org/D12293

**Comment by kartheek7895** [comment] 2019-03-21 06:43
From comment 4, looks like this feature has been added
[https://bugs.kde.org/show_bug.cgi?id=366475#c4]()

**Comment by andyholmes** [comment] 2019-03-21 13:39
The patch for Android has still not been merged: https://phabricator.kde.org/D12294

**Comment by viggy96** [comment] 2019-05-15 16:16
It doesn't appear that the notification actions work quite yet. I've tried on the notification for several apps, and it doesn't work. The reply action does though. All other ones don't.

**Comment by andyholmes** [comment] 2019-05-15 20:51
@viggy96 

Can you please reproduce this and supply a debug log, as described in [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log)?

**Comment by viggy96** [comment] 2019-05-15 21:21
@andyholmes debug log:

[gsconnect.3K9T1Z.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3184487/gsconnect.3K9T1Z.txt)

**Comment by andyholmes** [comment] 2019-05-15 21:57
Thanks for the log, I made a silly typo which makes me wonder why it's been working for me this whole time :s 

I'll try and push a new release ASAP, until then here's a ZIP ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3184600/gsconnect%40andyholmes.github.io.zip)

**Comment by viggy96** [comment] 2019-05-15 22:09
@andyholmes Doesn't appear to be fixed:
[gsconnect.FKQX1Z.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3184621/gsconnect.FKQX1Z.txt)

**Comment by andyholmes** [comment] 2019-05-15 22:17
This seems to work for me:

```
[/service/protocol/core.js:receive/<:177]: Google Nexus 4: {
  "id": 1557958473411,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "a3791fb9f4f02297a450278cada4a82a",
    "actions": [
      "Action"
    ],
    "id": "0|com.matusmak.fakenotifications|97|null|10077",
    "isClearable": true,
    "appName": "Fake Notifications",
    "time": "1557958473395",
    "ticker": "Test Actions: Test Body",
    "title": "Test Actions",
    "text": "Test Body"
  },
  "payloadSize": 6926,
  "payloadTransferInfo": {
    "port": 1739
  }
}
[/service/plugins/notification.js:closeNotification:599]: "0|com.matusmak.fakenotifications|97|null|10077"
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1557958477981,
  "type": "kdeconnect.notification.action",
  "body": {
    "action": "Action",
    "key": "0|com.matusmak.fakenotifications|97|null|10077"
  }
}
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1557958477983,
  "type": "kdeconnect.notification.request",
  "body": {
    "cancel": "0|com.matusmak.fakenotifications|97|null|10077"
  }
}
[/service/protocol/core.js:receive/<:177]: Google Nexus 4: {
  "id": 1557958476311,
  "type": "kdeconnect.notification",
  "body": {
    "id": "0|com.matusmak.fakenotifications|97|null|10077",
    "isCancel": true
  }
}
```

Are you sure you installed the ZIP correctly and restarted GNOME Shell?

**Comment by viggy96** [comment] 2019-05-15 22:41
Yes, I deleted all previous gsconnect extensions from ~/.local/share/gnome-shell/extensions, and I even restarted my machine to be sure. The error still occurs.

**Comment by andyholmes** [comment] 2019-05-15 23:22
Can you install this zip and confirm the About dialog says version 24?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3184776/gsconnect%40andyholmes.github.io.zip)

**Comment by viggy96** [comment] 2019-05-17 15:43
![image](https://user-images.githubusercontent.com/9837626/57939756-feff0a00-7898-11e9-89f4-9aca40854a9a.png)

Error still occurs.

**Comment by andyholmes** [comment] 2019-05-17 17:58
Could you show me a new log for this error? The code for this is straightforward, so I can't see how it could be the same error.

Device actions (eg. `activateNotification`) are bound to this function:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/59c303f71984cea5cdef988cd949db169fdf80de/src/service/plugins/base.js#L62-L76

Which will call this function:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/59c303f71984cea5cdef988cd949db169fdf80de/src/service/plugins/notification.js#L648-L656

Notification button actions are added here:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/59c303f71984cea5cdef988cd949db169fdf80de/src/service/plugins/notification.js#L494-L503

**Comment by viggy96** [comment] 2019-05-18 22:16
@andyholmes Here's a new log:
[gsconnect.FX711Z.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3194544/gsconnect.FX711Z.txt)

**Comment by andyholmes** [comment] 2019-05-18 23:47
@viggy96 

It seems like GSConnect is doing everything properly here, is it not working on Android? If that's the case your may have to get a logcat to find out why this is not working on the remote end.

If you can get `adb` installed and debugging enabled on your phone, you can get a logcat for KDE Connect with this command:

    adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)

**Comment by viggy96** [comment] 2019-05-19 04:56
@andyholmes The notification actions work perfectly fine on my phone itself.

**Comment by andyholmes** [comment] 2019-05-19 05:27
@viggy96 The log you posted shows that GSConnect is correctly sending the packet to activate the action:

```js
[/service/protocol/core.js:send:220]: Moto X4: {
  "id": 1558217712354,
  "type": "kdeconnect.notification.action",
  "body": {
    "action": "Once",
    "key": "0|co.krypt.kryptonite|0|4H6hAGUANadU2V9qAnICEY|10245"
  }
}
```

After this, it's up to [kdeconnect-android to activate the action](https://invent.kde.org/kde/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/NotificationsPlugin/NotificationsPlugin.java#L488-508):

```java
@Override
public boolean onPacketReceived(final NetworkPacket np) {

    if (np.getType().equals(PACKET_TYPE_NOTIFICATION_ACTION) && Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {

        String key = np.getString("key");
        String title = np.getString("action");
        PendingIntent intent = null;

        for (Notification.Action a : actions.get(key)) {
            if (a.title.equals(title)) {
                intent = a.actionIntent;
            }
        }

        if (intent != null) {
            try {
                intent.send();
            } catch (PendingIntent.CanceledException e) {
                Log.e(TAG, "Triggering action failed", e); // <=======
            }
        }
```

The only way to know if/why this is failing is to check the logcat for the Android app, since everything GSConnect can do it has done.

**Comment by andyholmes** [comment] 2019-06-12 00:58
Closing since there doesn't seem to be anything more to fix in GSConnect.

**Closed by andyholmes** 2019-06-12 00:58 UTC
Labels: needs info
