### ISSUE TITLE
Mounting file system does not work in lineage OS 16.0

### ISSUE THREAD

**Issue by Dashon1** [andyholmes/gnome-shell-extension-gsconnect#703] opened 2019-11-10 03:38 UTC
**Mounting file system on ubuntu does not work in lineage OS 16.0 on One Plus 7 Pro. **

**Steps To Reproduce:**

1. Click the mount icon in the panel
2. Nothing happens

**Expected behavior**

Click mount icon in panel and see file system mounted in the side bar of nautilus.

**Screenshots**

![Screenshot from 2019-11-09 21-26-23](https://user-images.githubusercontent.com/40647198/68538375-b486b380-0338-11ea-828d-d8c47e4cdc31.png)

**Support Log**

GSConnect Version: 28
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-11-07 14:08:35 CST, end at Sat 2019-11-09 21:26:34 CST. --
Nov 09 21:26:09 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356369604,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:09 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356369612,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:10 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356370236,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:13 gnome-shell[2471]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 533]: reference to undefined property "_delegate"
Nov 09 21:26:13 gnome-shell[2471]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 22]: reference to undefined property "_delegate"
Nov 09 21:26:15 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356375241,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:16 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356376359,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:20 systemd[1]: systemd-hostnamed.service: Succeeded.
Nov 09 21:26:23 dbus-daemon[2241]: [session uid=1000 pid=2241] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.105' (uid=1000 pid=2707 comm="/usr/lib/tracker/tracker-miner-fs " label="unconfined")
Nov 09 21:26:23 systemd[2213]: Starting Tracker metadata database store and lookup manager...
Nov 09 21:26:23 dbus-daemon[2241]: [session uid=1000 pid=2241] Successfully activated service 'org.freedesktop.Tracker1'
Nov 09 21:26:23 systemd[2213]: Started Tracker metadata database store and lookup manager.
Nov 09 21:26:23 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356383807,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:23 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356383812,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:23 dbus-daemon[2241]: [session uid=1000 pid=2241] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.105' (uid=1000 pid=2707 comm="/usr/lib/tracker/tracker-miner-fs " label="unconfined")
Nov 09 21:26:23 systemd[2213]: Starting Tracker metadata extractor...
Nov 09 21:26:23 dbus-daemon[2241]: [session uid=1000 pid=2241] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
Nov 09 21:26:23 systemd[2213]: Started Tracker metadata extractor.
Nov 09 21:26:25 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356385006,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:25 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356385727,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Nov 09 21:26:29 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356389304,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Nov 09 21:26:30 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356390014,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:31 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356391266,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 52428,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Nov 09 21:26:31 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356391723,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Nov 09 21:26:34 systemd[2213]: tracker-extract.service: Succeeded.
Nov 09 21:26:34 org.gnome.Shell.Extensions.GSConnect[2768]: [/service/protocol/core.js:send:321]: Artemis II: {
                                                              "id": 1573356394500,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 20, 24, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**
I can't exactly find any errors but seems like it is related to the bug report here: https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/52
,so possibly a regression.

Add any additional information about the problem or your system.

Things I have tried uninstalling gsconnect and kdeconnect on both systems respectively.
Rebooting both systems. 
Unpairing and repairing.
mount | grep gsconnect : has no result

**Comment by andyholmes** [comment] 2019-11-10 04:01
From the logs it looks like GSConnect is doing everything properly, but the Android app is just not responding. Is there a location set in the Android app settings?

Aside from that, you'll probably have to check if the Android app is throwing any errors:

```
adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)
```

**Comment by ferdnyc** [comment] 2019-11-10 04:02
... @andyholmes beat me to it. This sounds like a semi-duplicate of #525, it's not clear whether the Android side is configured for remote filesystem access.

**Comment by Dashon1** [comment] 2019-11-10 04:23
I replied via the email github sent. Did either of you two get those since they are not popping up here?

**Comment by andyholmes** [comment] 2019-11-10 04:33
Nope.

**Comment by Dashon1** [comment] 2019-11-10 04:36
Contents of the email:
As far as I can tell I have given all permissions that are required for this to work.

Screenshot of no message asking for file permissions for smtp plugin as well as the selected file system to expose are included. 

![Screenshot_20191109-221056_KDE_Connect](https://user-images.githubusercontent.com/40647198/68538905-44306000-0341-11ea-9c80-cec2418d02f3.png)
![Screenshot_20191109-221133_KDE_Connect](https://user-images.githubusercontent.com/40647198/68538902-3d095200-0341-11ea-8a8f-ab012e5248d6.png)

currently I will try uninstalling and reinstalling again.

**Comment by ferdnyc** [comment] 2019-11-10 04:36
@Dashon1 Not here either, sorry.

**Comment by andyholmes** [comment] 2019-11-10 04:40
Why does your storage location have no name? It shouldn't even let you do that.

**Comment by Dashon1** [comment] 2019-11-10 04:43
Ok thanks anyways. I'll open a bug report with kde, but for reference how would I go about debugging it with adb.

**Comment by Dashon1** [comment] 2019-11-10 04:53
@andyholmes 
@ferdnyc 
Umm you guys and gals may find this funny, but within seconds of enabling usb debugging on the phone it mounted the phones file system.

Last thing am I suppose to be the one to close the issue or is that you all?

**Closed** 2019-11-10 04:54 UTC

**Comment by andyholmes** [comment] 2019-11-10 05:10
Hooray, a heisenbug :D

**Comment by ferdnyc** [comment] 2019-11-10 07:02
> Hooray, a heisenbug :D

Oh uncertainty, how I've missed you.

Look at it this way, though: Heisenbug status is actually an improvement. Prior to that, it was also something of a GSConnect Schrödingbug. Turning on USB debugging opened the box!

**Comment by andyholmes** [comment] 2019-11-10 07:14
Just don't look too much into the box, or you'll find the [speed-up loop](https://thedailywtf.com/articles/The-Speedup-Loop) :wink:
