### ISSUE TITLE
v.27 Need to be restarted to connect to phone

### ISSUE THREAD

**Issue by lepidas** [andyholmes/gnome-shell-extension-gsconnect#680] opened 2019-10-24 05:01 UTC
Hi!
This I have found is for v.27, before it was working ok.
Computer can't connect to phone, displayed message is "Waiting for service"
Connects only if I open settings and press the "refresh", then it stays connected untill next reboot/start of computer.
If I restart the phone the problem does not exist, it connects immediately after phone has started.

log after refreshing, I don't know if that helps but here it is....

`GSConnect Version: 27
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-10-24 07:05:09 CEST, end at Thu 2019-10-24 07:07:14 CEST. --
Oct 24 07:07:04 boltd[2107]: power: setting force_power to OFF
Oct 24 07:07:10 dbus-daemon[1844]: [session uid=1000 pid=1844] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.105' (uid=1000 pid=2551 comm="gjs /home/blades/.local/share/gnome-shell/extensio" label="unconfined")
Oct 24 07:07:10 dbus-daemon[1844]: [session uid=1000 pid=1844] Successfully activated service 'org.gnome.Shell.Extensions.GSConnect'
Oct 24 07:07:10 gjs[2740]: g_variant_new_string: assertion 'string != NULL' failed
Oct 24 07:07:10 dbus-daemon[1844]: [session uid=1000 pid=1844] Connection :1.112 (uid=1000 pid=2740 comm="gjs /home/blades/.local/share/gnome-shell/extensio" label="unconfined") became a monitor.
Oct 24 07:07:10 dbus-daemon[1287]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.132' (uid=1000 pid=2551 comm="gjs /home/blades/.local/share/gnome-shell/extensio" label="unconfined")
Oct 24 07:07:10 systemd[1]: Starting Hostname Service...
Oct 24 07:07:10 dbus-daemon[1287]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct 24 07:07:10 systemd[1]: Started Hostname Service.
Oct 24 07:07:10 gjs[2740]: JS ERROR: POCO F1: Gio.IOErrorEnum: Host key verification failed
                           _mount/</<@/home/blades/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:178:33
                           @/home/blades/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1149:2
Oct 24 07:07:13 gjs[2551]: GtkDialog mapped without a transient parent. This is discouraged.
Oct 24 07:07:13 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893633468,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }
Oct 24 07:07:14 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893633862,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }
Oct 24 07:07:14 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893634067,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }
Oct 24 07:07:14 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893634245,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }
Oct 24 07:07:14 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893634564,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }
Oct 24 07:07:14 org.gnome.Shell.Extensions.GSConnect[2740]: [/service/protocol/core.js:receive/<:275]: POCO F1: {
                                                              "id": 1571893634814,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "id": "0|com.fsck.k9|35|null|10203",
                                                                "isCancel": true
                                                              }
                                                            }`

Ubuntu 18.04
GSConnect 27
Installed from extensions.gnome.org
GNOME Shell 3.28.4 
Paired with mobile phone

**Comment by andyholmes** [comment] 2019-10-24 05:28
Duplicate of #672 

This was fixed in f28250e, but won't be released for 3.28 as per [the announcement](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki#latest-news) in the news section of the wiki.

This Zip contains the above fix: [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3765852/gsconnect%40andyholmes.github.io.zip)

**Closed by andyholmes** 2019-10-24 05:28 UTC
