### ISSUE TITLE
Memory leak - 700mb RAM

### ISSUE THREAD

**Issue by x0a** [andyholmes/gnome-shell-extension-gsconnect#394] opened 2018-12-17 01:09 UTC
**Describe the bug**
Accumulates hundreds of MB of ram over the course of several hours.

**To Reproduce**
Not entirely sure how to reproduce. But it happens pretty consistently. I've not changed any of the defaults, I've only connected one device, my tablet. 

**Screenshots**
![screenshot from 2018-12-16 18-52-29](https://user-images.githubusercontent.com/13019784/50061247-c7622980-0163-11e9-9ff7-379e491cb9fe.png)
![screenshot from 2018-12-16 12-34-18](https://user-images.githubusercontent.com/13019784/50061240-a4d01080-0163-11e9-8de1-703d528b3aba.png)

**Debug output**
Heap attached. Doesn't seem to match what the terminal shows.
```
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

[gsconnect.heap.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2684139/gsconnect.heap.zip)

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.1
 - Distro/Release: Ubuntu 18.10

**GSConnect environment (if applicable):**
 - Paired Device(s): Samsung T-230NU Tablet
 - KDE Connect app version: 1.10.1

**Comment by andyholmes** [comment] 2018-12-17 01:14
Could you describe your general usage; SMS, sshfs, etc?

> Heap attached. Doesn't seem to match what the terminal shows.

Yes, these are not useful for this type of debugging. This will be removed from user view for the next release. You'll have to enable debugging as described here: [Debugging](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Debugging).

**Comment by andyholmes** [comment] 2018-12-17 01:44
A gdb dump probably wouldn't be much help without a lot of debug symbols, and even then I'd really hope it was my mistake and not GJS's since that would be a lot easier to fix :stuck_out_tongue_closed_eyes: 

Fortunately restarting the service should be relatively easy, if you can't find any obvious debug issues you can restart the service with `gapplication action org.gnome.Shell.Extensions.GSConnect quit`. That should at least avoid big problems, and the service reconnects quite easily.

There weren't any reports about this in v16, so hopefully I can track down what might have caused this.

**Comment by x0a** [comment] 2018-12-17 02:04
Actually, I do shut my monitor off and leave my desktop logged in throughout the night. And with the (minor) testing I could do in 10 minutes, messing around with remote input while the screen is off did make memory go up by about 15 MB. Also, opening the "Send files" dialog multiple times causes RAM to increase by 1-2MB and it never goes back down, even after triggering garbage collection. So it could definitely be a gjs issue. 

For now I'll refrain from restarting the service and let it run throughout the night, report back if I can confirm that the screen being off is the cause of the memory leak. Also, thanks for the great work on this wonderful extension!

**Comment by andyholmes** [comment] 2018-12-17 02:12
Hmm, thanks those are some good places for me to start looking.

It is strange that your help dump is so small, even though the memory usage is so high, not that there is explicitly useful information inside it.

**Comment by x0a** [comment] 2018-12-18 05:06
It's funny, I left it all night with the monitor off, like I said. In the morning it was up to 68mb which wasn't too bad. I almost forgot about it today. Haven't used KDE Connect at all. Then all of the sudden I see it had jumped up to 488mb sometime in the span of an hour? I've got the GJS log which might indicate something (very likely truncated because of the limited terminal scrollback) 
[gjs.log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2688955/gjs.log)

One thing I did notice is the icon kept disappearing from gnome tray throughout the day. My android probably kept killing KDEConnect because of memory, and I also jump between different hotspots throughout the day so perhaps constant disconnections/reconnections could occasionally cause a memory leak somehow? Pure speculation. As I  was typing this, the icon appeared and disappeared about 5 times.. sadly it didn't correspond to a memory increase. I'll try your build for a day and see how that affects things.

**Comment by andyholmes** [comment] 2018-12-18 11:15
> ...I also jump between different hotspots throughout the day so perhaps constant disconnections/reconnections could occasionally cause a memory leak somehow? Pure speculation.

Ah ha, good speculation! I think that causes it, since I've duplicated it a few times now by walking my phone to where another router picks up the signal.

I'm not sure how it exactly it happens or how to fix it, but this is a very good start to bad bug (for me it's almost always ~800mb :fearful:)

**Comment by andyholmes** [comment] 2018-12-19 08:48
> Great to hear you can reliably duplicate it! 

Well, not reliably :) It is a weird situation and I'm not entirely sure why it happens (this kind of race condition *should* already be addressed), or where the giant memory leak comes from. I noticed output like this:

```
[/service/lan.js:_onIncomingChannel:88]: "remote host 192.168.1.68"
[/service/lan.js:_onIncomingChannel:88]: "remote host 192.168.1.68"
[/service/lan.js:_onIncomingChannel:88]: "remote host 192.168.1.68"
[/service/lan.js:_onIncomingChannel:88]: "remote host 192.168.1.68"
[/service/device.js:_setConnected:309]: "Connected to Nexus 4 (14a7714d768b2003)"
```

So I guess there are a bunch if incoming connections and the wrong one resolves first, resulting in a dead connection. ~800MB is probably more than a couple months worth of packet data, so I guess maybe it's a dead socket reading tons of null bytes into nowhere or something?

In any case, here's an attempt at a fix, so if you could test this and see if it reliably fixes the problem I'll try and do the same. The approach is just to keep track of connections coming from a single host (eg. 192.168.1.68) and always favour the newest incoming connection, closing any current one. This might not work if your IP is changing between networks/hotspots, but it's unclear whether the connection lasts long enough to determine what *device* it's coming from or if there's only a chance to get the IP.

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2693967/gsconnect.andyholmes.github.io.zip)

**Comment by x0a** [comment] 2018-12-19 23:32
Very interesting, and it definitely looks like you might be correct as this build has been stable after about 10 hours,. I'd give it an extra 24 before I call it. I'll see about artificially inducing these disconnects/reconnects to really test your fix, but it's looking pretty good so far.
![screenshot from 2018-12-19 17-27-28](https://user-images.githubusercontent.com/13019784/50254370-6597fe80-03b3-11e9-9828-3211d31f2bf2.png)

**Comment by ferdnyc** [comment] 2018-12-20 18:10
You're _both_ on Ubuntu, right?

I wonder if that common thread is somehow meaningful? Because, I've **_never_** seen anything even remotely like this, running `v17` release. My Fedora 29 machine's two `gjs` processes, one started December 14 and the other started December 16, are sitting at 49MB and 10.6MB in resident memory, respectively. And I've never seen them waver from those svelte numbers. 

Granted, my PC:phone connection might be a bit more stable than average, but there are times when I'm at home with the phone in my pocket (not charging), in which case the WiFi would disconnect every time I lock it and reconnect every time it wakes up again, and still no hints of this.

(I was also wondering if Android version might be involved, but @x0a 's tablet is likely running an older release than my Android N phone, and both are Samsung so that's probably not significant.)

**Comment by x0a** [comment] 2018-12-20 23:14
@ferdnyc I tried something that I hadn't tried before, restarted my tablet. I hadn't figured it necessary since the service/app had been killed by Android dozens of times throughout the day. But since I've restarted last night I haven't seen memory rise above 35mb after 6 hours. 
![screenshot from 2018-12-20 17-01-50](https://user-images.githubusercontent.com/13019784/50315584-fd135500-0478-11e9-912d-7684c6e052c2.png).

I am running Android 4.4.2. Could be an obscure issue with the kdeconnect client. But I think it also lends credence to the idea that constant reconnections are responsible for the memory leak as restarting Android also kills any misbehaving services that could have been responsible for Android constantly having to kill the kdeconnect service.

**Comment by x0a** [comment] 2018-12-23 23:12
@ferdnyc I've been eager to try this and have been waiting for the bug to manifest itself again, but I haven't been able to reproduce the memory leak since I restarted my tablet (nearly 36 hours ago). Great news for me obviously since I don't have to keep killing GJS anymore, but bad news for debugging. I suppose if it doesn't show up again after a month we can chalk it up to a bad instance of KDEConnect and call it done?

**Comment by andyholmes** [comment] 2018-12-24 03:37
This might also be related to a bug fixed in kdeconnect-android ([d4d4849](https://github.com/KDE/kdeconnect-android/commit/d4d4849f158a4056feec5f17d14437c1480c8bf7)) where sockets were not being properly closed. GSConnect on the other hand, goes way over board when closing a channel, but that might still mean there's an obscure bug lurking somewhere.

I've haven't hit this bug in awhile myself, but I've also been running [nightly builds](https://binary-factory.kde.org/view/Android/job/kdeconnect_android/) on and off so that may have something to do with it. In any case, I'll probably release v18 soon regardless, since it's been some time since v17 and there are a lot of bug fixes. I'll probably just commit the "fix" I added anyways, since it doesn't seem to harm anything.

**Comment by andyholmes** [comment] 2019-01-15 05:50
How has this one been going? Personally this hasn't reoccurred for a very long time, safe to close it now?

**Comment by ivandotv** [comment] 2019-01-16 15:51
This is literally happening to me right now
![image](https://user-images.githubusercontent.com/390700/51260603-f102b080-19ae-11e9-9b19-b4a7d945cae0.png)

**Comment by ivandotv** [comment] 2019-01-17 17:35
I don't really know why it happens, maybe it has something to do with restarting the phone... I'm not really sure. I can't figure out if there is some kind of pattern to it.

**Comment by driscollw** [comment] 2019-01-23 06:41
This has happened to me as well a few times. Each time is was right after I closed my laptop lid with power attached. Disconnect power and take my device to another room and open the lid. Consistantly I hear my CPU fan ramp up. 700MB+ used. Haven't touched my phone in hours....but I do have two ubuntu systems connected to my phone.

**Comment by ferdnyc** [comment] 2019-01-23 15:38
I have actually, now, seen this exactly **once** — my occurrence looked exactly the same as @ivandotv (also on Fedora 29) — `gjs` was around 450MB in size. 

I have no idea what triggered it, and was unable to find any causes. (Interestingly, though, I'm on a desktop computer with no lid, no suspend beyond display sleep, etc.) But it's only ever been that one time. 

I've since restarted, and the `gjs` process running on my machine for the past 5 days is still < 80MB in size.

**Comment by driscollw** [comment] 2019-01-23 16:47
I will add though that I have never seen this issue on my VM running Ubuntu 18.04. Which is typically always running for days at a time.. It's always been my Thinkpad T420. I also have a lot of features turned off on my phone. When I open up the KDE Connect app the screen is blank, no presentation. I just wanted a few things to go over to my workstations. Just out of suspend it's 700MB+ with 25% CPU usage.

**Comment by ferdnyc** [comment] 2019-01-23 18:53
@driscollw 
> Just out of suspend it's 700MB+ with 25% CPU usage.

The **`gjs`** process, specifically, was using 25% of the CPU? (I assume that's on a 4-core processor, so one core pegged?) See, that's something else I've never seen — not from `gjs`, anyway. (I can get Firefox to do it by just looking at it funny.) Do you know how long the CPU spike lasted?

Even when the memory-consumption bug manifested for me, as in @ivandotv 's screenshot the CPU usage was still minimal. Heck, that 5-day-old `gjs` on my current machine only has a total of 5m14s of CPU time racked up over its entire lifetime... I don't recall it being significantly more even that one time it ballooned to 450MB. (Though, if the CPU spike only lasted briefly, it might not have really registered as a significant increase in accumulated time.)

**Comment by ivandotv** [comment] 2019-01-23 19:34
I'm using desktop computer

**Comment by driscollw** [comment] 2019-01-24 20:00
OK so today my VM Ubuntu 18.04 is doing it. See [Photo](http://bit.ly/2MscOwS)

**Comment by ferdnyc** [comment] 2019-01-24 21:35
@driscollw 's report inspired me to look at my own `gjs` process, and I was surprised to discover that it was up to 470 MB<sup>1</sup>. This is still the same (now) 6-day-old process that was only 80MB last night, so my best guess is that the size must've increased some time in the past 12-18 hours. 

That's a helpful narrowing of the window, since in my case the size increase still isn't associated with any sort of increased CPU usage... total CPU time for that `gjs` process is now just 7m24s, not significantly up from 5m14s over 24 hours ago.

Anyway, I first launched the GUI and ran "Generate Support Log". This is the entirety of what that produced:
```
GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Wed 2018-10-17 21:23:43 EDT, end at Thu 2019-01-24 16:13:39 EST. --
Jan 24 16:13:39 gjs[2834]: g_menu_item_set_attribute_value: assertion 'valid_attribute_name (attribute)' failed
```

Um. Seems a little... spare. So I ran `journalctl --user -b _PID=2834 > /tmp/gjs-journal.txt`, and the full output is attached: [gjs-journal.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2793700/gjs-journal.txt) (I've checked it for personally identifying data, nothing jumped out at me and I'm not particularly concerned.)

The lines that look interesting to me, because (a) I've never seen them before, and (b) they fall nicely within the time period in question, having been logged around 8 hours ago, are these. (Line-wrapped so you don't have to scroll horizontally.)
```
Jan 24 07:28:04 teevey gjs[2834]: Attempting to run a JS callback during garbage collection.
This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal
connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the
application, it has been blocked.
Jan 24 07:28:04 teevey gjs[2834]: The offending callback was AsyncReadyCallback().
Jan 24 07:28:04 teevey gjs[2834]: Attempting to run a JS callback during garbage collection.
This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal
connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the
application, it has been blocked.
Jan 24 07:28:04 teevey gjs[2834]: The offending callback was SourceFunc().
```
Other than that, everything that's visible in the log seems to be business as usual, mostly just hundreds and hundreds of lines of "`g_object_unref: assertion 'G_IS_OBJECT (object)' failed`".

#### Notes

1. (Actually, it's grown a bit more in just the past 5 minutes, now at 487 MB. It doesn't seem to be growing _regularly_, watching it in `top` most refreshes show no size change. In fact, the growth from 470 MB to 487 MB could be normal/meaningless, as it might've just been a consequence of me using "Generate Support Log".)

**Comment by driscollw** [comment] 2019-01-24 22:55
On my T420 as SOON as I opened my lid the CPU went strait to 25% 220MB to 525MB in a matter of 10 seconds. It was fine for about 10secs as I still had system monitor up from when I suspended it last night. GSConnect menu showing incorrect battery level. 

gjs was running fine last night when I suspended it.

**Comment by andyholmes** [comment] 2019-01-24 23:32
> Um. Seems a little... spare.

Yeah, after the third person posted a 10MB+ heap dump and several complaints about GSConnect being insecure because debug logging was left on by accident, it became obvious the debug tool was confusing users. The developer tool is also hidden behind a GAction now. So the usage is:

1. Open *Generate Support Log* dialog (debug logging is enabled)
2. Reproduce bug or action that doesn't work
3. Close *Generate Support Log* dialog (debug logging is disabled, log opens in text editor)

You can still turn on debug logging, but it must be done in dconf and whenever the *Generate Support Log* dialog *closes*, it disables it.

    JS ERROR: TypeError: packet.body.incomingCapabilities is undefined
                         _handleIdentity@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:270:1
                         attach@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:334:9
                         _onIncomingIdentity@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:244:13
                         Async*@/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:778:2
    JS WARNING: [/home/ferd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js 249]: reference to undefined property "code"

These lines here are probably the most helpful yet. It indicates that the Android app is sending a broken identity packet, which is only failing once `Channel.attach()` is called.

    Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
    The offending callback was AsyncReadyCallback().
    Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
    The offending callback was SourceFunc().

Probably this is an unresolved async function/Promise that eventually gets culled by GJS. Promises are queued in GJS in the GMainLoop with a custom GSource, but there's not much information here about which it is. Most likely it's some async function in `Lan.Channel` that never resolves or rejects because of the uncaught error in `Lan.Channel.attach()` and when it's eventually removed GSConnect stops leaking memory.

I just pushed 71337e9 which catches errors in `attach()` and closes the channel, but I'm not sure if that will fix the memory leak since I still can't reliably reproduce this problem (or at all anymore actually).

**Comment by driscollw** [comment] 2019-01-24 23:44
It's happened twice in the past hour for me. One thing I will add is that I am on a 5GHz wifi channel with an 6MB/s connection speed. Thinking more about this I often see this the most when my signal is poor. Out of suspend I sometimes have a ? where my wifi signal should be. Also my phone is on 5Ghz and has a poor signal in my Den. This morning when I stated that the power level was incorrect on my Ubuntu VM (Excellent Signal, right at AP) at 97% I was charging my phone in the Den.

**Comment by ferdnyc** [comment] 2019-01-25 18:01
> Yeah, after the third person posted a 10MB+ heap dump and several complaints about GSConnect being insecure because debug logging was left on by accident, it became obvious the debug tool was confusing users. 
Oh, yeah, getting rid of that switch makes total sense to me.

...So, here's another interesting wrinkle: That _very same_ `gjs` process on my machine — the one that's been running for > 7 days and as of now has racked up a grand total of 8m45s CPU time — is **back down** to only 90MB resident. Without restarting it, without any new interesting log messages being output, without any conscious action of my own that could account for the reduction in memory footprint.

So now I'm wondering if those `Attempting to run a JS callback during garbage collection` messages could be significant after all, or at least this could perhaps have something to do with the garbage collector. Perhaps they're signs of a GC run being interrupted/deferred, so that the memory in question does _eventually_ get released in a subsequent sweep. (Weird still that it's **so much** memory, but...)

**Comment by driscollw** [comment] 2019-01-26 00:22
Last night I sat my phone right next to my T420 for about 2 hours. I watched the memory usage go from about 22MB to 225MB in the course of two hours. I did not use either device. I just moved my mouse once in a while to see what is was currently using.

**Comment by Tids** [comment] 2019-02-12 22:11
It's the same for me on Arch Linux. The only thing I do with GSConnect is to sync notification from my phone to my desktop and yet I end at 400-800MiB at the end of the day

```

GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-02-07 00:17:10 CET, end at Tue 2019-02-12 23:10:01 CET. --
Feb 12 23:09:18 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 251236352/250851328/-385024, res+swap = 246235136/246235136/0
Feb 12 23:09:19 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 122286080/122286080/0, res+swap = 122343424/122343424/0
Feb 12 23:09:19 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 449200128/449400832/200704, res+swap = 444035072/444035072/0
Feb 12 23:09:20 org.gnome.Geary.desktop[10758]: Memory pressure relief: Total: res = 18378752/18378752/0, res+swap = 13615104/13615104/0
Feb 12 23:09:29 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 291098624/291098624/0, res+swap = 286150656/286150656/0
Feb 12 23:09:44 org.gnome.Shell.desktop[10758]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1600034 (GSConnect)
Feb 12 23:09:48 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 255680512/255410176/-270336, res+swap = 250839040/250839040/0
Feb 12 23:09:49 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 122277888/122277888/0, res+swap = 122339328/122339328/0
Feb 12 23:09:50 org.gnome.Geary.desktop[10758]: Memory pressure relief: Total: res = 18362368/18362368/0, res+swap = 13602816/13602816/0
Feb 12 23:09:51 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 449937408/449998848/61440, res+swap = 444633088/444633088/0
Feb 12 23:10:00 org.gnome.Shell.desktop[10758]: Memory pressure relief: Total: res = 290807808/291045376/237568, res+swap = 286105600/286105600/0
Feb 12 23:10:01 org.gnome.Shell.Extensions.GSConnect[11230]: [/service/lan.js:broadcast:273]: "Identifying to 192.168.2.101"
```

**Comment by andyholmes** [comment] 2019-02-12 23:17
Hi, since I still can't reproduce this locally I rely on people who can to test the fixes I apply. Here is a Zip built from master which includes 71337e9 from the Zip above:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2858061/gsconnect%40andyholmes.github.io.zip)

See [Install from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) in the Wiki for instructions.

**Comment by andyholmes** [comment] 2019-02-13 00:57
I've pushed 5401bc2 with an additional attempt to plug this leak. As detailed in the commit message, this comes with the risk that some clients may be unable to connect at all, so this won't be in a stable release unless I get lots of testing and confirmation. Here is an updated Zip:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2858350/gsconnect%40andyholmes.github.io.zip)

**Comment by Tids** [comment] 2019-02-13 09:06
Thanks!
Just to ask that: Whats a normal amount of ram gjs/gsconnect should use?

**Comment by andyholmes** [comment] 2019-02-13 09:18
Normal memory usage is about 30-40MB (resident - shared).

**Comment by Tids** [comment] 2019-02-14 09:21
Looks good. yesterdays normal usage at work and at home. gjs still chills at 24-36MiB. Usually I hit the bug every day once or twice at some point, so I'm really happy with what I see now. I'll go on with the testing for some longer time and report back

**Comment by marosoft** [comment] 2019-03-11 22:05
@andyholmes I found something interesting as well. However I did not test it yet as I would need to clone and build the plugin.

There is a missing 'await' in front of 'this.__cache_write()'
as you can see here: https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/plugins/base.js#L196 

__cache_write method returns a promise and because the code does not wait for it to be resolved it creates a loop.  The data to be cached is not being released from the memory:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/__init__.js#L184

This is just a hypothetical scenario as I could not test it yet.

**Comment by edwinfoss** [comment] 2019-03-15 12:26
I found a 100 thousand lines of this in my journalctl log after I noticed that gjs locks in one core at 100% cpu usage raising my cpu temperature:
`JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags_onIncomingIdentity@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:171:24`

**Comment by andyholmes** [comment] 2019-03-15 22:27
> I found a 100 thousand lines of this in my journalctl log after I noticed that gjs locks in one core at 100% cpu usage raising my cpu temperature:

This is not related to high memory usage. Most likely you are using a distribution which has already updated to glib2 `>= 2.60.0`. You should update to v21-rc2 or wait until the appropriate fix is backported to glib2.

**Comment by andyholmes** [comment] 2019-03-15 22:30
Since there have been no further reports of the original high-memory usage bug, I'm going to close this issue. I believe the original issue was fixed in 5401bc2. Thanks for everyone help with logs and testing on this bug!

**Closed by andyholmes** 2019-03-15 22:30 UTC
Labels: bug, help wanted

**Comment by vberthet** [comment] 2019-06-14 10:37
I've the same issue with GSConnect 24 on Ubuntu 18.04.

> Killed process 11014 (gjs) total-vm:27882468kB, anon-rss:19246980kB, file-rss:0kB, shmem-rss:40kB

> Out of memory: Kill process 11014 (gjs) score 723 or sacrifice child

I'll try to send an heap file next time, the process was killed by OOM before a can get on :(

**Comment by andyholmes** [comment] 2019-06-14 22:50
@vberthet this is probably a different bug than the one fixed in this issue. Can you open a new issue with logs for this?

**Comment by Crucizer** [comment] 2020-12-22 07:39
I have the same issue!

**Comment by pegasusearl** [comment] 2022-03-11 03:42
Hello, I'm not sure if this one is related but I experienced giant memory usage as well.
![11_10-10-03_381](https://user-images.githubusercontent.com/23167087/157795776-88166478-f276-4f78-a83c-d276abd072fc.png)

In my case it's caused by a [software](https://github.com/elesiuta/picosnitch) that send massive amount of notifications. Perhaps the more notification in a session, the bigger ram usage is.

Here is the video of my reproduction:
https://www.youtube.com/watch?v=pYR2W7_bsjQ&list=PLhcbq4A0YXYCYHE-XN5-nQcBam4Vq_DKj&index=1

**Comment by ferdnyc** [comment] 2022-03-15 02:01
@pegasusearl 

Hm, that's interesting! Some differential diagnosis:

1. Are the notifications originating on the Linux side, or the Android side? (I'm not familiar with that application.)
1. Whichever side they're on, do you have that device relaying notifications to peer devices?
1. If it's on the Android side, what happens if you block relaying of that app's notifications?
1. If it's on the Linux side and you're sharing notifications,
    1. Does the memory leak still happen if you disable notification sharing?
    1. Does it still happen if you disable the notification plugin **completely**?
1. If it's on the Linux side and you're NOT sharing, does it still happen if you enable sharing? (I'm thinking maybe there's a leak where notifications that aren't being sent across the wire aren't properly disposed of.)

**Comment by pegasusearl** [comment] 2022-03-15 13:37
1. Linux side
2. no
3. -
4~5. there is no notification shared. At the time I didn't connect to any android devices. I only use GSconnect occasionally to copy files. I never do anything else with it. I'm not sure how do I do that.
I already connected to my android device, in GSconnect I already enabled notification in Advanced Setting and make sure "Share Notification" is checked. And then in KDEconnect I made sure Notification Sync is enabled, and then made sure notification plugin does not require more permission.
But notification is not sent when I call `notify-send` on linux. `notify-send` in GSconnect setting is also checked.

About that app:
It was [picosnitch](https://elesiuta.github.io/picosnitch/), it's bug that [sends massive amount of notification at short period](https://github.com/elesiuta/picosnitch/issues/14) .

This can also be reproduced by calling `notify-send` every 0.05 second for few seconds. But doing that might make gnome unresponsive when opening notification window.

I'm not sure if there is any case where user would receive a lot of notification. One thing that I can think of is if I enable all notification instead of just mentions for [Discord](https://discord.com/) and run it for long period of time without rebooting.

Doing the discord thing appears to have similar effect. Memory usage slowly increase, sometimes it went down but overall it kept increasing. In my case it's still not a big problem.

Perhaps this is different than what people discussed above.

**Comment by ferdnyc** [comment] 2022-03-16 00:21
@pegasusearl 

Ah, sorry, I was on my phone when I sent that previous reply and couldn't look into things too deeply.

On the Android side, to receive notifications _from_ a Linux peer you'd want the "Receive notifications" plugin enabled for that peer ­— "Notification sync" enables sharing in the other direction, for notifications that originate locally on the Android device.

On the Linux side, the Notifications plugin handles sharing in both directions, unlike on Android where it's two separate plugins. It can be enabled/disabled under "Advanced". (It's normally enabled). When enabled, the Notifications settings panel lets you enable/disable global notification _sending_, and then if that's enabled, also disable sharing for specific Linux application sources.

One thing I notice is that the DBus notification handler unpacks the notification contents anytime a notification comes in, because it handles managing the applications list unconditionally. Only _then_ does it check whether notification sharing is enabled. If not, it bails, otherwise it attempts to generate a message over the wire to the connected peer. 

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/aa02b6ad1457bbe936dba0ff0ecc933ccd4e676e/src/service/plugins/notification.js#L232-L265

So, it's possible there's some sort of leak in `GLib.Variant.deepUnpack()` or `Gio.Icon.deserialize()`, which are [used by `notification.full_unpack()`](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/aa02b6ad1457bbe936dba0ff0ecc933ccd4e676e/src/service/__init__.js#L270-L305) to unpack the notification payload. (That's another thing, this may only occur for notifications with a certain type of associated icon — you can simulate that by running `notify-send` with a `-i` argument and providing either a stock-icon name, or the path to an icon file. The code path for each is different.)

The other thing, though, is that AFAICT all of this plugin code runs on a per-peer basis. So if you didn't have any peers connected to the Linux machine at the time, none of this should even have been _running_. If that's the case, I'm really at a loss as to how the gjs process could've racked up so much memory usage. Unless perhaps we're not correctly dropping our DBus listener connections when peers disconnect, so that we'd still be bombarded with unhandled notifications.

You don't happen to see any messages like these in your user journal, referencing the GSConnect session bus connection, do you?

> The maximum number of pending replies for "(some DBus address)" (connection details) has been reached


(I know what that message would look like because, in an unrelated problem, I've been getting flooded with them for `goa-identity-service` for some time now.)
