### ISSUE TITLE
GSconnect stopped working in Ubuntu 19.10 / Gnome 3.34.1

### ISSUE THREAD

**Issue by Saroumane** [andyholmes/gnome-shell-extension-gsconnect#685] opened 2019-10-31 17:25 UTC
Settings of extension"GS connect" shows "Waiting for service" in Devices section. No icon in top panel.

Ubuntu 19.10
GNOME Shell 3.34.1
Kernel 5.3.0-19-generic
![Screenshot from 2019-10-31 18-24-18](https://user-images.githubusercontent.com/22261137/67970698-b3080d80-fc0b-11e9-9584-d725f792acf1.png)

**Comment by andyholmes** [comment] 2019-10-31 19:01
Duplicate of #672 

This is fixed in [v28-rc1](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v28-rc1) and will be released in a few days as v28.

**Closed by andyholmes** 2019-10-31 19:01 UTC
Labels: duplicate, fixed in master

**Comment by kolserdav** [comment] 2019-12-21 00:37
Hello!
Today I uninstalled the old version and reinstalled it, but I have the same problem on Ubuntu 19.10.

**Comment by ferdnyc** [comment] 2019-12-21 03:31
@kolserdav Installed which version? The latest release is `v31` on extensions.gnome.org, if you install (or installed) that version to replace `v28` you _may_ need to reboot after (or at least log out/in) to kick the hamsters.

**Comment by kolserdav** [comment] 2019-12-21 14:41
@ferdnyc thanks for the answer. Installed version v31, and you were right, after rebooting my computer everything worked. Sorry, I myself had to guess. Thanks.
