### ISSUE TITLE
GSConnect Stuck on waiting for service v28

### ISSUE THREAD

**Issue by kiljoy001** [andyholmes/gnome-shell-extension-gsconnect#767] opened 2020-02-17 20:37 UTC
Not sure why, but it's not working:
![image](https://user-images.githubusercontent.com/8892111/74684896-ec946280-5181-11ea-9c56-3c41747086d2.png)

Here is the version number:
![image](https://user-images.githubusercontent.com/8892111/74685002-206f8800-5182-11ea-8f2d-2d1e6460b525.png)

log:
`Logs begin at Sat 2020-02-15 11:42:56 PST, end at Mon 2020-02-17 12:36:54 PST. --
Feb 17 12:36:02 shutter.desktop[1189]: GLib-CRITICAL **: Source ID 6782 was not found when attempting to remove it at /usr/bin/shutter line 7262, <DATA> line 19.
Feb 17 12:36:02 shutter.desktop[1189]: GLib-CRITICAL **: Source ID 5288 was not found when attempting to remove it at /usr/share/perl5/Shutter/App/ShutterNotification.pm line 186, <DATA> line 19.
Feb 17 12:36:02 org.gnome.Shell.desktop[38244]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5400655 (/home/scot)
Feb 17 12:36:29 shutter.desktop[1189]: GLib-CRITICAL **: Source ID 9564 was not found when attempting to remove it at /usr/bin/shutter line 7262, <DATA> line 19.
Feb 17 12:36:54 gjs[62915]: GtkDialog mapped without a transient parent. This is discouraged.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Encoding raw at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Dimensions: 16 x 16 at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Copy pixels == false at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Encoding raw at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Dimensions: 16 x 16 at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891, <DATA> line 19.
Feb 17 12:36:54 shutter.desktop[1189]: GdkPixbuf-LOG **:         Copy pixels == false at /usr/bin/shutter line 2891, <DATA> line 19.`

**Comment by andyholmes** [comment] 2020-02-18 04:08
Most likely either extensions are all disabled in GNOME Tweaks or the service is disabled in the User Menu under *Mobile Settings*.

Unfortunately if the problem is elsewhere, it can't be fixed since we don't accept bug reports for older versions of GNOME Shell.

**Comment by andyholmes** [comment] 2020-03-04 04:47
Closing since this is for an older version and we're starting to look to GNOME 3.36 now.

**Closed by andyholmes** 2020-03-04 04:47 UTC
