### ISSUE TITLE
Not able to open gsconnect setting menu in gnome 3.31

### ISSUE THREAD

**Issue by raushankumar27** [andyholmes/gnome-shell-extension-gsconnect#469] opened 2019-02-19 15:29 UTC
**Describe the bug**
Not able to open gsconnect setting menu in gnome 3.31

**To Reproduce**
open  gsconnect setting  from tweak tools or from user menu 

**Expected behavior**
It should open gsonnect menu

```
Clicking on the setting menu gave no response
```

**System Details :**
 - GSConnect version: 20 and 21rc1
   - Installed from: github
 - GNOME/Shell version: 3.31
 - Distro/Release: ubuntu 19.04

**Comment by andyholmes** [comment] 2019-02-20 06:16
Thanks for reporting, I believe this is a duplicate of #468. Please follow that issue for progress.

Since neither GNOME 3.32 or Ubuntu 19.04 have been released, this system should be considered unsupported for the time being. This probably complicated by the fact that Ubuntu 19.04 is still shipping gjs-1.54.3.

**Closed by andyholmes** 2019-02-20 06:17 UTC
Labels: duplicate
