### ISSUE TITLE
GSConnect stuck on "Waiting for Service"

### ISSUE THREAD

**Issue by hellocatfood** [andyholmes/gnome-shell-extension-gsconnect#682] opened 2019-10-28 11:52 UTC
I have installed GSConnect v27 on Ubuntu 19.04 and now 19.10. On both installations whenever I launch the extension on my computer the window just shows "Waiting for service" and nothing happens. See screenshot below.

![Screenshot from 2019-10-28 11-51-28](https://user-images.githubusercontent.com/151947/67676409-54c3fc00-f979-11e9-8af6-c08d08ffee96.png)

**Support Log**

Unfortunately nothing in the Support Log

**System Details (please complete the following information):**

GSConnect Version: 27
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu

Using a Google Pixel 3
KDE Connect version 1.13.2

My computer doesn't show up as a device my phone can connect to.

**Comment by andyholmes** [comment] 2019-10-28 20:32
Duplicate of #672

This was fixed in f28250e and will be in v28. This Zip contains that fix:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3765852/gsconnect%40andyholmes.github.io.zip)

**Closed by andyholmes** 2019-10-28 20:32 UTC
