### ISSUE TITLE
android phone is getting disconnected, when it is locked

### ISSUE THREAD

**Issue by abkiran** [andyholmes/gnome-shell-extension-gsconnect#474] opened 2019-02-26 08:59 UTC
android phone is getting disconnected, when it is locked

**Comment by andyholmes** [comment] 2019-02-26 15:07
Hi, I believe this is a duplicate of #272. Please see the upstream bug report at https://bugs.kde.org/show_bug.cgi?id=404163.

**Closed by andyholmes** 2019-02-26 15:07 UTC
Labels: duplicate
