### ISSUE TITLE
Cannot mount phone, nothing happens, no log

### ISSUE THREAD

**Issue by arun-gurung** [andyholmes/gnome-shell-extension-gsconnect#544] opened 2019-05-21 12:03 UTC
**Describe the bug**
When clicking "mount" nothing happens. But I can send files.

**Debug output**
If you have been able to reproduce the problem with debugging enabled (see [instructions in the wiki](wiki/Debugging)), paste any log messages related to this issue between the two ``` lines below.

Tried to generate support log, but it's empty.

**System Details (please complete the following information):**
 - GSConnect version: 23
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28.2
 - Distro/Release: CentOS 7.5
**GSConnect environment (if applicable):**
 - Paired Device(s): Cat S61

**Additional context**

I have installed the sshfs and it works with other machines.

**Comment by andyholmes** [comment] 2019-05-21 23:15
Please see the instructions in the wiki to [Generate a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log). It's necessary to leave the dialog open while reproducing the error, only closing it after the error has occurred.

**Comment by arun-gurung** [comment] 2019-05-22 08:49
This is all I get:


[gsconnect.PRW01Z.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3206487/gsconnect.PRW01Z.txt)

**Comment by ferdnyc** [comment] 2019-05-22 15:03
\*fistshake\* CentOS!

The `--no-host` flag was added to the `journalctl` command [over three years ago](https://github.com/poettering/systemd/commit/f78aa7555717158e3ba95b8d7295079ab996d722). Which is clearly far too new-fangled for venerable CentOS. **#KidsToday** :laughing: 

@arun-gurung The _easiest_ short-term fix, TBH, is probably for you to just edit the file `$HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/settings.js`, and remove the `'--no-host'` entry from the list on line 53. Here's the before/after in diff form:

```diff
diff --git a/service/ui/settings.js b/service/ui/settings.js
index 7054c39..5b38241 100644
--- a/service/ui/settings.js
+++ b/service/ui/settings.js
@@ -50,7 +50,7 @@ async function generateSupportLog(time) {
         // FIXME: BSD???
         let proc = new Gio.Subprocess({
             flags: Gio.SubprocessFlags.STDOUT_PIPE | Gio.SubprocessFlags.STDERR_MERGE,
-            argv: ['journalctl', '--no-host', '--since', time]
+            argv: ['journalctl', '--since', time]
         });
         proc.init(null);
 
```

When that line looks like the lower/green "after" version, save the file, log out and log in again (or restart the system) to reload the GSConnect service, and you should be able to collect a debug log.

**Comment by arun-gurung** [comment] 2019-05-22 16:54
Thanks, now the log is here!

[gsconnect.3VLD2Z.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3208443/gsconnect.3VLD2Z.txt)

**Comment by andyholmes** [comment] 2019-05-25 04:01
Thanks for the log. In you log there is a record of GSConnect sending the request:

```js
[/service/protocol/core.js:send:220]: Cat: {
    "id": 1558544012814,
    "type": "kdeconnect.sftp.request",
    "body": {
     "startBrowsing": true
    }
}
```
If the device is simply not responding, this is probably a bug in the Android app. I'd make a guess this is the same problem described [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/516#issuecomment-485251087), but you'd need a logcat from Android to be sure.

There seem to be a number of problems happening with SFTP since kdeconnect-android 1.12, I'm just not sure they're problems that can be fixed in GSConnect.

**Comment by triptronics** [comment] 2019-05-27 18:55
Hello,

I have the exact same issue and my logs are identical. It's something to do with the latest version of the KDE Connect app. I went to Apps > KDE Connect then I force killed the app and restarted. Then the mount worked again. On a Galaxy S8, latest update of android.

**Closed** 2019-05-27 23:46 UTC
Labels: upstream
