### ISSUE TITLE
GSConnect flooding all system logs with great speed.

### ISSUE THREAD

**Issue by different55** [andyholmes/gnome-shell-extension-gsconnect#470] opened 2019-02-21 21:04 UTC
**Describe the bug**
Woke up this morning to a notification that my root partition had only 1.0GiB left. Turns out /var/log/messages, user.log, and syslog were taking up 20.4GiB. Of that, 20.4GiB of these messages belonged to GSConnect:

    root@Chalupa /v/log# fgrep -h org.gnome.Shell.Extensions.GSConnect messages user.log syslog | wc -c
    21907497712
    root@Chalupa /v/log# units -1 "21907497712 bytes" "GiB"
    	* 20.402947

And they were all lines like these:

    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 0.35678979754447937 0.5700228586792946 0.5075015611946583
    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 90 38 0
    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 0.27108334004879 0.6836964190006256 0.8819757401943207
    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 69 46 0
    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 0.5200110729783773 0.5922613367438316 0.5070155197754502
    Feb 21 07:36:38 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 132 40 0

I tried truncating /var/log/messages so I could install a new package and less than 3 seconds later it was already flooded with 1.3MiB of this stuff again. Now it's at 60MiB and still climbing.

**To Reproduce**
1. Enable GSConnect
2. Watch the logs fill up.

**Expected behavior**
System logs should not be flooded.

**Debug output**
Support logging was not functional while the root partition was full. clicking "Review log" does not open my default text editor. Or any text editor. Truncating /var/log/messages allowed me to grab this kinda unhelpful-looking debug log.

```
GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
```

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Debian Sid

**GSConnect environment (if applicable):**
 - Paired Device(s): Droid Turbo 2
 - KDE Connect app version: 1.10.1

**Additional context**
Going through the logs it looks like it started this morning just before I woke up. It spit out something slightly different from the normal pattern, idk if it's helpful or not:

    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 1000
    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 1.0 0.2663545845364998 0.0
    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 0.2801159471273422 0.060832321643829346 0.3742794841527939
    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 71 4 0
    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 0.20847094058990479 0.5290985833853483 0.14583763480186462
    Feb 21 07:36:29 Chalupa org.gnome.Shell.Extensions.GSConnect[1357]: 53 35 0

and then the normal pattern continued on after that.

**Comment by ferdnyc** [comment] 2019-02-21 23:52
@different55 

Yeah, sorry, the support-logs functionality currently assumes the presence of systemd / journalctl, so it wouldn't function on a syslog system. (Debian _still_ isn't using systemd, as of sid? Huh.) It wouldn't have really helped you anyway, as it's meant for collecting logs while reproducing problems — only log messages generated after starting the log collection (generated by user actions to reproduce the issue) are captured. Or, would be, if journald was present.

@andyholmes the developer may be able to say more definitively, but I'm trying to find _anywhere_ in the code where GSConnect would just log bare numbers with no accompanying useful information. I'm trying, and failing. It doesn't match his coding style at all, in my experience. I'm at a loss to say where those logs are even coming from; I've never seen anything remotely like them when using GSConnect, but then I've never run it in a syslog environment.

One thing you could check is whether GSConnect is set for debugging. This command will show the dconf value for that setting:
```bash
gsettings --schemadir \
~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/schemas/ \
get org.gnome.Shell.Extensions.GSConnect debug
```
If it returns "true", turn it off with:
```bash
gsettings --schemadir \
~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/schemas/ \
set org.gnome.Shell.Extensions.GSConnect debug false
```

Also, can you check what the identity of process 1357 is on your system? (Assuming the messages are still logging with that identifier.) It's odd that the GJS process ID reported by GSConnect is different from the one in the log messages. `cat /proc/1357/cmdline|xargs -0 echo` will format the command line for that process.

**Comment by different55** [comment] 2019-02-22 02:46
>Yeah, sorry, the support-logs functionality currently assumes the presence of systemd / journalctl, so it wouldn't function on a syslog system. (Debian _still_ isn't using systemd, as of sid? Huh.)

I'm definitely using systemd right now. Journalctl's here, too. Debian made the switch as of like Jessie which is nearly 2 releases ago. Way, way out of my depth here but don't some syslog mirroring services exist for systemd?

> I'm trying to find _anywhere_ in the code where GSConnect would just log bare numbers with no accompanying useful information. I'm trying, and failing.

I didn't catch anything like that in my stroll through GSConnect, either, but it wasn't very exhaustive at all. I posted the bug report figuring the dev would know better what might be going on.

> One thing you could check is whether GSConnect is set for debugging.

gsettings is returning false.

**Comment by different55** [comment] 2019-02-22 03:38
Alright, strange turn of events, I disabled GSConnect but just got another "Root partition low" notification and sure enough GSConnect is still stuffing the logs full. There's still one GSConnect process going even with the extension disabled, `gjs /home/diff/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js` so it must be this lil guy that's going nuts.

**Comment by ferdnyc** [comment] 2019-02-22 11:21
> There's still a handful of GSConnect processes going even with the extension disabled, 

Yeah, disabling the Shell extension won't kill the background processes — that's intentional and necessary, since Gnome Shell effectively disables its extensions every time it locks the screen, even. So `daemon.js` exists to stay running independent of the extension, and it keeps the connection between the computer and the mobile device(s) alive so that messages can still be passed back and forth. (The others are presumably the browser extension(s) and/or Nautilus plugin, their lifecycle is managed by those applications.)

The main `daemon.js` process is _started_ by the Shell extension, so once that's disabled the daemon can be killed and it won't respawn. Or, a logout/login cycle will terminate it, and it won't be started again until the extension is next enabled.

> `gjs /home/diff/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js` so it must be this lil guy that's going nuts.

\*nod\* AFAIK that's the only code that logs with the identity `org.gnome.Shell.Extensions.GSConnect`, so that had to be the one. (Presumably that's process `1357`.) Killing it will stop the log storm, I'm sure, I just wish I knew where those messages were _coming from_ in the first place. Especially if debugging isn't enabled. 

I suppose it could even be the `STDOUT` of one of the _other_ commands the daemon launches, now that I think of it. GSConnect v19 used several external programs to provide various features — `fusermount`, `openssl`, `ssh-add`, `ssh-keygen`, `sshfs`, `journalctl` `canberra-gtk-play`, its own `service/components/folks.py`... plus anything configured in the `runcommand` plugin, but presumably there's nothing there on your system.

It **shouldn't** be calling any of those programs repeatedly like that, so even on the off chance one of them is behaving unexpectedly and producing those messages, the frequency is still hard to explain.

> I'm definitely using systemd right now. Journalctl's here, too. Debian made the switch as of like Jessie which is nearly 2 releases ago. Way, way out of my depth here but don't some syslog mirroring services exist for systemd?

I _assume_ so, though honestly I don't know anything about them either. I'm surprised things would be set up that way, since it's kind of a "worst of both worlds" scenario. Flat-file mirrors like that defeat the protections `journald` has against exactly this scenario. 

If the messages _were_ going to the journal exclusively, the problem of them filling up your disk wouldn't occur, since `journald` both (a) uses a message catalog, and automatically de-duplicates messages, so repeated logs take up almost no space at all; and (b) it has a disk-space cap. From the `journald.conf(5)` man page:
> SystemMaxUse= and RuntimeMaxUse= control how much disk space the
> journal may use up at most.  SystemKeepFree= and RuntimeKeepFree=
> control how much disk space systemd-journald shall leave free for
> other uses.  systemd-journald will respect both limits and use the
> smaller of the two values.
> 
> The first pair defaults to 10% and the second to 15% of the size of
> the respective file system, but each value is capped to 4G.

**Comment by ferdnyc** [comment] 2019-02-22 11:25
(That last part isn't in any way meant to excuse the storm of log messages, nor to lessen the severity of the problem and the need to track down what's causing it.)

**Comment by different55** [comment] 2019-02-22 14:14
>*nod* AFAIK that's the only code that logs with the identity `org.gnome.Shell.Extensions.GSConnect`, so that had to be the one. (Presumably that's process `1357`.) Killing it will stop the log storm, I'm sure, I just wish I knew where those messages were _coming from_ in the first place. Especially if debugging isn't enabled.

Not sure if this is to be expected or not but the daemon.js processes are PIDs 1793 and 1798-1808. `cat /proc/1357/cmdline` spits out `/usr/bin/dbus-daemon--session--address=systemd:--nofork--nopidfile--systemd-activation--syslog-only`

Woke up this morning and it looks like the onslaught stopped last night just past midnight.

>plus anything configured in the `runcommand` plugin, but presumably there's nothing there on your system.

And. Now that you mention I'm pretty sure I know the culprit. I *said* it started yesterday morning just before I woke up, but in light of this, it was probably more "before I got out of bed." And specifically "After I rolled over and used GSConnect to turn on the lights so I wouldn't fall back asleep" with a script that I just verified spit out pairs of 3 "random" floats and 3 matching ints with great speed as debug info. I left it running through the day and shut it off just past midnight when I went to bed, which is when it stopped.

So there's our answer. Not sure if I should go ahead and close this or if it could be argued that GSConnect could handle this better, maybe it'd be possible to silence stdout or somehow "intercept" stdout and tack on a little blame reassignment to each line? Maybe just in the case of crazy, unpredictable user commands :P

**Comment by andyholmes** [comment] 2019-02-22 15:51
> Not sure if I should go ahead and close this or if it could be argued that GSConnect could handle this better, maybe it'd be possible to silence stdout or somehow "intercept" stdout and tack on a little blame reassignment to each line?

These are both possible, but both would have consequences. Silencing stdout/stderr is pretty simple, but comes with the risk that you'll just never get that output if something goes wrong (or you want that output). It could be unsilenced if 'debug' is enabled, but only at the time of execution.

Intercepting stdout/stderr could be more costly. Output can be read in a dedicated thread, but to prefix the output such as `Command Name: [output]` we'd have to return to the main thread after each line to do it and the log message itself is probably synchronous under the hood (actually I think logging is asynchronous, but the `log()` call itself is not).

Actually I think the `runcommand` launcher itself is pretty crude, and probably could leave zombie procs everywhere, I just haven't looked at that plugin in a very long time :)

**Comment by ferdnyc** [comment] 2019-02-22 16:16
I'm just glad we got that sorted out! :+1: And that I get to apply that ^^ label to it. 

(Though I'm going to hold off closing it, unless @andyholmes decides to, as I agree it's worth at least spitballing how `runcommand` could maybe safeguard against this. Perhaps just a limiter on the runtime of any commands launched through the plugin, kill them after N seconds or whatever? It'd just mean if you want to use it to launch `vlc` or whatever, you have to make sure the process detaches.)

**Comment by ferdnyc** [comment] 2019-02-22 16:28
@different55 
> specifically "After I rolled over and used GSConnect to turn on the lights so I wouldn't fall back asleep" with a script that I just verified spit out pairs of 3 "random" floats and 3 matching ints with great speed as debug info.

I love that you then failed to _recognize_ that output even when it was staring you in in the face from your log files, and I'm over here going "There's _nothing_ in the code that outputs anything like this, it's totally against Andy's entire coding style!" No sarcasm or insult intended whatsoever. it's **totally** the sort of thing I would do. I don't have enough fingers and toes to count the number of problems I've had to deal with, all the while knowing full well that I created them for myself in the first place. :laughing: 

(Oh, right, and: Edit your script to output useful information or nothing at all! **#YoullThankMeLater**) :wink:

**Comment by andyholmes** [comment] 2019-03-06 22:15
Going to close this one. I don't think there's a good solution for GSConnect to deal with these sorts of problems in-house. Probably it should just be considered a user-beware feature since there's really nothing stopping someone from doing *anything* terrible in an external command.

**Closed by andyholmes** 2019-03-06 22:15 UTC
Labels: solved elsewhere

**Comment by jogaman** [comment] 2021-12-02 13:08
I've been staring at this thread for a good 10 minutes after running into this issue. It looks like you have a solution - but what is it?? Is there a layman way to understand what you did to stop gsconnect from flooding the syslog? many thanks!

**Comment by different55** [comment] 2021-12-02 16:25
The thing flooding the syslog was one of my own programs spewing debug information, launched as a command from my phone. Wasn't a problem when launched from my PC, because stdout just vanished into the void. But launching it from my phone, GSConnect funnels all stdout of the things it launches into the syslog which slowly filled up my disk.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jogaman** [comment] 2021-12-02 16:26
Aha thank you! For me it happens on pop os 21.04...
