### ISSUE TITLE
Messaging not working on UTF-8 contacts

### ISSUE THREAD

**Issue by ondrejkolin** [andyholmes/gnome-shell-extension-gsconnect#587] opened 2019-08-14 09:16 UTC
**Describe the bug**
Contacts with "ěščřžýáíé" in name are not loading into messaging

**Steps To Reproduce:**

1. Go to 'Messaging'
2. Click on '+'
3. Search for my sister "Kateřina"
4. The titlebar changes, but messages don't load

**Expected behavior**

All messages should be loaded into the interface

**Screenshots**

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect Version: 24
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Tue 2019-03-26 19:08:01 CET, end at Wed 2019-08-14 11:13:31 CEST. --
srp 14 11:13:04 org.gnome.Shell.desktop[2830]: libinput error: client bug: timer event19 debounce: offset negative (-26ms)
srp 14 11:13:04 org.gnome.Shell.desktop[2830]: libinput error: client bug: timer event19 debounce short: offset negative (-39ms)
srp 14 11:13:11 systemd[1287]: Started dbus-:1.2-org.gnome.gedit@2.service.
srp 14 11:13:13 systemd[1287]: dbus-:1.2-org.gnome.gedit@2.service: Succeeded.
srp 14 11:13:18 org.gnome.Shell.desktop[2830]: libinput error: client bug: timer event19 debounce: offset negative (-37ms)
srp 14 11:13:18 org.gnome.Shell.desktop[2830]: libinput error: client bug: timer event19 debounce short: offset negative (-50ms)
srp 14 11:13:28 gjs[3375]: JS ERROR: TypeError: thread[0].address is undefined
                           _populateMessages@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:369:17
                           _init@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:298:9
                           set address@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:766:28
                           _onConversationSelected@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:877:13
                           @/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
srp 14 11:13:29 gjs[3375]: JS ERROR: TypeError: thread[0].address is undefined
                           _populateMessages@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:369:17
                           _init@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:298:9
                           set address@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:766:28
                           _onConversationSelected@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:877:13
                           @/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
srp 14 11:13:30 gjs[3375]: JS ERROR: TypeError: thread[0].address is undefined
                           _populateMessages@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:369:17
                           _init@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:298:9
                           set address@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:766:28
                           _onConversationSelected@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:877:13
                           @/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
srp 14 11:13:31 gjs[3375]: JS ERROR: TypeError: thread[0].address is undefined
                           _populateMessages@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:369:17
                           _init@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:298:9
                           set address@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:766:28
                           _onConversationSelected@/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:877:13
                           @/home/ondrejkolin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
```

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** Gnome Extensions
 - **GNOME/Shell version:** 3.32.2
 - **Distro/Release:** Fedora 30

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [Xiaomi Redmi 4 Note ]
 - **KDE Connect app version:** 1.12.9
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

**Comment by ondrejkolin** [comment] 2019-08-14 09:29
Contact details (changed ciphers in phone number) from contacts.json
```
"d037d11f0097616c7392db044d7e03abdd253397": {
    "id": "d037d11f0097616c7392db044d7e03abdd253397",
    "name": "Kačenka",
    "numbers": [
      {
        "value": "+420123456789",
        "type": "cell"
      }
    ],
    "origin": "folks",
    "avatar": "/home/ondrejkolin/.cache/evolution/addressbook/b68e9cbc6e899994747d9e044bda727c580c7bc0/PHOTO-dcc6880c155a2addafc9ecd6423a217e5014c5af-11.jpeg"
  },
```

**Comment by andyholmes** [comment] 2019-08-18 08:24
I believe this is probably a duplicate of #562 and should be fixed in master and v25-rc3.

**Closed by andyholmes** 2019-08-18 08:24 UTC
