### ISSUE TITLE
GSConnect v40 fails to install on Ubuntu 20.04 with latest updates

### ISSUE THREAD

**Issue by mcl21014** [andyholmes/gnome-shell-extension-gsconnect#917] opened 2020-08-15 13:58 UTC
**Describe the bug**
Attempting to install or upgrade to v40 throws an error.

**Steps To Reproduce:**

1. Go to https://extensions.gnome.org/extension/1319/gsconnect/ . Ensure chrome-gnome-shell is installed as well as the GNOME shell integration extension for Firefox or a Chromium based browser.
2. Click on the off button to try to turn it to on.
4. Generic red error is thrown.

**Expected behavior**
Extension should still install on Ubuntu 20.04, as GNOME 3.36 is the latest stable version as far as I'm aware.

**Screenshots**
![Screenshot from 2020-08-15 09-46-29](https://user-images.githubusercontent.com/3611312/90313712-a4f65580-dedc-11ea-9946-e534145f9225.png)

**Support Log**

Please comment on where to find the logs for failed installations of GNOME shell extensions. I can't generate a support log via the app when it won't install. I searched the GNOME logs application for "gsconnect" (w/o quotes) and will attach the results. I didn't see anything interesting there, so let me know where to go. 
[gnome_logs_search_gsconnect.log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5078739/gnome_logs_search_gsconnect.log)

**System Details (please complete the following information):**

 - **GSConnect version:** 40
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Ubuntu 20.04

**GSConnect environment (if applicable):**
Not applicable

 - **Paired Device(s):** Galaxy S10 Plus (shouldn't matter)
 - **KDE Connect app version:** not applicable
 - **Plugin(s):** not applicable

**Additional Notes:**
N/A

**Comment by enigma0160** [comment] 2020-08-15 16:33
v40 fails to install/update on Fedora 32 as well.

Details:

OS: Fedora 32 Workstation
GNOME Version: 3.36.3 Wayland

**Comment by andyholmes** [comment] 2020-08-15 17:18
Thankks for reporting but...

Duplicate of #817 :wink:

**Closed by andyholmes** 2020-08-15 17:18 UTC
