### ISSUE TITLE
No conversations Ubuntu 18.10

### ISSUE THREAD

**Issue by r3dlobst3r** [andyholmes/gnome-shell-extension-gsconnect#460] opened 2019-02-07 14:23 UTC
**Describe the bug**
I am unable to view conversations. However, I am able to send messages through the messages applet. I am on Ubuntu 18.10 and all permissions have been accepted in KDE Connect Android app.

Log:
SConnect Version: 20
GSConnect Install: user
GJS: 15401
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-02-07 05:40:11 PST, end at Thu 2019-02-07 06:05:15 PST. --
Feb 07 06:05:12 dbus-daemon[1365]: [session uid=1000 pid=1365] Activating service name='org.gnome.gedit' requested by ':1.93' (uid=1000 pid=9010 comm="gjs /home/shumana/.local/share/gnome-shell/extensi" label="unconfined")
Feb 07 06:05:12 dbus-daemon[1365]: [session uid=1000 pid=1365] Successfully activated service 'org.gnome.gedit'
Feb 07 06:05:12 org.gnome.Shell.desktop[1536]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x36000f8 (gsconnect.)
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Feb 07 06:05:15 gjs[9010]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Expected behavior**
I would like to see current conversations.

**Screenshots**
![screenshot from 2019-02-07 06-09-35](https://user-images.githubusercontent.com/33791877/52416707-13b05280-2a9f-11e9-82dd-841dc7fd762d.png)

**System Details (please complete the following information):**
 - GSConnect version: 20
   - Installed from: zip release
 - GNOME/Shell version: GNOME Shell 3.30.1
 - Distro/Release: Ubuntu 18.10

**GSConnect environment (if applicable):**
 - Paired Device(s): Galaxy S8
 - KDE Connect app version: 1.10.1

**Comment by ferdnyc** [comment] 2019-02-07 21:07
@r3dlobst3r 

This is a known issue, unfortunately, with KDE Connect on the Samsung Galaxy S8 (and several other devices), see our #320 and upstream https://bugs.kde.org/show_bug.cgi?id=401677

Closing as duplicate of #320.

**Closed by ferdnyc** 2019-02-07 21:07 UTC
