### ISSUE TITLE
Gnome-shell hangs for a few seconds before showing gsconnect notifications

### ISSUE THREAD

**Issue by nicber** [andyholmes/gnome-shell-extension-gsconnect#199] opened 2018-09-22 15:54 UTC
It seems that gsconnect is slow to connect to the phone and that freezes gnome-shell until it is done.

Here is a log:

```
Sep 22 12:40:59 localhost.localdomain gjs[2383]: JS LOG: Daemon: Updating device
Sep 22 12:40:59 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:40:59 localhost.localdomain gjs[2383]: JS LOG: Connecting to '2c127ad458867113'
Sep 22 12:40:59 localhost.localdomain gjs[2383]: JS LOG: Authenticating '2c127ad458867113'
Sep 22 12:40:59 localhost.localdomain gjs[2383]: JS LOG: Connected to 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received unsupported packet type: {"id":1537630859592,"type":"kdeconnect.runcommand.request","body":{"requestComman>
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Connecting to '2c127ad458867113'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:00 localhost.localdomain gjs[2383]: JS LOG: Connecting to '2c127ad458867113'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS LOG: Connecting to '2c127ad458867113'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS LOG: Received from 'Samsung J7 Prime de Nico'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS LOG: Connecting to '2c127ad458867113'
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS ERROR: Gio.TlsError: Peer failed to perform TLS handshake
                                                 Transfer<._read/<@/home/nicolas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol.js:610:>
                                                 @/home/nicolas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:962:2
Sep 22 12:41:09 localhost.localdomain gjs[2383]: JS ERROR: Gio.TlsError: Peer failed to perform TLS handshake
                                                 Transfer<._read/<@/home/nicolas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol.js:610:>
                                                 @/home/nicolas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:962:2
```

**Comment by andyholmes** [comment] 2018-09-24 14:59
I think this might be a duplicate of #181, but I'm not sure what would cause gnome-shell to hang. Unless maybe multiple notifications were being received at once. If you turn on debug mode in the About page is there any more information?

**Comment by nicber** [comment] 2018-09-24 22:55
> Unless maybe multiple notifications were being received at once.
This is exactly what's going on. After the shell unfreezes a bunch of notifications appear one after the other.

**Comment by andyholmes** [comment] 2018-09-26 04:43
duplicate of #181 

Marking this as a duplicate and closing since I believe it's the same issue as #181

**Closed** 2018-09-26 04:44 UTC
