### ISSUE TITLE
Contact names with non-ASCII characters cause problems

### ISSUE THREAD

**Issue by thedrint** [andyholmes/gnome-shell-extension-gsconnect#562] opened 2019-06-19 15:03 UTC
**Describe the bug**

If contact name on phone has non-latin symbols (russian for example), after sync with GS this contact shows cutted to 12 symbols in GS message app.

**Steps To Reproduce:**

0. Have a contact on your phone with non-latin characters in name and length more than 12 symbols (including spaces). "Василий Васильевич" (18 symbols) for example. Already have a sms conversation with this contact.
1. Connect phone to gsconnect and allow to syncronize sms and contacts from your phone
2. Open gs message app and find sms conversation.
3. See that name of contact cutted to 12 symbols. In my example it would be "Василий Васи" 
4. See that other contacts, with latin letters only, showing good.

**Expected behavior**

Non-latin names must be imported to message app as is, without cutting.

**Screenshots**

![bug with nonlatin names](https://user-images.githubusercontent.com/5421805/59776429-74f0f980-92bb-11e9-960e-6941246f9451.png)

As you can see, name at top of screenshot, "Дядя Саша" has 9 symbols (with space) and displays correctly. But name at bottom of screenshot must be "Сергей Дмитриевич", but displays only "Сергей Дмитр".

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32.1
 - **Distro/Release:** Ubuntu 19.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Meizu M5Note
 - **KDE Connect app version:** latest from Google Play
 - **Plugin(s):** all plugins enabled

**Additional Notes:**

Maybe it is meizu bug? This manufacturer use modified version of android called FlymeOS and it has custom permissions settings.

**Comment by andyholmes** [comment] 2019-06-19 22:32
Could you try and test with this Zip ([Instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip))?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3308086/gsconnect%40andyholmes.github.io.zip)

You will have to clear the cache in Advanced preferences, then press the <kbd>+</kbd> button in the Messaging window to re-sync:
![Screenshot from 2019-06-19 15-31-13](https://user-images.githubusercontent.com/1265208/59805842-49641400-92a7-11e9-9755-a4858df4b1ac.png)

**Comment by igorbarkowsky** [comment] 2019-06-20 12:32
@andyholmes of cource i can and i did as you tell. Deleted old extension, unziped new version from link you provide. Deleted cache for contacts and sms, deleted mobile device and sync again. After this i saw same bug.

![image](https://user-images.githubusercontent.com/5421805/59848962-1c7b3400-936f-11e9-9eb6-cfecb9c52e5b.png)
You can see that name of person with only latin symbols is ok, but second name with russian symbols cutted.

I tried to clear cache yet one time, sms message became empty. I clicked on plus to create new conversation, contacts and sms are loaded - but with same bug.

But i did one more test. On the phone i change name of person to latin and non-latin letters. It became "Леонид Nikolaevich". I repeated deleting cache and reopened GS sms app. Now i have another picture:
![image](https://user-images.githubusercontent.com/5421805/59849338-06ba3e80-9370-11e9-8acc-f93d21e559fc.png)
You can see that only last letter "h" was cutted in tested contact.

Hope this information would helps you.

**Comment by andyholmes** [comment] 2019-06-22 03:36
@igorbarkowsky the changed Zip seems to work for me:

![Screenshot from 2019-06-21 20-30-03](https://user-images.githubusercontent.com/1265208/59958964-8aa12300-9463-11e9-94ad-ae81972710dd.png)

It might actually be a problem with Android in this case, but it's hard to tell since I can't reproduce this myself.

**Comment by igorbarkowsky** [comment] 2019-06-22 13:35
@andyholmes highly likely it is flymeos bug. I gmail you gsconnect.log that i had. It logged moment when i deleted cache and resynced. `kdeconnect.contacts.response_vcards` included. Hope it can helps.

**Comment by andyholmes** [comment] 2019-06-22 23:30
Thanks for the log, I believe I've fixed the problem now. Here's an updated Zip:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3317344/gsconnect%40andyholmes.github.io.zip)

**Comment by igorbarkowsky** [comment] 2019-06-22 23:56
@andyholmes It fixed, but partially:) Now most of russian names not showed in left column (their phone numbers showed instead). Not all ("Сергей Дмитриевич" from first example showed correctly), but most of them ("Леонид Nikolayvich" and many others showed as phone number).

But, in contact list (which accessible via search bar when compose new sms) all looks fine with names. And in window title contact name showed correctly. It's enough for my usecases. Nice quickfix, thank you.

**Comment by monosoul** [comment] 2019-07-02 11:37
I'm having the same issue.

**Comment by andyholmes** [comment] 2019-07-02 18:54
Reopening since the fix isn't officially released. This should be fixed in master though.

**Comment by thedrint** [comment] 2019-07-06 02:41
@andyholmes, after one of reconnecting phone to laptop i noticed that all contact names showed correctly everywhere in GS Message App. Your fix really works at 100% (not immediatelly, but idk what a reason).

**Comment by andyholmes** [comment] 2019-08-19 04:18
Closing again since the problem seems to be solved and v25 will be coming (pretty soon-ish).

**Closed by andyholmes** 2019-08-19 04:18 UTC
Labels: bug, fixed in master
