### ISSUE TITLE
Broken extension after update

### ISSUE THREAD

**Issue by fakhamatia** [andyholmes/gnome-shell-extension-gsconnect#669] opened 2019-10-16 13:39 UTC
After last update exenshon not working anymore.

**Screenshots**

![Screenshot from 2019-10-16 17-07-11](https://user-images.githubusercontent.com/20030910/66924393-6b905780-f037-11e9-9735-b867dcd1042d.png)

**System Details**

 - **GSConnect version:** [27]
   - **Installed from:** [GNOME Extensions Website]
 - **GNOME/Shell version:** [3.28.4]
 - **Distro/Release:** [Ubuntu 18.04]

```
GLib.FileError: Failed to create file “/home/titan/.local/share/icons/hicolor/scalable/apps/org.gnome.Shell.Extensions.GSConnect.svg.QEKZ9Z”: No such file or directory

Stack trace:
  gsconnect.installService@/home/titan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:213:9
  init@/home/titan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:20:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  ```

**Comment by patricklibert** [comment] 2019-10-22 16:20
Ubuntu 18.04
GSconnect 27 completely broke the application.
No devices found...

**Comment by andyholmes** [comment] 2019-10-22 18:27
Duplicate of #653

**Closed by andyholmes** 2019-10-22 18:27 UTC

**Comment by patricklibert** [comment] 2019-10-23 20:02
This is not a duplicate of bug 653...
No GSconnect Desktop is found on KDEConnect and GSconnect can't find the phone.
No devices found.
They are on the same network...
The only way to make this work is by putting the IP address of the phone in GSconnect..
The other way putting the IP in KDEconnect doesn't work.
I have to do this every day again.
Happened from GSConnect 27

**Comment by andyholmes** [comment] 2019-10-23 21:58
The bug was opened with the same screenshot, reporting the same bug, for the same distribution.

The problems you are reporting are different from the original bug, but still relate to Ubuntu 18.04 LTS. As described in #653 we're probably just going to drop support for older versions of GNOME unless a volunteer offers to maintain it.

**Comment by fakhamatia** [comment] 2019-11-05 12:48
@andyholmes I still have this problem.
I remove the extension and install again from extensions.gnome.org but not work.
I have exactly [this](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/669#issue-507859354) error

**Comment by ferdnyc** [comment] 2019-11-05 14:42
@fakhamatia Since this is a closed report for a fixed problem, it's likely you have a _different_ issue. (Even though it may look the same, because a lot of things can cause the extension manager to show a generic "Error" message that provides no information whatsoever about the problem in question.)

The best thing would be to file a new report, using the [bug report template](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/new?assignees=&labels=&template=bug_report.md&title=), and provide **all** of the requested information about _your_ case, including the requested version information for your distro and GNOME installation.

Since the extension isn't starting, you won't be able to use the Generate Support Log feature, but it would be helpful if you could check your user journal for any error messages and provide them in the report. Use this command to see messages related to gsconnect:
```sh 
journalctl --user -n 10000 --grep gsconnect -e
```
The most recent ones will be at the bottom.

**Comment by fakhamatia** [comment] 2019-11-05 17:23
@andyholmes  I wanted to create a new report bug, But `journalctl --user -n 10000 --grep gsconnect -e` show nothing.
Do you want to download manualy and copy files? or another way to install?

**Comment by andyholmes** [comment] 2019-11-05 19:20
At this point your best bet is to install one of the older versions from https://extensions.gnome.org/extension/1319/gsconnect/. You should be able to use the dropdown menu to select an older version:

![Screenshot from 2019-11-05 11-17-53](https://user-images.githubusercontent.com/1265208/68238403-f5d83580-ffbd-11e9-8f72-e49995188dc4.png)

Unfortunately I just don't have the time or resources to support Ubuntu's LTS releases anymore. Canonical makes a commitment to backport security and bug fixes for 18.04 LTS, but GSConnect is not one the programs they do that for.

**Comment by fakhamatia** [comment] 2019-11-05 20:11
@andyholmes 
Version 28 and 27 not work. I download 26 from [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v26) and manualy copy and manualy install and work for now.

**Comment by andyholmes** [comment] 2019-11-06 21:32
Okay, I will mark v26 as available on the extensions website, thanks for reporting back.
