### ISSUE TITLE
very high ram use in gjs process under gnome shell 3.28.4

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#666] opened 2019-10-11 05:56 UTC
gsconnect 26
ubuntu 18.04.3
gnome shell 3.28.4

Recently, maybe about one week ago - I can't really relate it to any event I can recall - whenever I have the gsconnect extension turned on, gnome-shell uses a large amount of RAM, and after just an hour or so will be up to using about 10GB of RAM, eventually causing the desktop to frequently freeze up.  I do not have this problem when the gsconnect extension is turned off.  

How do I diagnose and get this problem fixed.

**Comment by A-UNDERSCORE-D** [comment] 2019-10-12 07:29
Confirming this, Ubuntu  18.04, gnome shell 3.28.4

**Comment by A-UNDERSCORE-D** [comment] 2019-10-12 07:36
As a workaround, SIGTERM-ing gjs will deal with the memory gobbling quite well for a few hours, and it autorestarts itself

**Comment by dln949** [comment] 2019-10-12 15:24
Sorry.....  I'm a layman.  

1)  What is gjs, what does it do?  
2)  What does SIGTERM mean?  
3)  HOW do I SIGTERM something?  
4)  What are the effects, including drawbacks, of SIGTERM gjs?  
5)  How does this workaround relate to gsconnect?  What is the underlying problem with gsconnect that is work around is working around?

**Comment by A-UNDERSCORE-D** [comment] 2019-10-12 15:29
1. gjs is the javascript engine that plugins run on
1. SIGTERM is a [unix signal](https://en.wikipedia.org/wiki/Signal_(IPC)) often used to stop software "politely"
1. To do it, rclick on the process in the task manager and select end task
1. I have no idea--It appears to work.
1. It smacks the process gsconnect runs under, thereby freeing its ram. gsconnect has a memory leak, No idea where, no idea why/

**Comment by dln949** [comment] 2019-10-12 15:35
Hey, thanks!  

I might try this - although I have never checked into the situation with gjs.  

One drawback I foresee:  This may be a real hassle.  For me, while running gsconnect, the consumption of huge amounts of RAM grows QUICKLY.  So, I think I'd have to do this frequently.  For now, I have turned off the gsconnect extension, turning it on only when I need to use it.

**Comment by dln949** [comment] 2019-10-12 19:56
After spending more time looking around on my system, it turns out I do not have a process called "gjs" running, so that is not the problem.  The problem is a process called gnome-shell, that is the process that grows in RAM whenever I have gsconnect running.

**Comment by A-UNDERSCORE-D** [comment] 2019-10-12 19:59
Weird. Well dont just terminate that, use alt+f2, type in r, and hit enter. Should restart it without killing your applications. There SHOULD be a gjs process though, that is weird. see:

![Screenshot from 2019-10-12 21-58-36](https://user-images.githubusercontent.com/21071450/66707074-9038b680-ed3b-11e9-89fc-6c6e04b668f9.png)

**Comment by andyholmes** [comment] 2019-10-13 02:11
Generally it's a bit harder to debug GSConnect this way now, but here's what you'll likely have to do:

1. First permanently enable debug logging so you can catch errors at startup and shutdown:
    `dconf write /org/gnome/shell/extensions/gsconnect/debug true`

2. Open `journalctl` in a new terminal to watch for errors:
    `journalctl -f -o cat /usr/bin/gjs`

3. Touch the service, which should trick into restarting:
    `touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js`

If you restart GSConnect this way, you should be able to see additional warning and errors. There will be some expected warnings, but also probably some Promise/GSource tracebacks; this has usually ended up being the source of memory problems.

You'll have to set `debug` to `false` when you're done to avoid filling up your logs.

**Comment by dln949** [comment] 2019-10-13 02:58
I followed your procedure, and let the journalctl run for quite a while.  I have a file of 78 KB.  I don't know how to find the "tracebacks" you spoke about.  I searched for "Promise", "GSource", and "tracebacks", but none of them were in the output.  

Is there a way I can share the file with you directly?  I don't feel comfortable attaching it here.

**Comment by andyholmes** [comment] 2019-10-13 04:16
Sorry, I should have been clearer. The first place you want to look is at the "end" of the log when GSConnect exits.

So once you have the log and GSConnect running and you're sure it's leaked memory, run the `touch` command above which will cause the service to shutdown (and then restart). It's here that messages about unresolved Promises or orphaned GSources would be printed.

**Comment by dln949** [comment] 2019-10-13 05:51
Sorry.....  It isn't working out the way you described.  

I start gsconnect.  When I start gsconnect and it is running, then I see the gnome-shell RAM increasing a lot as time goes by.  

I turn gsconnect debug on.  

I start the journalctl command. 

I run the gsconnect restart (touch) command.  

Restarting gsconnect adds lots of stuff to journalctl terminal window.  

I do a search in the journalctl window for "Promises" and for "GSources".  No such results.  

(gnome-shell RAM is still increasing.)  

I repeat the last three steps.  Still do not find those two words.

**Comment by ferdnyc** [comment] 2019-10-13 07:32
@dln949 One possibility is that the problem is _not_ GSConnect.

Oh, I'm not saying that starting GSConnect isn't causing the `gnome-shell` process' memory usage to increase, I'm sure it is. But it could be a fault in another extension, or some internal Gnome Shell component — something GSConnect is triggering when it's loaded.

(_Especially_ if you see `gnome-shell` increasing while `gjs` isn't running — the `gjs` process is where all of GSConnect's code executes, without it GSConnect is effectively disabled.)

If you're still running Gnome Shell 3.28, it might be worth going to the [GSConnect e.g.o page](https://extensions.gnome.org/extension/1319/gsconnect/?c=52762) and manually downloading `v24`. See if downgrading to that version fixes the problem. If it does, then perhaps it's an issue with the newer code running under older Shell releases. You may just need to stick with the older versions until you're running a newer release of the platform.

**Comment by A-UNDERSCORE-D** [comment] 2019-10-13 09:34
@ferdnyc Ive got the same issue but on gjs. Im going to enable debug mode now and let you know where it goes

**Comment by A-UNDERSCORE-D** [comment] 2019-10-13 17:06
okay update time!
```
../../../../gobject/gsignal.c:2641: instance '0x55a2ebd70430' has no handler with id '232'
../../../../gobject/gsignal.c:2641: instance '0x55a2ebd707a0' has no handler with id '235'
../../../../gobject/gsignal.c:2641: instance '0x55a2ec27cdc0' has no handler with id '59'
../../../../gobject/gsignal.c:2641: instance '0x55a2ec27cdc0' has no handler with id '61'
../../../../gobject/gsignal.c:2641: instance '0x55a2ec27cdc0' has no handler with id '57'
../../../../gobject/gsignal.c:2641: instance '0x55a2ec2cfb50' has no handler with id '247'
../../../../gobject/gsignal.c:2641: instance '0x55a2ec2d9a60' has no handler with id '251'
[/service/device.js:_loadPlugin:900]: Viper: "loading 'battery' plugin"
```

This is the relevant log for the `touch` command, before then the gjs was above my highest memory user (a jetbrains ide--using ~1.5G), and after it was ~32.3M

So that "proves" that something about gsconnect is causing gjs to go a-nomming on memory. Unsure exactly what.

**Comment by andyholmes** [comment] 2019-10-14 00:37
Did this start happening with v25/26? This is starting to seem like something in GJS that was fixed after ~1.52 or whichever version of GJS runs on 3.28.

**Comment by dln949** [comment] 2019-10-14 04:04
@ferdnyc suggested that I try going back to an earlier version of gsconnect.  So, I unstalled version 26, and installed version 25, and have been running version 25 all day.  

With version 26 I had the problems that I described above in the original post.  (In addition, I had forgotten to mention:  Whenever I had version 26 running, if I tried to restart gnome-shell, my computer would freeze during the restart process, and I'd always have to manually reboot the computer.)  

With version 25, while the gnome-shell ram would still grow some, it definitely grows MUCH more slowly and FAR less than what I saw with version 26.  Also, while running version 25, gnome-shell restart has always worked for me.  

I am not a computer expert, I don't want to lead anyone astray, so I am not laying out any conclusions about what exactly the problem is, what other things may be interacting, etc.  I don't know those kinds of things.  I am simply reporting what I am seeing in case it helps.

**Comment by ferdnyc** [comment] 2019-10-15 14:56
@dln949 That actually complicates things more than clears them up, I'm afraid.

The reason I'd suggested `v24`, specifically, as the version to downgrade to is, `v26` was a quick bugfix release that came out on the heels of `v25`, which had one issue that needed quick correction. This is literally the _entire_ set of differences between `v25` and `v26`:

```diff
git diff v25..v26
diff --git a/meson.build b/meson.build
index 95943261..8cef3264 100644
--- a/meson.build
+++ b/meson.build
@@ -1,4 +1,4 @@
-project('gsconnect', 'c', version: '25', meson_version: '>= 0.49.0')
+project('gsconnect', 'c', version: '26', meson_version: '>= 0.49.0')
 
 gnome = import('gnome')
 i18n = import('i18n')
diff --git a/src/service/protocol/__init__.js b/src/service/protocol/__init__.js
index 8aaf6ac6..03333c4a 100644
--- a/src/service/protocol/__init__.js
+++ b/src/service/protocol/__init__.js
@@ -83,7 +83,7 @@ Object.defineProperties(Gio.TlsCertificate.prototype, {
                 proc.init(null);
 
                 let stdout = proc.communicate_utf8(this.certificate_pem, null)[1];
-                this.__common_name = /[a-zA-Z0-9-]{36}/.exec(stdout)[0];
+                this.__common_name = /(?:cn|CN)\ ?=\ ?([^,]*)/.exec(stdout)[1];
 
                 proc.wait_check(null);
             }

```

So, if downgrading to v25 made any appreciable difference for you, then something **really** strange is going on.

**Comment by dln949** [comment] 2019-10-17 21:04
I am so sorry.....  I did not realize something I was doing inadvertantly.  

I have a few other extensions installed.  In my efforts to isolate the issue, I would turn off all the other extensions, going through them one at a time.  That is how I landed on gsconnect being the problem.  Today, though.....  I realized that whenever I turned on or off gsconnect, I was not being careful enough, and one other extension was always also on or off at the same time.  Stupid me.  

Now as I do that more carefully, I have narrowed my problem down to a different extension.  When I have that extension off, and gsconnect on, I do not have the RAM problem.  

I'm sorry for the misleading information.  

Should I close this issue?  While my problem appears to be a non-problem, other people have jumped onto this issue with a problem they are having, and I can't say that my solution is also their solution.

**Comment by ferdnyc** [comment] 2019-10-17 21:50
@dln949 Hey, it happens! Glad to hear you worked out the source of the issue (but sorry to hear some other extension is causing you grief).

Yeah... I guess we'll leave this open pending an update on @A-UNDERSCORE-D 's `gjs` memory-consumption troubles, thanks. But feel free to Unsubscribe if you don't want to be pestered with any additional notifications.

**Comment by andyholmes** [comment] 2019-10-22 20:19
Closing, as it's likely this is related to #653 and #676 where I've posted a message:

> There seem to be quite a few problems happening with GNOME 3.28, and sadly it may just be time to drop support for older versions. I don't have the hard drive space to keep VMs around for all these versions or the time to properly support them, and we've been holding back on newer language features and libraries going back over two years now.
> 
> So basically, unless someone volunteers to maintain support for older versions of GNOME, I think we'll drop support for them in v28.

**Closed by andyholmes** 2019-10-22 20:19 UTC
