### ISSUE TITLE
Not load after clean zip install

### ISSUE THREAD

**Issue by NedasPekorius** [andyholmes/gnome-shell-extension-gsconnect#247] opened 2018-10-19 07:22 UTC

**Comment by andyholmes** [comment] 2018-10-19 10:29
Sorry, I need more information to be able to help.

**Comment by andyholmes** [comment] 2018-11-06 23:49
I'm going to close this, since it's been open without information for sometime and is likely a duplicate of another bug.

**Closed by andyholmes** 2018-11-06 23:49 UTC
Labels: needs info
