### ISSUE TITLE
Some SMS send attempts do nothing (insert-address-token contacts?)

### ISSUE THREAD

**Issue by allibell** [andyholmes/gnome-shell-extension-gsconnect#710] opened 2019-11-14 01:36 UTC
First of all, thanks for such an amazing plugin!!!  This is lifechanging!

Now, on to the **Description**:

Sometimes trying to send an SMS from `Messaging` does nothing except turn the text bar red.  It seems `send()` in `service/protocol/core.js` isn't even called.

This may be a contact/phone number issue - it just happens with specific contacts that seem to show up wrong.  But I don't think it's the number-formatting issue in #380, since the messed-up contacts' saved numbers aren't formatted differently from other contacts.  These particular contacts appear with the name `insert-address-token` (instead of their contact names) in the selected conversation view, even though the contact names appear correctly in the left-hand conversation list.  
 
**Steps To Reproduce:**

1. Get a "faulty" contact?  I'm unsure what causes this.  Their numbers are saved in the same formats (including country codes, etc) as other contacts which work properly. 
2. Select that contact's SMS conversation in the `Messaging` applet
3. Type text, hit ENTER
4. The text bar turns red and nothing else happens.  Also, the conversation appears to be a group conversation even though it isn't.

**Expected behavior**

The SMS should send, and the text bar shouldn't change.  The contact's conversation shouldn't show up like a group conversation.

**Screenshots**
![gsconnect-insert-address-token](https://user-images.githubusercontent.com/25647843/68818156-4e07db00-0641-11ea-964b-5ab9756c24f6.jpeg)

**Support Log**

The following log was created before capturing the screenshot above.  I first sent a successful text, `text1`, to my own number; no issues there.  Then I attempted to send a text `test2` to this contact, and got the error.  Note:
1. Nothing is logged about my attempted text `test2` - it doesn't seem to call `send()`
2. The message about the ampersand deals with an entirely different contact, so I don't think that's relevant.

```
GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-02-10 18:28:31 MST, end at Wed 2019-11-13 17:29:56 MST. --
Nov 13 17:29:19 gjs[10110]: GtkDialog mapped without a transient parent. This is discouraged.
Nov 13 17:29:40 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/core.js:send:321]: LG G6: {
                                                              "id": 1573691380624,
                                                              "type": "kdeconnect.sms.request",
                                                              "body": {
                                                                "sendSms": true,
                                                                "phoneNumber": "************65",
                                                                "messageBody": "test1"
                                                              }
                                                            }
Nov 13 17:29:42 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/core.js:receive/<:275]: LG G6: {
                                                              "id": 1573691382050,
                                                              "type": "kdeconnect.sms.messages",
                                                              "body": {
                                                                "messages": [
                                                                  {
                                                                    "addresses": [
                                                                      {
                                                                        "address": "********65"
                                                                      }
                                                                    ],
                                                                    "body": "test1",
                                                                    "date": 1573691381428,
                                                                    "type": 2,
                                                                    "read": 1,
                                                                    "thread_id": 496,
                                                                    "_id": 26988,
                                                                    "sub_id": 1,
                                                                    "event": 1
                                                                  }
                                                                ],
                                                                "version": 2
                                                              }
                                                            }
Nov 13 17:29:42 gjs[6913]: Failed to set text 'Ben (S&D)' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
Nov 13 17:29:45 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/core.js:receive/<:275]: LG G6: {
                                                              "id": 1573691385591,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "payloadHash": "99c5796cc1255a31916509f2265da13a",
                                                                "id": "0|com.textra|2|null|10243",
                                                                "isClearable": true,
                                                                "appName": "Textra",
                                                                "time": "1573691385552",
                                                                "ticker": "self: test1",
                                                                "title": "self",
                                                                "text": "test1"
                                                              },
                                                              "payloadSize": 3495,
                                                              "payloadTransferInfo": {
                                                                "port": 1739
                                                              }
                                                            }
Nov 13 17:29:45 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/lan.js:_onIdentity:313]: {
                                                              "id": 1573691385725,
                                                              "type": "kdeconnect.identity",
                                                              "body": {
                                                                "deviceId": "74abeabf51bc4adb",
                                                                "deviceName": "LG G6",
                                                                "protocolVersion": 7,
                                                                "deviceType": "phone",
                                                                "incomingCapabilities": [
                                                                  "kdeconnect.telephony.request_mute",
                                                                  "kdeconnect.notification",
                                                                  "kdeconnect.ping",
                                                                  "kdeconnect.notification.reply",
                                                                  "kdeconnect.notification.action",
                                                                  "kdeconnect.share.request",
                                                                  "kdeconnect.clipboard.connect",
                                                                  "kdeconnect.runcommand",
                                                                  "kdeconnect.contacts.request_all_uids_timestamps",
                                                                  "kdeconnect.sms.request_conversations",
                                                                  "kdeconnect.telephony.request",
                                                                  "kdeconnect.mpris",
                                                                  "kdeconnect.sms.request_conversation",
                                                                  "kdeconnect.findmyphone.request",
                                                                  "kdeconnect.systemvolume",
                                                                  "kdeconnect.mousepad.keyboardstate",
                                                                  "kdeconnect.sftp.request",
                                                                  "kdeconnect.share.request.update",
                                                                  "kdeconnect.notification.request",
                                                                  "kdeconnect.mousepad.request",
                                                                  "kdeconnect.photo.request",
                                                                  "kdeconnect.sms.request",
                                                                  "kdeconnect.contacts.request_vcards_by_uid",
                                                                  "kdeconnect.mpris.request",
                                                                  "kdeconnect.battery.request",
                                                                  "kdeconnect.clipboard"
                                                                ],
                                                                "outgoingCapabilities": [
                                                                  "kdeconnect.sms.messages",
                                                                  "kdeconnect.telephony",
                                                                  "kdeconnect.mpris",
                                                                  "kdeconnect.notification",
                                                                  "kdeconnect.contacts.response_uids_timestamps",
                                                                  "kdeconnect.findmyphone.request",
                                                                  "kdeconnect.ping",
                                                                  "kdeconnect.mousepad.keyboardstate",
                                                                  "kdeconnect.share.request",
                                                                  "kdeconnect.contacts.response_vcards",
                                                                  "kdeconnect.notification.request",
                                                                  "kdeconnect.mousepad.echo",
                                                                  "kdeconnect.clipboard.connect",
                                                                  "kdeconnect.mousepad.request",
                                                                  "kdeconnect.presenter",
                                                                  "kdeconnect.sftp",
                                                                  "kdeconnect.photo",
                                                                  "kdeconnect.runcommand.request",
                                                                  "kdeconnect.mpris.request",
                                                                  "kdeconnect.systemvolume.request",
                                                                  "kdeconnect.battery",
                                                                  "kdeconnect.clipboard"
                                                                ],
                                                                "tcpPort": 1716,
                                                                "tcpHost": "192.168.1.142"
                                                              }
                                                            }
Nov 13 17:29:52 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/core.js:send:321]: LG G6: {
                                                              "id": 1573691392860,
                                                              "type": "kdeconnect.notification",
                                                              "body": {
                                                                "appName": "Google Chrome",
                                                                "id": "fdo|null|0",
                                                                "title": "self",
                                                                "text": "SMS at 5:29 PM\n\ntest1",
                                                                "ticker": "self: SMS at 5:29 PM\n\ntest1",
                                                                "isClearable": false
                                                              },
                                                              "payloadSize": 16729,
                                                              "payloadTransferInfo": {
                                                                "port": 1740
                                                              }
                                                            }
Nov 13 17:29:52 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/lan.js:close:750]: "lan://192.168.1.142:1740 (597a979c-e178-473b-94ed-82b42f625998)"
Nov 13 17:29:55 org.gnome.Shell.Extensions.GSConnect[6913]: [/service/protocol/core.js:receive/<:275]: LG G6: {
                                                              "id": 1573691386425,
                                                              "type": "kdeconnect.sms.messages",
                                                              "body": {
                                                                "messages": [
                                                                  {
                                                                    "addresses": [
                                                                      {
                                                                        "address": "************65"
                                                                      }
                                                                    ],
                                                                    "body": "test1",
                                                                    "date": 1573691385144,
                                                                    "type": 1,
                                                                    "read": 0,
                                                                    "thread_id": 496,
                                                                    "_id": 26989,
                                                                    "sub_id": 1,
                                                                    "event": 1
                                                                  }
                                                                ],
                                                                "version": 2
                                                              }
                                                            }
Nov 13 17:29:56 gjs[6913]: Failed to set text 'Ben (S&D)' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;

```

The following log snippet is from starting up `Messaging` after clearing the SMS cache, just to show a couple `insert-address-token` contacts in the logs.  It looks like they're treated kind of like group conversations.

```
{
"addresses": [
    {
      "address": "insert-address-token"
    },
    {
      "address": "(***) ***-****"
    }
],
"body": "redacted",
"date": 1556068756000,
"type": 2,
"read": 1,
"thread_id": 361,
"_id": 10123,
"sub_id": -1,
"event": 3
},
{
"addresses": [
    {
      "address": "insert-address-token"
    },
    {
      "address": "(***) ***-****"
    }
],
"body": "redacted",
"date": 1573077548000,
"type": 2,
"read": 1,
"thread_id": 4,
"_id": 10994,
"sub_id": -1,
"event": 3
},

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28 
 - **Installed from:** Ubuntu Software 
 - **GNOME version:** 3.28.4
 - **Distro/Release:** Ubuntu 18.04
 - **Paired Device(s):** LG G6
 - **Texting app:** Textra
 - **KDE Connect app version:** 1.13.2
 - **Plugin(s):** Messaging

**Comment by andyholmes** [comment] 2019-11-14 02:31
Hi, thanks for the thorough bug report.

I think you are correct that GSConnect is being confused into thinking this is a group message. Since we (GSConnect & KDE Connect) don't support sending or responding to group MMS, GSConnect currently just sets the text entry to "error" which is why it goes red. It's not really great feedback for the user, but it was intended to be a temporary behaviour.

Some quick googling seems to indicate that `insert-address-token` is a string that Android inserts into the SMS/MMS database in some situations. It might mean that the address is usually to be found elsewhere in the database, but I'm not sure yet.

Probably we can avoid this just by stripping addresses out with `insert-address-token`, but that might blow up in our face later.

For now, I'm CC'ing @sredman on this issue, who is the primary SMS developer in the KDE Connect team. He might have a bit more experience with this issue.

**Comment by sredman** [comment] 2019-11-14 02:58
I have never seen this before.

My quick Googling suggests that `insert-address-token` happens when the phone is trying to signal to the network to please replace the sender's phone number here.

Goodness knows how old this document is, but it has a nice explanation which fits what I like to hear: http://www.hellkvist.org/software/mmsdiary/README.txt (search for "insert-address-token")

Windows Phone can also do the same thing, which is to say that it's not an Android-specific-ism: https://docs.microsoft.com/en-us/windows-hardware/customize/mobile/mcsf/use-insert-address-token-or-local-raw-address (Much as I love to blame Android for all my problems)

I could suggest a workaround for KDE Connect which would give us more information but I don't know the details of how GSConnect works well enough to "translate" it. In KDE Connect, I define the details of a conversation based on the most-recent message in the conversation. If my understanding of this weird value is correct, it should not appear in case of an incoming message. It should only be present in case of an outgoing *MMS* message. This means that if you go to the phone and send a proper SMS message or wait until you receive something, then refresh the KDE Connect SMS app, it would be un-stuck until the next time the conversation is opened when the last message contained "insert-address-token".

@andyholmes, @allibell Can you think of a way to do similar validation with GSConnect? Basically what I want to see is an outgoing message as well as an incoming message. That would be one message with type = 1 and one message with type = 2. GSConnect stores a lot more information on the user PC so it will probably be much easier for you than my crazy workaround above :)

If it is the case that the wacky field only shows up in place of the user's phone number in outgoing messages, then I can relatively easily just add that to the list of "addresses" to strip from MMS messages. (Where that list is currently all of the user's phone numbers, assuming the app was able to retrieve them)

**Comment by andyholmes** [comment] 2019-11-14 03:38
> Can you think of a way to do similar validation with GSConnect? Basically what I want to see is an outgoing message as well as an incoming message. That would be one message with type = 1 and one message with type = 2. GSConnect stores a lot more information on the user PC so it will probably be much easier for you than my crazy workaround above :)

Since we're using JS, we basically store SMS history exactly how we receive it; we just dump it into a file as JSON. I know that sometimes we get duplicate or repeat `messages` packets, but regardless of that, we update our current cache basically by overlaying the new message on the old one.

The purpose of that is to update the `read` field, however it occurs to me that what might be happening is that we get an initial "outgoing" packet (aka confirmation the phone sent the message), and then later the same message (eg. message with the same id) that has the `insert-address-token` updated with the real address, hence ending up with a message that appears to have two contacts. I guess that would depend on whether an updated message triggers the SMS content manager though.

Like you say, @sredman, we'd probably have to see the two-way communication to be sure of that, but if it's the case we can probably safely strip `insert-address-token` entries on both sides, especially if both implementations are sorting by `thread_id`.

**Comment by andyholmes** [comment] 2019-11-14 04:14
@allibell I see you're using Ubuntu 18.04 LTS. Unfortunately we're not going to be doing any more releases for older GNOME Shell versions, but since you're probably happy to test the fix, here is a Zip that should fix your problem:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3844562/gsconnect%40andyholmes.github.io.zip)

You can install it using the [instructions in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip), and it's set up to auto-correct the messages in the cache when the extension loads. This basically just trawls through all messages and removes the problem addresses, so let me know if this fixes the problem.

**Comment by allibell** [comment] 2019-11-15 03:27
Wow, thank you guys for being so helpful and responsive!

That fixed it!  `insert-address-token` "group chats" are now all individual contact conversations.  I seemed to need to clear my Contacts and SMS caches for this to work, but this is likely because the trawling just took longer than I spent waiting.  (I have a lot of backed up SMSes, it takes a few minutes to reload).  Sorry I wasn't more scientific in my fixing approach, but I'm very happy to have it working.

I (a noob user) somehow totally missed that group MMSes aren't currently supported in my wiki reading. But that makes total sense of this issue now that `insert-address-token` "group chats" are fixed in your new code.  I'll be upgrading Ubuntu/GNOME now and seeing if there's a good way I can contribute toward possible group MMS support here.

Thanks so much!

**Comment by andyholmes** [comment] 2019-11-15 23:22
No problem, thanks for testing. I've included a patch in `master` that corrects incoming packets before handling them, although any users affected by this already will have to clear their cache. It's a bit much going through thousands of messages on each startup, as you noticed :)

**Comment by sredman** [comment] 2019-11-16 18:15
> I (a noob user) somehow totally missed that group MMSes aren't currently supported in my wiki reading. But that makes total sense of this issue now that `insert-address-token` "group chats" are fixed in your new code. I'll be upgrading Ubuntu/GNOME now and seeing if there's a good way I can contribute toward possible group MMS support here.

The first step to MMS support is the Android app needs a significant amount of work. Help with that would be welcome, feel free to read the KDE Connect wiki for information on how to work on that and how to get in touch with us https://community.kde.org/KDEConnect#Android

**Comment by andyholmes** [comment] 2019-11-17 01:13
^ I'd second what Simon said; the bulk of the work will be in the Android app. Working with Qt & Gtk will be the easy part, by comparison.

**Closed** 2019-11-20 04:49 UTC

**Comment by sredman** [comment] 2019-12-24 16:56
@allibell do you have a messaging app which supports RCS? (e.g., Google Messages?) In the conversation which was having this issue, if you long-press on a message, select the three dots menu in the top right, and select "View details", what does it say in the type field?

This is an issue I just discovered this morning which I believe should be somewhat straightforward to fix: https://bugs.kde.org/show_bug.cgi?id=415531

**Comment by andyholmes** [comment] 2019-12-24 22:00
@sredman See also #738.
