### ISSUE TITLE
emoticon Window to small

### ISSUE THREAD

**Issue by Mannshoch** [andyholmes/gnome-shell-extension-gsconnect#556] opened 2019-06-13 13:29 UTC
**Describe the bug**

emoticon Window is to small
![Bildschirmfoto von 2019-06-13 15-15-24](https://user-images.githubusercontent.com/7795891/59435792-b2064900-8dee-11e9-91e2-bc1372a9de03.png)

**Steps To Reproduce:**

1. Open Message Window (Whatsap in this case)
2. Rightclick into Textfield and select Emoticon
3. The Window appear like you see in [picture](https://user-images.githubusercontent.com/7795891/59435792-b2064900-8dee-11e9-91e2-bc1372a9de03.png)
4. Workaround: made Message Window wider before you open the emoticon window.
![Bildschirmfoto von 2019-06-13 15-23-02](https://user-images.githubusercontent.com/7795891/59436054-2f31be00-8def-11e9-9ae0-46a0424d7e5e.png)

**Expected behavior**

The Message Window appear normally

```

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 'apt search gnome-shell |grep gnome-shell/' 
disco-updates,now 3.32.1-1
 - **Distro/Release:** Ubuntu 19.04
 - **System:** Vmware

**Comment by andyholmes** [comment] 2019-06-14 00:36
Is this on Wayland? This seems like a duplicate of #211 which is caused by the upstream issue [#534 GtkPopover is constrained to parent window size on non-Wayland backends](https://gitlab.gnome.org/GNOME/gtk/issues/543)

**Comment by Mannshoch** [comment] 2019-06-14 09:58
I use X11

**Comment by andyholmes** [comment] 2019-06-14 22:49
In that case this is bug #534 in Gtk, so this can't be fixed in GSConnect.

**Closed by andyholmes** 2019-06-14 22:49 UTC
Labels: duplicate, upstream

**Comment by Mannshoch** [comment] 2019-06-15 05:54
Could you may Workaround it and made the Window a bit wider and higher?
