### ISSUE TITLE
android file system folder icon suddenly appears on PC desktop

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#504] opened 2019-03-26 04:26 UTC
Ubuntu 18.04.2, GNOME shell 3.28.3, KDE Connect 1.12.6, GSConnect 21.  

Until recently, whenever GSConnect on my PC would mount an android's filesystem, the folder icon for the mounted android filesystem would NOT appear on the PC desktop.  I always wondered why it did not, but never really questioned that.  (I have my settings on my desktop to show the icons for mounted filesystems.)  

In the past few days, I am now noticing that when I boot my PC, when I get to the desktop, the folder icons for the android filesystems appear on the PC's desktop.  

Having them appear on the PC's desktop is not, in and of itself, a problem.  However, I didn't know if this change is intentional, or if I had some problem in the past that has now been solved, or if the sudden appearance of these icon folders on the PC's desktop is indicative of a problem.  

So, I'm looking for advice by those who understand this better:  Should I regard this sudden and unexpected change as a sign of something that is going wrong?

**Comment by ferdnyc** [comment] 2019-03-27 04:21
Believe it or not, just an hour or two ago I saw my phone spontaneously automount on Linux _because I plugged the phone in to charge_. (Which may have caused the WiFi radio to turn on, if it was previously turned off to save power — so, the mounting may really have been a response to the phone connecting to the WiFi network and becoming visible.) Regardless, I didn't perform any actions that would've indicated that I wanted to mount the phone.

I only recently (last night) added a "Configured storage location" to the KDE Connect "Filesystem expose" plugin, so to some extent I guess it makes sense that it wouldn't have happened _before_ I did that. The question is, why would having a configured share path cause the remote device to automount?

I've observed similar behavior from Gvfs in the past, with _other_ configured remote locations. For instance, I have both an OwnCloud account and a Google Drive account set up in Gnome Online Accounts. Occasionally one of those two will suddenly decide to mount itself, for no apparent reason. Usually that happens on login, as @dln949 is seeing — but it doesn't happen _every_ login or even _most_ logins, nor is login the _only_ time it's happened. Long story short, I've never managed to figure out what's going on there. It's rare enough that I generally just unmount the remote server with a shrug.

My point is, Gvfs could have a poorly-understood (at least by me) bug that's involved here. But it's definitely behavior I've seen as well.

**Comment by andyholmes** [comment] 2019-03-27 20:58
> @dln949: In the past few days, I am now noticing that when I boot my PC, when I get to the desktop, the folder icons for the android filesystems appear on the PC's desktop.

Since about v21 we've dropped support for `sshfs` in favour of Gvfs. Even though we've had Gvfs support for awhile, it's likely only now that you've been using it. This just means that your phone's filesystem will be treated like like any other external drive, but nothing to worry about.

> @ferdnyc: My point is, Gvfs could have a poorly-understood (at least by me) bug that's involved here. But it's definitely behavior I've seen as well.

Well, Gvfs doesn't seem to be so much complicated as diverse, since it abstracts a bunch of different filesystems. For example, I'm not entirely clear on how/when a network filesystem (like ours) will be reconnected. I believe it functions somewhat like `sshfs`'s `-o reconnect` where it *actually* connects either on access (eg. file list requested/folder opened) or when a clear signal of disconnection happens (eg. some socket/connection closed).

Something that makes it a little more complicated is that the sftp server can arbitrarily be on ports 1739-1764. So an example of how this can be non-deterministic:

1. Phone connects
   * sftp mounts on port 1739 (in Gvfs)
   * notification with icon transfers over port 1740
2. Phone disconnects and reconnects
   * a notification with icon transfers over port 1739
   * sftp gets port 1740, but we haven't accessed the mount from (1), so Gvfs get no disconnection notice.
3. Phone disconnects, reconnects
   * sftp gets port 1739 again. User accesses sftp mount, still technically from (1)

In (3) Gvfs doesn't know or care about our kdeconnect connections, it's just a sftp server on the same address & port with the same credentials; so it sees it as the same filesystem. In fact, I believe Gvfs uses 2 connections for sftp: one to do initial authentication and the second for actual communication.

Something that's made this more obvious, is upstream has been working on packets being dropped during initial connection. Sftp has always been setup to automount, but as soon as a device connects a large packet exchange happens, often before the Android app has finished loading the plugins that handle those packets (yay thread-safety).

**Comment by ferdnyc** [comment] 2019-03-28 14:51
@andyholmes 
> Well, Gvfs doesn't seem to be so much complicated as diverse, since it abstracts a bunch of different filesystems. For example, I'm not entirely clear on how/when a network filesystem (like ours) will be reconnected. 

Nor am I, though not for lack of trying... I'm not entirely certain anymore that it _**is**_ completely clear. I know for certain that it's not clear in the _general_ case, because there is no "general" case — "auto"- or even normal-mount functionality doesn't appear to be one of the things Gvfs attempts to abstract, so each backend is slightly different. And `sftp:` appears to be a particularly quirky one since remote `sftp:` locations can't exist as Gio Volumes, effectively rendering them all temporary/transient.

<details>
<summary> <b>Expand for a bunch of unfocused rambling about Gvfs Volumes, Mounts, and backends</b> </summary>

#### Accounts configured in GOA create mountable Gio Volumes
For the remote storage accounts I have configured in GOA, an entry is always present in the second section of the Nautilus sidebar, mounted or not. (If the remote dir is unmounted, I can click that entry to "Mount & open" it, as the tooltip reads. If it _is_ mounted, an eject button allows me to unmount the remote share and close the connection.) Each of those entries is tied to a Volume in Gio, of type GProxyVolume (from GProxyVolumeMonitorGoa, specifically). When one is mounted, Gvfs connects using the specified protocol and a Mount instance of type GProxyShadowMount is created (again by/via GProxyVolumeMonitorGoa) as a child of that Volume.

But mounted `sftp:` locations aren't (seemingly can't be) associated with Volumes. When they're mounted, a Mount of type GDaemonMount is created at the root of the Gio hierarchy. Because that Mount has no parent, it only exists in Gio for the duration of the connection (aka until it's unmounted), after that it disappears without a trace. That's why remote SFTP servers only show up in that section section of Nautilus' sidebar when they're mounted. There's really no concept in Gvfs of an "unmounted SFTP location", because `sftp:`-scheme remote locations are only **defined** by a connected mount.

#### Ya but GSConnnect tho
With GSConnect-ed Android devices, It _seems_ like the **ideal** Gvfs implementation would be more akin to the way e.g. flash drives are handled. Whenever a USB storage device is attached to the system, any filesystems it contains show up as Volumes in Gio, and they're then individually mountable (or unmountable) as long as the device is attached to the USB port.

So, for GSConnect, it'd be really amazing if connecting with a paired device (with the proper plugins enabled) triggered the creation of a Gio Volume for each of the mountable storage locations configured in KDE Connect. Those Volumes could then be mounted to establish the actual SFTP connection, and unmounted to disconnect it.

Unfortunately, it just doesn't appear that there's any support for this in the current implementation of the Gvfs SFTP backend. Attempting to open an `sftp:` URI "as mountable" (via `gio mount -m <var>uri</var>`) results in an "Operation not supported by backend" error message. And anyway, as you point out the port number can change, which means the `sftp:` URI isn't fully defined for an unmounted storage location.

A custom backend implementing a `gsconnect:` scheme could theoretically solve that problem, since it could identify connected devices by their device ID instead of IP and port#. So, for example, if my paired phone is device `0101deadbeef4321` and exports two remote storage locations, connecting might create two Volumes with `uuid=gsconnect:0101deadbeef4321/sdcard` and `uuid=gsconnect:0101deadbeef4321/Download`. What happens when either Volume is Mounted then becomes a slightly tricky question, because Gvfs would need to trigger GSConnect since it can't establish the mount on its own (not having the `sftp:` URI for the connection) would then ideally just fire off the standard SFTP backend, assuming it can be used for child Mounts and not just top-level orphans.
</details> 

#### Gvfs re- and automounts

> I believe it functions somewhat like `sshfs`'s `-o reconnect` where it _actually_ connects either on access (eg. file list requested/folder opened) or when a clear signal of disconnection happens (eg. some socket/connection closed).

Not that I've seen, due to the Volume-less, transient-Mount issue. It'd be great if it _did_ work like that, actually, because connection interruptions would be survivable. Gvfs mounts SFTP locations "on access", but only in the sense that any request for an `sftp://host:port/path` URI will cause it to attempt a connection to that host if there isn't already one established. But in that case, there's no mount _present_ until the connection is made. 

Any loss of connectivity, in my experience, causes the termination of the connection's `ssh` processes. (Two of them, since you're right about the dual connections — any Gio `sftp:` mount creates two `ssh` processes running on different local ports, both connected to the same remote IP/port.) If that happens, the Mount will vanish and any Nautilus views displaying remote paths will return Home. AFAICT the only way a Gvfs `sftp:` mount would theoretically survive a loss of connectivity is if it _doesn't notice_ the interruption, like in your example session above.

(Though TBH I'm not 100% clear on just how _that's_ possible, either. SFTP (or, SSH itself really) is implemented using TCP streams, not UDP datagrams — the connection is stateful and disconnects should get noticed pretty quickly. And since the SFTP connection is established at mount time, it shouldn't matter whether the mount's been _accessed_ or not.)

The sequence of events in your example is more what I'd expect if the phone's SFTP share _doesn't_ get mounted at step 1 (because no attempt to access a remote URI ever triggered a mount of the remote SFTP host), and therefore there's no connection to terminate. Whereas in step 2... hang on, I just realized I'm not clear on why SFTP would have _any_ port? Or why would step 3, for that matter?

AIUI the SFTP port number is assigned when KDE Connect gets a `kdeconnect.sftp.request` from the desktop with `startBrowsing` set to `true`, correct? When KDE Connect receives that message, it starts an SFTP server on the next available port, and then sends a `kdeconnect.sftp` reply that includes the port number and other connection details. Have I got that right?

Assuming I'm on track so far... now when we reach step 2 and the phone reconnects, does GSConnect automatically generate an additional `kdeconnect.sftp.request` message? Or does KDE Connect take it upon itself to relaunch the SFTP server (on a newly-assigned port number), then send an unsolicited `kdeconnect.sftp` message to the desktop with the new connection parameters?

> Something that's made this more obvious, is upstream has been working on packets being dropped during initial connection. Sftp has always been setup to automount, but as soon as a device connects a large packet exchange happens, often before the Android app has finished loading the plugins that handle those packets (yay thread-safety).

See, now "SFTP has always been setup to automount" sounds like you're saying that anytime GSConnect connects with a known device (assuming the appropriate plugins/configs), it'll automatically send a `kdeconnect.sftp.request` `startBrowsing` message to have KDE Connect start the SFTP server?

That might be problematic. 

Not so much because of the automounting itself, in an ideal world that'd be great and super convenient. The problem is, for those of us whose Android devices do really aggressive power management, the resulting SFTP server will only last a few minutes (at most) before getting forcibly terminated by the OS. So, that mount is going to become a bit of a yo-yo, potentially. And whenever it drops, reconnecting will have to be triggered manually through GSConnect, rendering the mounting **significantly** less than "auto", really.

My desktop normally has my SFTP-accessible home directory on my fileserver mounted in Gvfs — I have it run a `gio mount ...` command at login (after a 20-second delay) so it's there right away. But when that mount is disconnected, my solution for remounting it when I need to is simple: I have the `sftp:` URL for the root of the host stored as a Nautilus bookmark. I can just click that, and it triggers the same type of "Mount & open" operation as with an unmounted Gio Volume.

But the non-static port number (and non-static IP, potentially!) of paired Android devices means that bookmarks won't work. Neither will symlinks through `/run/user/$UID/gvfs/...`. No form of stored remote path will work, because the host details can't be expected to remain constant. Nothing Nautilus or Gvfs can do will allow them to follow the device's IP and/or port changes. _**Only**_ GSConnect has the contents of the device's most recent `kdeconnect.sftp` message, which is required in order to construct a valid `sftp:` URI that matches the device's SFTP server.

I'm starting to wonder if these issues might be the reason why the KDE Connect desktop developers long ago [abandoned the use of KIO to handle mounts, in their own SFTP plugin](https://github.com/KDE/kdeconnect-kde/commit/5b91610e3fa6b2f5a89f4f00020762040b54907a), and instead just run `sshfs` to attach a local filesystem mount point (which _does_ have a static path).

**Comment by andyholmes** [comment] 2019-03-28 21:43
> ...triggered the creation of a Gio Volume for each of the mountable storage locations configured in KDE Connect.
> A custom backend implementing a gsconnect: scheme...

Unfortunately out-of-tree extensions like this aren't even possible in C; they have to be merged upstream. I guess an architecture flaw/oversight. Of course, there's nothing stopping us from handling `gsconnect://` URIs, but it really be more proxying those to invoke the mounting and/or redirecting to the proper path.

> [abbreviated to...] Have I got that right?

Basically, the SFTP server is a per-connection singleton, so it should only be stopped when the "packet connection" breaks. Resending the `startMount` request will just return the same connection info if the server is already running. I think the reason my sftp connection flow is confusing is because of how socket connections are hotswapped, so in way you're right.

Essentially, because of the 30s keepalive, it's pretty common for kdeconnect clients to not notice the packet connection has died. If a client receives an identity broadcast or TCP connection before it realizes the original has died (or if it just hasn't died), the new connection is hotswapped in without triggering a change in connection status. Of course, this can happen asymmetrically so that one side registers a connection change while the other doesn't.

I'm guessing my reconnection effect in Gvfs is actually GSConnect noticing the packet connection break, probably because it's not in a "doze mode", and reopening the packet connection which kdeconnect-android hotswaps in without reloading the sftp server. I'm guessing while kdeconnect-android isn't noticing the connection break, the Gvfs connection hasn't broken somehow?

> I'm starting to wonder if these issues might be the reason why the KDE Connect desktop developers long ago abandoned the use of KIO to handle mounts, in their own SFTP plugin

I believe this was actually a result of the DSS deprecation in openssh, which is not something possible to address in either GIO or KIO since they're too high level.

I suppose there's not much lost in reverting `sshfs` support, although I'm not keen on making it a user-visible option, so it would have to take precedence over Gvfs. Probably the better fix would be to improve `gvfs-sftp` and lobby kdeconnect to pick a static port for sftp. There are in fact a number of free ports between the 1716 and 1739-1764 range.

**Comment by ferdnyc** [comment] 2019-03-29 04:49
> > I'm starting to wonder if these issues might be the reason why the KDE Connect desktop developers long ago abandoned the use of KIO to handle mounts, in their own SFTP plugin
> 
> I believe this was actually a result of the DSS deprecation in openssh, which is not something possible to address in either GIO or KIO since they're too high level.
> 
> I suppose there's not much lost in reverting `sshfs` support, although I'm not keen on making it a user-visible option, so it would have to take precedence over Gvfs. Probably the better fix would be to improve `gvfs-sftp` and lobby kdeconnect to pick a static port for sftp. There are in fact a number of free ports between the 1716 and 1739-1764 range.

I should've been clearer about that, I actually _don't_ think using `sshfs` would **really** solve this problem either... or at least, not correctly/completely. It would just mean that the mount would have a _chance_ of surviving disconnection, in the cases when it can be reestablished on the same port. There are still all the other cases where the SFTP service hops ports, in which case `sshfs` is no less screwed than Gvfs.

The one other advantage `sshfs` might have — at least in theory — is that GSConnect could potentially hide the messy details of host/port selection from the user, and instead mount devices on a well-defined static filesystem path. IOW, with the right connection-juggling logic, a mount of `sftp://192.168.0.9:1740/sdcard/` could be swapped out for `sftp://192.168.0.12:1739/sdcard/` mounted at the same local path (`$HOME/.local/share/gsconnect-mounts/$device_id/sdcard`?), and presto-changeo userland is none the wiser. (As always with such sleight-of-hand: "Neat trick, if you can pull it off.")

But in terms of the former issue, just **not** port-hopping would go a long way towards improving the situation, yeah. And the latter, as you say that could be addressed (and maybe would be better addressed) with Gvfs-sftp improvements. It'd  be nice to see `sftp:` mounts elevated above their current status as transient second-class remote filesystem connections. 

With Gvfs-sftp _right now_, there's no avoiding that the `host:port` details are part of the path to the remote filesystem, and just sort of implicitly presumed to be static. But that's starting to look like an awfully dated connectivity model, in this age of passive remote connections and devices with no fixed network location. GSConnect is far from the only use case for a more robust definition of "remote mount".

**Comment by andyholmes** [comment] 2019-03-30 19:59
True, true. Well, since we can't really fix this in GSConnect, I haven't the time to rewrite gvfs-sftp and the original issue isn't really a bug, I'm going to close this one :)

**Closed by andyholmes** 2019-03-30 19:59 UTC
