### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by anggapw** [andyholmes/gnome-shell-extension-gsconnect#958] opened 2020-09-20 00:12 UTC
![Screenshot from 2020-09-20 08-08-57](https://user-images.githubusercontent.com/67362656/93691511-c4eee980-fb18-11ea-9e09-5b6f15982095.png)
This happened after I updated the extension. I tried to reinstall but got the same result
Gnome version 3.36.6

**Comment by andyholmes** [comment] 2020-09-20 00:57
Duplicate of #817. Please restart GNOME Shell if updating from the website, or use GNOME Extensions.

**Closed by andyholmes** 2020-09-20 00:57 UTC
