### ISSUE TITLE
Messaging window show text of wrong message thread

### ISSUE THREAD

**Issue by siegfriedhuber** [andyholmes/gnome-shell-extension-gsconnect#534] opened 2019-05-08 06:25 UTC
**Messaging window shows text of wrong message thread**
The detail (right) area of the messaging window shows text of a message thread that is not selected.
It looks like the problem occurs with _threads_ where I only receive messages and never reply, like mobile TANs.
![image](https://user-images.githubusercontent.com/37623198/57354101-dd9c7080-716a-11e9-9991-18a681283d84.png)

**Expected behavior**
Show text of selected message thread.

**System Details:**
 - GSConnect version: 23
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.32
 - Distro/Release: Ubuntu 19.04

**GSConnect environment:**
 - Paired Device(s): OnePlus3
 - KDE Connect app version: 1.12.7

**Comment by andyholmes** [comment] 2019-05-09 13:50
Thanks for reporting. Problems with SMS threads are difficult to diagnose without more specific information about the addresses (phone number, e-mail or 2fa name) of the two conflicting names.

It's not necessary to supply the real addresses, but I do need functional equivalents. For example, the length, international prefix, any special characters, etc. From your screenshot alone is it impossible for me to discover the cause since I have no way to reproduce this problem.

**Comment by siegfriedhuber** [comment] 2019-05-10 14:09
I put the messages from my phone vis-a-vis the messages in GSConnect messaging window. I tried to "anonymize" them. I changed most of the phone numbers except of a suspicious "00000" and two others.
I changes the texts of the messages so that length is the same.
I hope this helps.

[gsconnect anonymous2.xlsx](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3166763/gsconnect.anonymous2.xlsx)

**Comment by andyholmes** [comment] 2019-05-10 21:23
Is the number `00000` actually in your messages? If so I'm guessing this is some SMS short code in your country/carrier, and that will definitely cause problems since we have to strip leading 0's to account for international prefixes.

You can try this ZIP and see if it fixes the problem, but I think shortcodes with all `0`'s are usually not allowed in most countries so this could be an error on your phone?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3168139/gsconnect%40andyholmes.github.io.zip) ([Wiki - Install from ZIP](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip))

**Comment by siegfriedhuber** [comment] 2019-05-13 05:57
The number `00000` is, or rather was, actually there. It looked to me as if it was a message with a the initial password for some OTP system. I prematurely deleted the SMS before finishing to read your message. Once deleted the messaging window went back to normal behaviour. So I guess there's no point in trying the zip. 
I will check with my colleagues whether anybody has a SMS with sender `00000`, but I guess you're correct. This is no valid code.
Thanks for your help.

**Comment by andyholmes** [comment] 2019-05-16 21:02
I've pushed a fix to allow for addresses with all `0`'s, so I think this should fix the problem in the rare case it does happen. Closing for now then.

**Closed by andyholmes** 2019-05-16 21:02 UTC
Labels: needs info
