### ISSUE TITLE
GSConnect Error at Extensions page.

### ISSUE THREAD

**Issue by charlesngeru** [andyholmes/gnome-shell-extension-gsconnect#777] opened 2020-03-07 09:46 UTC
**GSConnect red error flag at the extensions page**

My GSConnect was working well, then after I restarted my laptop for a totally unrelated reason I got the GSConnect network error once I logged into my computer. I tried to troubleshoot it but no joy. Finally, I decided to reinstall it, but when I uninstalled and reinstalled it again I got the red flag error. I repeated the steps again but the outcome was the same.

**Expected behaviour**

I expect it to work as promised.

**Screenshots**

![Screenshot from 2020-03-07 12-10-38](https://user-images.githubusercontent.com/31818771/76140804-1947e580-606f-11ea-9495-c1f54e2b5cbf.png)

**Support Log**

There is nothing in the support logs that are relevant to the problem I'm experiencing.

**System Details (please complete the following information):**

 - **GSConnect version: 33**
   - **Installed from: GNOME Extensions Website** 
 - **GNOME/Shell version: 3.34.1**
 - **Distro/Release: Ubuntu 19.10**
 - **Paired Device(s): Samsung Galaxy A70**
 - **KDE Connect app version: 1.13.7**

**Comment by ferdnyc** [comment] 2020-03-07 13:34
[Hi @charlesngeru, can you try the following in a terminal window?

First, to gather some data, please post the output of:
```
gnome-extensions info gsconnect@andyholmes.github.io
```

After that, let's try to wake the extension up:
```sh
# (this should output something like 'gjs killed (pid 12345)', or nothing)
pkill -e -f daemon.js

gnome-extensions reset gsconnect@andyholmes.github.io
gnome-extensions enable gsconnect@andyholmes.github.io
```

...Hopefully, after that, the extension is running. Or if not, there should be some useful log output in your user journal, which you can browse by running `journalctl --user -n 10000 -e`.

**Comment by ferdnyc** [comment] 2020-03-07 13:35
(If you don't have a `pkill` command, you may need to install procps:)
```sh
sudo apt install procps
```

**Comment by charlesngeru** [comment] 2020-03-07 14:12
> [Hi @charlesngeru, can you try the following in a terminal window?
> 
> First, to gather some data, please post the output of:
> 
> ```
> gnome-extensions info gsconnect@andyholmes.github.io
> ```
> 
> After that, let's try to wake the extension up:
> 
> ```shell
> # (this should output something like 'gjs killed (pid 12345)', or nothing)
> pkill -e -f daemon.js
> 
> gnome-extensions reset gsconnect@andyholmes.github.io
> gnome-extensions enable gsconnect@andyholmes.github.io
> ```
> 
> ...Hopefully, after that, the extension is running. Or if not, there should be some useful log output in your user journal, which you can browse by running `journalctl --user -n 10000 -e`.

![Screenshot from 2020-03-07 17-09-03](https://user-images.githubusercontent.com/31818771/76145033-c7b35100-6096-11ea-9741-109d43fe406b.png)

![Screenshot from 2020-03-07 17-10-21](https://user-images.githubusercontent.com/31818771/76145034-cda93200-6096-11ea-8d71-1576c873fd8e.png)

**Comment by ferdnyc** [comment] 2020-03-07 15:44
Thanks! There's definitely a problem with the extension install, not sure what happened but the best option is probably to perform another reinstall, but using the `gnome-extensions` command to force the installation (unlike the extensions web interface).

A few more shell commands, I'm afraid. The long lines run off the edge of the window on Github, unfortunately, but you should be able to just cut-and-paste the entire contents of the text block into a shell window:
```sh
wget https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v33.shell-extension.zip
pkill -e -f daemon.js
gnome-extensions disable gsconnect@andyholmes.github.io
gnome-extensions install --force gsconnectandyholmes.github.io.v33.shell-extension.zip
gnome-extensions enable gsconnect@andyholmes.github.io
```

If you get a command-not-found error on the first line, you can use `curl` instead of `wget` (these are all the same commands, except for the first line):
```sh
curl https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v33.shell-extension.zip --output gsconnectandyholmes.github.io.v33.shell-extension.zip
pkill -e -f daemon.js
gnome-extensions disable gsconnect@andyholmes.github.io
gnome-extensions install --force gsconnectandyholmes.github.io.v33.shell-extension.zip
gnome-extensions enable gsconnect@andyholmes.github.io
```

If _that_ doesn't fix the schema error, then there must be some external cause for the errors. 

Can you check `/usr/share/gnome-shell/extensions/` and confirm that there **isn't** a `gsconnect@andyholmes.github.io` directory in there? (You don't have to bother if the problem is solved, only if GSConnect is still not working after the reinstall. If that's the case, a conflicting systemwide installation might be to blame.)

**Comment by charlesngeru** [comment] 2020-03-07 17:47
> Thanks! There's definitely a problem with the extension install, not sure what happened but the best option is probably to perform another reinstall, but using the `gnome-extensions` command to force the installation (unlike the extensions web interface).
> 
> A few more shell commands, I'm afraid. The long lines run off the edge of the window on Github, unfortunately, but you should be able to just cut-and-paste the entire contents of the text block into a shell window:
> 
> ```shell
> wget https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v33.shell-extension.zip
> pkill -e -f daemon.js
> gnome-extensions disable gsconnect@andyholmes.github.io
> gnome-extensions install --force gsconnectandyholmes.github.io.v33.shell-extension.zip
> gnome-extensions enable gsconnect@andyholmes.github.io
> ```
> 
> If you get a command-not-found error on the first line, you can use `curl` instead of `wget` (these are all the same commands, except for the first line):
> 
> ```shell
> curl https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v33.shell-extension.zip --output gsconnectandyholmes.github.io.v33.shell-extension.zip
> pkill -e -f daemon.js
> gnome-extensions disable gsconnect@andyholmes.github.io
> gnome-extensions install --force gsconnectandyholmes.github.io.v33.shell-extension.zip
> gnome-extensions enable gsconnect@andyholmes.github.io
> ```
> 
> If _that_ doesn't fix the schema error, then there must be some external cause for the errors.
> 
> Can you check `/usr/share/gnome-shell/extensions/` and confirm that there **isn't** a `gsconnect@andyholmes.github.io` directory in there? (You don't have to bother if the problem is solved, only if GSConnect is still not working after the reinstall. If that's the case, a conflicting systemwide installation might be to blame.)

I did everything you asked of me and it didn't work. I even checked to see if the file was in the location you stated and as expected it wasn't there. But once you suggested that it was a systemwide installation may be the cause, I did a deep dive into my system logs and realized there was a problem/conflict with my display properties as I was using Ubuntu on Wayland. 
I decided to reboot and revert to the normal Ubuntu without Wayland and interesting enough GSConnect works now. I also noted that this error started after I updated the GSConnect, it seems it's either there was a problem with the update or my system of which I'm not sure which caused the problem.

**Comment by ferdnyc** [comment] 2020-03-07 18:45
@charlesngeru Hm! Interesting, it's very odd that Wayland-vs-Xorg would affect GSConnect _in **this** way_ (inability to access its GSettings schema).

But I'm glad you worked out the issue, that's the important thing! Impressive bit of sleuthing, too. I think it probably would've taken me a _very_ long time to connect this failure back to the change in display server, if this happened on my system.

Despite the temptation to keep trying to unravel exactly what was going on here, I'm going to close this issue since it sounds like there was _some_ sort of localized issue at play — certainly, we have plenty of users running GSConnect on Wayland-powered systems just fine, so I wouldn't expect we'd be able to even reproduce the issue, much less find the cause and/or fix it.

But please feel free to reopen, if there are any further developments or new discoveries.

**Closed by ferdnyc** 2020-03-07 18:45 UTC
Labels: needs info

**Comment by charlesngeru** [comment] 2020-03-07 19:21
> @charlesngeru Hm! Interesting, it's very odd that Wayland-vs-Xorg would affect GSConnect _in **this** way_ (inability to access its GSettings schema).
> 
> But I'm glad you worked out the issue, that's the important thing! Impressive bit of sleuthing, too. I think it probably would've taken me a _very_ long time to connect this failure back to the change in display server, if this happened on my system.
> 
> Despite the temptation to keep trying to unravel exactly what was going on here, I'm going to close this issue since it sounds like there was _some_ sort of localized issue at play — certainly, we have plenty of users running GSConnect on Wayland-powered systems just fine, so I wouldn't expect we'd be able to even reproduce the issue, much less find the cause and/or fix it.
> 
> But please feel free to reopen, if there are any further developments or new discoveries.

Sure, no problem. Thank you for the help as well.
