### ISSUE TITLE
Lots of errors on Debian Testing

### ISSUE THREAD

**Issue by philn** [andyholmes/gnome-shell-extension-gsconnect#185] opened 2018-09-10 11:36 UTC
My Journal logs are spammed with the following tracebacks. Using gnome-shell 3.28.3-1 here.

```
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Connecting to 'ad782dbe168239bf'
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Authenticating 'ad782dbe168239bf'
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Connected to 'Xiaomi'
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Disconnected from 'Xiaomi'
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Daemon: Removing device
Sep 10 12:27:26 ecto-1 gjs[13296]: JS LOG: Received from 'Xiaomi'
Sep 10 12:27:26 ecto-1 gnome-shell[4197]: Object .Gjs_GSConnectShellPluginButton (0x56544bf4ec10), has been already finalized. Impossible to set any property to it.
Sep 10 12:27:26 ecto-1 gnome-shell[4197]: Object .Gjs_GSConnectShellPluginButton (0x56544bb60c90), has been already finalized. Impossible to set any property to it.
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: == Stack trace for context 0x565448edc320 ==
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #0 0x5654492a9de8 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:238 (0x7fb5a00e6cd0 @ 21)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #1 0x7ffc59145f00 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fb5b80d2230 @ 386)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #2 0x5654492a9d58 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7fb5a85272b8 @ 23)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #3 0x7ffc59147250 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #4 0x5654492a9cd0 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7fb5a8526340 @ 17)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #5 0x7ffc59148590 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #6 0x5654492a9c30 i   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7fb5a8526230 @ 81)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #7 0x7ffc591498d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #8 0x5654492a9ba8 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7fb5a8526340 @ 32)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #9 0x7ffc5914ac10 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #10 0x5654492a9b20 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7fb5a00f5560 @ 67)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #11 0x7ffc5914c2e0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #12 0x5654492a9a98 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:507 (0x7fb5a00f5780 @ 52)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #13 0x7ffc5914d620 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #14 0x5654492a99f8 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:736 (0x7fb5a00f5de0 @ 209)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #15 0x7ffc5914e960 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #16 0x7ffc5914f170 b   self-hosted:918 (0x7fb5b80f1230 @ 394)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #17 0x5654492a9928 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:744 (0x7fb4f6504670 @ 408)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #18 0x7ffc59150fb0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #19 0x5654492a9890 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:710 (0x7fb4f65042b8 @ 66)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: == Stack trace for context 0x565448edc320 ==
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #0 0x5654492a9de8 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:239 (0x7fb5a00e6cd0 @ 38)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #1 0x7ffc59145f00 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fb5b80d2230 @ 386)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #2 0x5654492a9d58 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7fb5a85272b8 @ 23)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #3 0x7ffc59147250 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #4 0x5654492a9cd0 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7fb5a8526340 @ 17)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #5 0x7ffc59148590 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #6 0x5654492a9c30 i   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7fb5a8526230 @ 81)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #7 0x7ffc591498d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #8 0x5654492a9ba8 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7fb5a8526340 @ 32)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #9 0x7ffc5914ac10 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #10 0x5654492a9b20 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7fb5a00f5560 @ 67)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #11 0x7ffc5914c2e0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #12 0x5654492a9a98 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:507 (0x7fb5a00f5780 @ 52)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #13 0x7ffc5914d620 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #14 0x5654492a99f8 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:736 (0x7fb5a00f5de0 @ 209)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #15 0x7ffc5914e960 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #16 0x7ffc5914f170 b   self-hosted:918 (0x7fb5b80f1230 @ 394)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #17 0x5654492a9928 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:744 (0x7fb4f6504670 @ 408)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #18 0x7ffc59150fb0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb5b80b5de0 @ 71)
Sep 10 12:27:26 ecto-1 org.gnome.Shell.desktop[4197]: #19 0x5654492a9890 i   /home/phil/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:710 (0x7fb4f65042b8 @ 66)
Sep 10 12:27:26 ecto-1 gnome-shell[4197]: Object .Gjs_GSConnectShellPluginButton (0x56544a5b9880), has been already finalized. Impossible to set any property to it.
```

**Comment by andyholmes** [comment] 2018-09-13 05:07
Most of these errors are warnings due to changes related to garbage collection in GJS since Gnome Shell 3.26. Aside from the logged messages, there should be no problems caused by this. Unfortunately there won't be another formal release until v13 is merged and stabilized.

**Comment by andyholmes** [comment] 2018-09-26 04:42
I'm going to close this since the issue has essentially been fixed in master, no stack traces of this sort appear there.

**Closed by andyholmes** 2018-09-26 04:42 UTC
Labels: fix committed
