### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by Patatone** [andyholmes/gnome-shell-extension-gsconnect#116] opened 2018-05-17 14:40 UTC
There is a view issue.
![schermata da 2018-05-17 16-38-37](https://user-images.githubusercontent.com/34103646/40184577-e56b9cf6-59f0-11e8-9136-9c0bbf946f56.png)
![schermata da 2018-05-17 16-34-44](https://user-images.githubusercontent.com/34103646/40184580-e694c56c-59f0-11e8-9682-bf48b228c9e2.png)
![schermata da 2018-05-17 16-43-19](https://user-images.githubusercontent.com/34103646/40184809-6ee818ba-59f1-11e8-8bcb-eb3fc375bf84.png)

**Comment by andyholmes** [comment] 2018-05-17 15:37
Can you tell me if you are using v11, this looks like a duplicate of #44

**Comment by Patatone** [comment] 2018-05-17 16:59
What is v11? Sorry for that :persevere:

**Comment by andyholmes** [comment] 2018-05-17 22:29
The extension website currently distributes version 10 of the extension while version 11 contains a fix for this problem. You can download it [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/latest) and there are instructions for installing it [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip).

**Comment by Patatone** [comment] 2018-05-18 16:53
You can't update it here? https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by andyholmes** [comment] 2018-05-18 17:14
It's already uploaded, waiting for review. You can either wait for approval or install manually, it's up to you.

**Comment by Love4Taylor** [comment] 2018-05-19 09:37
v11...
![](https://img.love4taylor.me/large/af997d39gy1frgs5ons3dj211y0lc77y.jpg)
![](https://img.love4taylor.me/large/af997d39gy1frgs9pofaoj211y0lcgpo.jpg)

**Comment by AdamKane41** [comment] 2018-05-19 10:09
@andyholmes you are one patient person my friend... we all filled the same bug report... once a day a new one pop-ups... thanks for never loosing it! ;-p

**Comment by andyholmes** [comment] 2018-05-19 15:45
@Love4Taylor thanks for reporting with screenshots showing you're using v11. This seems to be a problem specifically with Ubuntu's Humanity icon theme which makes a judgement to return a 48x48 icon instead of the requested 32x32 to maintain sharpness.

Here's an up to date build you can install using the [instructions in the wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip) or you can use a different icon theme:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2019595/gsconnect.andyholmes.github.io.zip)

**Closed** 2018-05-19 15:45 UTC

**Comment by Patatone** [comment] 2018-05-19 17:20
Will the fix upload in: https://extensions.gnome.org/ ?

**Comment by andyholmes** [comment] 2018-05-19 19:12
Eventually, yes. Then it will go through the review process and be distributed once approved.
