### ISSUE TITLE
Port to cinnamon

### ISSUE THREAD

**Issue by gnurichard** [andyholmes/gnome-shell-extension-gsconnect#169] opened 2018-08-18 03:19 UTC
Cinnamon is a fork of gnome, could be possible port gsconnect to cinnamon

**Comment by andyholmes** [comment] 2018-08-18 06:47
Duplicate of #118

It's probably possible, but I don't use Cinnamon or know much about what makes it different. Probably the best thing to do would be for someone using Cinnamon or familiar with Cinnamon extensions to fork GSConnect and keep the necessary changes synced.

Sorry, I just don't have time to do this myself.

**Closed by andyholmes** 2018-08-18 06:47 UTC
