### ISSUE TITLE
Old notifications pile up

### ISSUE THREAD

**Issue by lnicola** [andyholmes/gnome-shell-extension-gsconnect#364] opened 2018-11-28 06:52 UTC
After installing GSConnect, I noticed that my calendar widget would randomly stop working and the mouse cursor would lag when moving it above the menu area. Disabling GSConnect doesn't help, but also disabling and re-enabling Dash to panel makes the calendar work again.

So I just realized what's happening. My old notifications from e.g. chat apps all pile up in the Gnome notification panel (the one next to the calendar). After maybe some 10-100 of them, the panel starts lagging or stops working completely.

I'm not sure what KDE Connect and GSConnect can do here. Can they detect that a notification was dismissed from the phone? Can Gnome notifications be removed? I'd rather not disable this functionality, since it's pretty useful.

Note that I haven't tried disabling Dash to panel, it may be that it's a bit inefficient (the widget looks the same, though), as I can't stand to use Gnome without it.

```

**System Details (please complete the following information):**
 - GSConnect version: 16
 - Dash to panel version: 16
   - Installed from: [e.g. extensions.gnome.org, GitHub Release download, distro package, ...]
 - GNOME/Shell version: 3.30
 - Distro: Arch Linux
```

**Comment by andyholmes** [comment] 2018-11-28 19:05
Ah yes, this is a known upstream bug in gnome-shell: [#209 Notification list can potentially grow ad infinitum](https://gitlab.gnome.org/GNOME/gnome-shell/issues/209)

GNOME Shell sets a 3 notification limit for applications to prevent this, so it usually only affects `notify-send`, but GSConnect removes that limit for us.

> I'm not sure what KDE Connect and GSConnect can do here. Can they detect that a notification was dismissed from the phone?

Yes, but it doesn't. Hmm, the short version is that libnotify notifications are send using a DBus method and the return value of that method is the notification id that you need to close it. Although it's pretty easy to monitor the DBus interface and forward notifications, it's probably impossible for an outside application like KDE Connect to intercept the notification id.

For this reason, the same functionality that allows us to close notifications from the desktop is not implemented on Android. See here:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/b7a11f477438432a5b947c656a07df1d5490379a/src/service/plugins/notification.js#L128-L136

You could open an upstream bug (it is one *technically*), but the best way to get this fixed is really for someone on "our" side to submit a patch for the Android app. Probably they will never fix this themselves, since it would only work for GSConnect.

**Comment by andyholmes** [comment] 2019-05-05 20:26
Closing this since it's technically an upstream bug and I don't have to time to work on the upstream patch myself.

**Closed by andyholmes** 2019-05-05 20:26 UTC
Labels: upstream

**Comment by pacho2** [comment] 2020-04-04 21:01
I am still hitting this near every day. I wonder why gsconnect cannot send all the notifications under "gsconnect" application , as upstream also thinks that the applications that are not sending them in that way are doing it wrong too , then, we are stuck with this and it's really easy to hit it (as soon as you receive multiple messages from, for example, multiple whatsapp) :/

Thanks

**Comment by andyholmes** [comment] 2020-04-04 22:50
> I wonder why gsconnect cannot send all the notifications under "gsconnect" application

That is what we do. There are really only two options here:

1. Show all notifications

   In this case, we show all notifications and only close device notifications when the device tells us to. If the device is not connected when the notification is closed, we aren't asked to close them. 

   When a device receives a notification, it sends a packet telling us there is a new notification. When a device connects, it sends a packet for each notification that is currently open. In other words, the device doesn't send a list of notifications we can use to tell what notifications have been closed while we were offline.

2. Only ever show three notifications

   This means three total; regardless of whether they come from GSConnect itself, a remote device, or multiple devices. Since desktop notifications weren't designed for this use case, it also means that any time a notification gets replaced GSConnect will request the device dismiss the notification.

`#1` is the current behaviour, since it has the least disruptive behaviour. If we go with `#2` there's no guarantee you even see a notification before it's closed, both on the desktop and the phone.

**Comment by pacho2** [comment] 2020-04-04 23:55
Is not possible to show only three notifications in desktop but not dismissing them in the phone? For example currently, I can clean all notifications in gnome-shell and it doesn't dismiss the notification in the phone. That would be the option I think it would fit better. Like a "fake" dismiss, it's dismissed from desktop side but, when returning to the phone to dismiss, the call is interrupted to, at the end, leave it untouched there

Piling them in desktop is not really useful as most of the times it takes many seconds (or even more than one minute) to load them. Even in the phone (depending on the apps), notifications are not piled forever (for example in whatsapp there is a limit and when there are a lot of messages you can only see the last ones).

Also, for example, the official Whatsapp Web, whose notifications are also shown in gnome-shell tray while it's opened, is only showing the last notification, and new notifications are overwriting previous ones

**Comment by andyholmes** [comment] 2020-04-05 00:09
> Is not possible to show only three notifications in desktop but not dismissing them in the phone?

Sure, but they will just come back anyways and there's no guarantee the notifications that end up in the message tray will be the ones you want.

> Piling them in desktop is not really useful as most of the times it takes many seconds (or even more than one minute) to load them.

That really is more of an issue in gnome-shell. There's no disk I/O happening, which means there's some pretty serious drawing bottleneck if it takes even a second to draw them.

If you really want, I'll change it, but I'm not going to change it back and forth if different users want different things.

**Comment by pacho2** [comment] 2020-04-05 00:26
I agree that gnome-shell has an issue with this, but the problem is that they seem to not really care as they think apps shouldn't behave like that. It seems the way they would take is to add another limit for all "unknown-apps" that would be not really a fix:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/209

As I see that the limit is being evaded on purpose in src/shell/notification.js maybe one option would be to make this configurable or, if adding a limit, and people think that 3 notifications is too few for gsconnect, we can try a higher number but still keep a limit (maybe "10", but I guess it will depend on the used system resources, in my case going over ~14 starts to show lag).

The worst of current situation is not that it takes a minute to load them, is that during that minute, user cannot interact with gnome-shell and needs to wait. 
In my case I deal with it because I know what is causing the problem (I even installed another extension to allow me to clean the notifications without opening them when I realize that I must have too many notifications waiting for me), but for users not knowing what is going on, is not really good :/

Personally, I would opt for still overwrite it in src/shell/notification.js to increase a bit the limit of 3, not remove it completely. Maybe a limit of 6-10 could be tried at first.

Thanks

**Comment by ferdnyc** [comment] 2020-04-05 01:08
> 
> I guess it will depend on the used system resources, in my case going over ~14 starts to show lag).

...With THAT many notifications being mirrored to your desktop, are they really all relevant?

I mean, I don't know. Maybe the answer is, "yes, they really are", and I can accept that. But that just seems like a LOT of notifications, if you're getting "over 14" synced from the device. Keep in mind that YOU have _very_ fine-grained control over which apps' notifications are mirrored, from the KDE Connect app plugin settings. 

I know that, personally, I turned off a **bunch** that I'm willing to tolerate on my phone (even though with Android 9 I could for the most part turn them off completely), but I just don't need copies sent to my computer.

**Comment by pacho2** [comment] 2020-04-05 09:53
Oh, over 14 are easy to get as soon as you get some messages from messaging apps like Whatsapp, I know they are not really relevant and that is the reason I would like to limit them. I only put that "~14" as an example to try to find a balance between 3 (that maybe is too short taking into account that the limit would apply to all notifications from gsconnect) and the no-limit. It was an example only.

Thanks a lot , I will try the patch :)

**Comment by adymitruk** [comment] 2020-05-16 17:38
I want the option to not notify my of _ANY_ stale mobile notifications. It's making my laptop useless. And they come in waves. The lack of this option makes kdeconnect not usable.
