### ISSUE TITLE
GSConnect doesn't start on startup

### ISSUE THREAD

**Issue by ANtlord** [andyholmes/gnome-shell-extension-gsconnect#739] opened 2019-12-23 07:32 UTC
**Describe the bug**

GSConnect doesn't start on startup. In order get it worked I go to extensions, activate it manually, so it works but it doesn't see my phone. I launch GSConnect settings and push Refresh button, it connects to the phone but icon of GSConnect doesn't appear on the top panel.

**Steps To Reproduce:**

1. Install Ubuntu 19.10
2. Install GSConnect
3. Reboot a computer
4. GSConnect is not launched.

**Expected behavior**

GSConnect starts automatically, connects to the paired phone, shows its icon in top right corner

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

```
GSConnect Version: 30
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Fri 2019-11-08 09:25:47 EET, end at Mon 2019-12-23 09:14:30 EET. --
Dec 23 09:14:01 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:05 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:09 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:14 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:18 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:22 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:26 gnome-shell[4189]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e00007
Dec 23 09:14:26 dbus-daemon[3213]: [session uid=1000 pid=3213] Reloaded configuration
Dec 23 09:14:26 gnome-software[4969]: failed to rescan: Failed to parse /home/wantlord/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop
Dec 23 09:14:26 gnome-software[4969]: failed to rescan: Failed to parse /home/wantlord/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.Preferences.desktop file: cannot process file of type application/x-desktop
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gsd-media-keys[4395]: == Stack trace for context 0x55694a88b1a0 ==
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b0c98e0.
Dec 23 09:14:26 gsd-media-keys[4395]: == Stack trace for context 0x55694a88b1a0 ==
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b0c9ee0.
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b0c95e0.
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b335370.
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b0c9be0.
Dec 23 09:14:26 gnome-shell-ext[6500]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Dec 23 09:14:26 gnome-shell-ext[6500]: The offending signal was destroy on Gjs_ExtensionRow 0x55694b0c92e0.
Dec 23 09:14:26 dbus-daemon[3213]: [session uid=1000 pid=3213] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.80' (uid=1000 pid=4466 comm="/usr/lib/tracker/tracker-miner-fs " label="unconfined")
Dec 23 09:14:26 systemd[3134]: Starting Tracker metadata database store and lookup manager...
Dec 23 09:14:26 dbus-daemon[3213]: [session uid=1000 pid=3213] Successfully activated service 'org.freedesktop.Tracker1'
Dec 23 09:14:26 systemd[3134]: Started Tracker metadata database store and lookup manager.
Dec 23 09:14:26 dbus-daemon[3213]: [session uid=1000 pid=3213] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.80' (uid=1000 pid=4466 comm="/usr/lib/tracker/tracker-miner-fs " label="unconfined")
Dec 23 09:14:26 systemd[3134]: Starting Tracker metadata extractor...
Dec 23 09:14:26 dbus-daemon[3213]: [session uid=1000 pid=3213] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
Dec 23 09:14:26 systemd[3134]: Started Tracker metadata extractor.
Dec 23 09:14:26 dbus-daemon[1270]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.580' (uid=1000 pid=6514 comm="gjs /home/wantlord/.local/share/gnome-shell/extens" label="unconfined")
Dec 23 09:14:26 systemd[1]: Starting Hostname Service...
Dec 23 09:14:27 dbus-daemon[1270]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 23 09:14:27 systemd[1]: Started Hostname Service.
Dec 23 09:14:27 kernel: usb usb2-port2: Cannot enable. Maybe the USB cable is bad?
Dec 23 09:14:30 org.gnome.Shell.Extensions.GSConnect[5915]: [/service/protocol/core.js:send:329]: asus: {
                                                              "id": 1577085270350,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": true,
                                                                    "volume": 24900,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_01_00.1.hdmi-stereo",
                                                                    "description": "HDMI / DisplayPort (HDA NVidia Digital Stereo (HDMI))",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo",
                                                                    "description": "Speakers (USB PnP Audio Device Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "bluez_sink.4C_87_5D_0A_FB_7A.a2dp_sink",
                                                                    "description": "Headphone (Bose QuietComfort 35 Series 2)",
                                                                    "muted": false,
                                                                    "volume": 60292,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Dec 23 09:14:30 org.gnome.Shell.Extensions.GSConnect[5915]: [/service/protocol/core.js:send:329]: asus: {
                                                              "id": 1577085270410,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3.analog-stereo",
                                                                    "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                    "muted": true,
                                                                    "volume": 24900,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_01_00.1.hdmi-stereo",
                                                                    "description": "HDMI / DisplayPort (HDA NVidia Digital Stereo (HDMI))",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo",
                                                                    "description": "Speakers (USB PnP Audio Device Analog Stereo)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "bluez_sink.4C_87_5D_0A_FB_7A.a2dp_sink",
                                                                    "description": "Headphone (Bose QuietComfort 35 Series 2)",
                                                                    "muted": false,
                                                                    "volume": 60292,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
```

**System Details (please complete the following information):**

 - **GSConnect version:** 30
   - **Installed from:** GNOME Extensions Website, GitHub, Package Manager
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Ubuntu 19.04, Ubuntu 19.10

**GSConnect environment (if applicable):**

 - **Paired Device(s):** ASUS Zenfone max pro m1
 - **KDE Connect app version:** 1.13.3

**Additional Notes:**

Actually it has been happening for 3 months but I get a change to make the bug report only now. By the way should I have `kdeconnected` launched? It happened with Ubuntu 19.04 and not it happens with Ubuntu 19.10

**Comment by ferdnyc** [comment] 2019-12-23 12:12
@ANtlord 



> By the way should I have `kdeconnected` launched? It happened with Ubuntu 19.04 and not it happens with Ubuntu 19.10

No, in fact, having the Linux `kdeconnectd` running will interfere with GSConnect, as they use the same network ports. That's most likely the cause of the issue you're seeing. We recommend uninstalling the `kdeconnect` package(s) when using GSConnect.

**Comment by ANtlord** [comment] 2019-12-23 12:14
> We recommend uninstalling the kdeconnect package(s) when using GSConnect.
I don't have it

**Comment by ferdnyc** [comment] 2019-12-23 12:34
Hmmm, OK. In that case, there are two possibilities.

1. You could try downloading the [`v31-rc1` version](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v31-rc1) and installing it from zip file ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)), to see if that clears up the issue. There have been a few changes since `v30` that might affect things.

2. Otherwise (or if that doesn't work), we'll need a support log capture that shows the process of activating a non-working device connection in GSconnect.
    
    Meaning, when you start your session and the device isn't connected,
    1. Select "Mobile Settings" from the GNOME Shell user menu
    1. Select "Generate Support Log" from the menu in the settings window
    1. Wait for the capture dialog to open
    1. _**Then**_ hit the Refresh button in the settings window to connect the phone
    
    You could even try completely restarting GSConnect's daemon:
    1. Select "Turn Off" from the GNOME Shell user menu
    1. The Mobile Settings window should change to show "Waiting for service..."
    1. Select "Turn On" from the GNOME Shell user menu
    1. The Mobile Settings window should show the detected device, initially as "Disconnected"
    1. After a couple of seconds, that _should_ automatically change to "Connected"

But again, you'd want to do all of that _after_ starting the "Generate Support Log" process, as detalied logs are only collected while the capture dialog is open.

When you're done reproducing the issue, hit "Review Log" to display the captured messages, remove any sensitive personal data, and post the logs here so we can review them.

**Comment by ferdnyc** [comment] 2019-12-23 12:43
Come to think of it, one thing you should check up front is whether the daemon is really running in the first place.

Hitting Refresh in the settings window _implicitly_ activates the daemon, but when it's not running then GSConnect won't auto-connect to devices.

So, if the user menu shows a "Turn On" option above "Mobile Settings", or if the settings window shows "Waiting for service...' when you first open it, then that means the daemon isn't active and needs to be started. It could be that it's not starting automatically for some reason.

**Comment by ANtlord** [comment] 2019-12-23 14:21
I try v31-rc1. I don't get an icon of GSConnect on the top panel and I don't get any items in the user menu still so I can't get "Mobile settings"
That's what I do:
1. Enable GSConnect in Gnome Tweaks
2. Reboot my machine, the top panel doesn't show icon of GSConnect, the user menu doesn't show mobile settings.
3. I open Gnome Tweaks, GSConnect is disabled (but I enabled it in the previous session)
4. I enable GSConnect. Still no icon or "Mobile Settings" menu item and phone is not connected.
5. I open GSConnect's settings, there is a caption "Waiting for service..."
6. Wait for a minute, nothing happens
7. I select "Generate Support Log" and don't push "Review Log"
8. Wait for a couple of seconds, still no icon, no menu item, no devices.
9. Push "Update" button in GSConnect settings. Caption "Waiting for service..." disappears, my phone is in the list with status "Disconnected" then it is "Connected" after a couple of seconds. Still no icon, no menu item.
10. I push "Review Log"
11. Remove my personal sms messages from the log
Here is the [Review Log result](https://gist.github.com/ANtlord/886297dfade0de264979b7feb6454e03)

**Comment by ferdnyc** [comment] 2019-12-23 22:57
@ANtlord Perfect, thanks!

> 3\. I open Gnome Tweaks, GSConnect is disabled (but I enabled it in the previous session)

Ouch, OK, so GSConnect simply isn't being started automatically _at all_. That's extremely strange.

Do you have other GNOME Shell extensions installed, and are they automatically enabled at the start of the session?

Unfortunately I'm not sure there's anything GSConnect can really do about the problem, since extensions don't have any control over whether or not they're enabled — that's completely managed by GNOME Shell. I can't really think of a reason why it wouldn't preserve the enabled state of GSConnect across sessions, though. Obviously it's properly installed and recognized by the Shell, since you're able to manually enable it.

Your experience of needing to Refresh the state manually after enabling the extension I can confirm, manually enabling the extension doesn't always launch the `daemon.js` backend process if it isn't already running. But enabling the extension on each session shouldn't be necessary in the first place.

You could check the logs to see if GNOME Shell logs some error when trying to start GSConnect at startup, though I don't expect there will be. Normally if GNOME Shell fails to enable an extension, it'll mark it as not working and you won't be able to manually enable it either.

Still, can't hurt to check the logs:
```sh
#To review your user journal since the system was last rebooted
# (You might have to scroll down a couple hundred lines or so.
# You'd be looking for messages involving "gsconnect" or "gjs" — but
# not all "gjs" messages are necessarily about gsconnect.)
journalctl --user -b

# Or, you can search for matching lines

# Lines containing 'gsconnect'
journalctl --user -b --grep gsconnect

# Lines containing 'gjs' (not all GSConnect-related)
journalctl --user -b --grep gjs

# Lines containing 'gnome-shell' (not all GSConnect-related)
journalctl --user -b --grep gnome-shell
```

Like I said, you'd be looking for anything that might indicate a problem launching the extension at startup. At least **most** of the messages won't be important, in fact I suspect none of them will be.

Oh, one other test you can try, since you're running X11: Once the extension is enabled and working, if you restart the Shell does it _stay_ enabled? You can perform a restart of your existing session (without closing any applications or anything) by hitting <kbd>Alt</kbd>+<kbd>F2</kbd> to bring up the command-entry dialog, then typing `r` and hitting <kbd>Enter</kbd>. (Yes, the command is just a single lowercase letter '`r`'.)

**Comment by andyholmes** [comment] 2019-12-24 03:48
It seems like the service is running fine, but the shell extension is failing to start. Is there anything in the log when you enable GSConnect in GNOME Tweaks? You can watch that with:

```sh
$ journalctl -f -o cat /usr/bin/gnome-shell
```

**Comment by ANtlord** [comment] 2019-12-24 10:42
> Do you have other GNOME Shell extensions installed, and are they automatically enabled at the start of the session?

Yes, I do. There are User Themes extension and Clipboard Indicator extension. They start automatically.

In order to provide clear logs I've deactivated other extensions manually with Gnome Tweaks and restarted my machine. So here logs go.

`$ journalctl --user -b --grep gsconnect`
shows
```
-- Logs begin at Fri 2019-11-08 09:25:56 EET, end at Tue 2019-12-24 12:31:35 EET. --
Dec 24 12:31:29 wantbook org.freedesktop.FileManager1[2679]: GSConnect: No translation file found for domain
```

`$ journalctl --user -b --grep gjs`
shows
```
-- Logs begin at Fri 2019-11-08 09:25:56 EET, end at Tue 2019-12-24 12:31:50 EET. --
-- No entries --
```

`$ journalctl --user -b --grep gnome-shell`
shows
```
-- Logs begin at Fri 2019-11-08 09:25:56 EET, end at Tue 2019-12-24 12:31:50 EET. --
Dec 24 12:31:17 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating service name='org.gnome.Shell.CalendarServer' req
Dec 24 12:31:17 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gnome.evolution.da
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gtk.vfs.UDisks2Vol
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gtk.vfs.MTPVolumeM
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gtk.vfs.GPhoto2Vol
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gtk.vfs.GoaVolumeM
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gtk.vfs.AfcVolumeM
Dec 24 12:31:18 wantbook gnome-shell[3056]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1090]:
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating service name='org.freedesktop.FileManager1' reque
Dec 24 12:31:18 wantbook dbus-daemon[2679]: [session uid=1000 pid=2679] Activating via systemd: service name='org.gnome.evolution.da
```
> Oh, one other test you can try, since you're running X11: Once the extension is enabled and working, if you restart the Shell does it stay enabled?

Yes, it does

> Is there anything in the log when you enable GSConnect in GNOME Tweaks?

Unfortunately nothing

**Comment by kakolisgay** [comment] 2019-12-24 22:08
Also having this issue on a completely fresh install, something is definitely up with the extension. Ubuntu 19.10, GNOME 3.34.1

**Comment by andyholmes** [comment] 2019-12-31 20:49
Doesn't seem like there were any errors related to GSConnect in the log posted.

The best log will really be unstripped from `journalctl -f -o cat /usr/bin/gnome-shell`. Grepping the logs is more useful if you know what you're looking for, but this may be a distro specific problem.

1. Have the extension disabled

   This means "switch off" in GNOME Tweaks or `gnome-shell-extension-prefs` and the service should not be running.
2. Run `journalctl -f -o cat /usr/bin/gnome-shell` in a terminal

   This will show all messages from GNOME Shell, instead of just messages from GSConnect which may not include the error
3. Turn the extension on

   At this point the extension will already be initialized, but enabling it actually starts executing code, so this is where the error will be.

**Comment by ddnexus** [comment] 2020-01-05 07:22
Here it does not find any device nor it is found, however the activation or deactivation persists as expected.

On deactivation there is only an entry in the log:

`../../../gobject/gsignal.c:2647: instance '0x55b40bb74c80' has no handler with id '75314'`

and the id increases each activation/deactivation cycle.

HTH

**Comment by andyholmes** [comment] 2020-02-01 04:03
Is this issue still occurring for some users, or has it been solved by using the `gnome-extensions` tool and/or the User Menu item?

**Comment by ddnexus** [comment] 2020-02-01 08:49
Yes. I updated yesterday to the latest extension and it still does not fin the device. 

> has it been solved by using the gnome-extensions tool and/or the User Menu item?

I may have missed something in the thread and I don't understand the question. Are that supposed to be some sort of work-arounds/fixes?

**Comment by andyholmes** [comment] 2020-02-01 09:57
The original issue was the GSConnect service not starting automatically. If the issue you're experiencing is devices not connecting, then that's a different issue.

Can you open a new issue, where you confirm that your devices are on the same network, any firewalls are correctly configured, ports are open and you can ping your device directly. Then [Generate a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log)?

**Comment by ANtlord** [comment] 2020-02-03 08:34
> Is this issue still occurring for some users, or has it been solved by using the `gnome-extensions` tool and/or the User Menu item?

I got the application launched by enabling it via `gnome-extensions` so if it's acceptable I suppose the issue can be closed. Honestly I'd like to see the note in the Help section of the Wiki. After all only this application launches so but all the rest my applications are enabled with Gnome Tweaks

**Comment by ddnexus** [comment] 2020-02-03 11:07
Indeed, it starts both with Tweaks and with gnome-extensions. The `gjs` process is up listening on port TCP *:1716. Same thing on the android side: the KDE Connect app is listening on the 1716. Should I check other ports, and how?

**Comment by ddnexus** [comment] 2020-02-03 12:48
I had some local problem that might be related with a wrong /usr/sbin permission on my machine. Fixing that also fixed the issue with the specific port, so it's definitely not a bug. No new issue needed, and you can close this one too, as far as I am concerned. Thanks.

**Comment by andyholmes** [comment] 2020-02-03 13:02
> Honestly I'd like to see the note in the Help section of the Wiki. After all only this application launches so but all the rest applications of mine are enabled with Gnome Tweaks

There is ultimately no difference between these; ultimately they all just call methods on the `org.gnome.Shell.Extensions` DBus interface:

* GNOME Tweaks (`gnome-tweaks`)
* `gnome-extensions`
* `gnome-shell-extension-prefs`
* https://extensions.gnome.org

You can add a note to the Wiki if you like (it is after all a wiki), but in your case the extension simply wasn't enabled.

> No new issue needed, and you can close this one too, as far as I am concerned. Thanks.

Hooray I fixed it! :wink:

**Closed** 2020-02-03 13:02 UTC
Labels: needs info, shell-extension

**Comment by gofordeepu** [comment] 2022-08-21 02:09
I am getting the same issue but not able to resolve it using above comments. The gsconnect extension is enabled when i am starting my pc but not able to see the my phone battery or phone related details in panel or usermenu ....first i have to go to gsconnect setting and refresh it then there my phone is showing as connected but again in panel or usermenu i am not able to see my phone details.
![Screenshot from 2022-08-21 07-36-52](https://user-images.githubusercontent.com/55938474/185772285-2d5e8f4c-f81c-4bd4-9107-a853141c3833.png)

**Comment by gofordeepu** [comment] 2022-08-21 02:10
![image](https://user-images.githubusercontent.com/55938474/185772306-84c877c2-2bde-49b2-a571-14092201c3e9.png)
when i am rebooting my pc it's not automatically detecting my device.

**Comment by gofordeepu** [comment] 2022-08-21 02:12
![image](https://user-images.githubusercontent.com/55938474/185772331-82964690-d1fe-4259-8b6d-2fa0554cef57.png)
after clicking on refresh button i can see my device is connected but in usermenu or in panel i can't see my phone related details anywhere.
![Screenshot from 2022-08-21 07-42-11](https://user-images.githubusercontent.com/55938474/185772351-1866726d-2a5b-442e-a1a8-604887987f51.png)

**Comment by gofordeepu** [comment] 2022-08-21 02:16
My system details:
Linux deepu-singh 5.15.0-46-generic #49~20.04.2-Ubuntu SMP Fri Aug 12 08:03:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gnome shell version: GNOME Shell 3.36.9

**Comment by andyholmes** [comment] 2022-08-21 23:01
I'd recommend you follow the steps in the wiki to [reset all settings](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) and perform a clean install. Other than that, GNOME 3.36 is long out of support for the project at this point.
