### ISSUE TITLE
"Do Not Disturb" user menu entry can't be enabled in Gnome 3.34

### ISSUE THREAD

**Issue by jkotra** [andyholmes/gnome-shell-extension-gsconnect#655] opened 2019-10-04 06:21 UTC
GSconnect 26
Arch Linux (Up to date) Gnome 3.34

I am aware 3.34 is not officially supported but i just want to bring this issue to light so it will be noted.

Problem:

Cannot enable DND - toggle.

![](https://i.imgur.com/5web8NT.gif)

**Comment by ferdnyc** [comment] 2019-10-04 07:35
@jkotra 

What if you run this command in a shell?
```sh
gsettings --schemadir ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/schemas/ \
set org.gnome.Shell.Extensions.GSConnect donotdisturb $(($(date +%s) + 120))
```

(That'll manually enable DND for a period of 2 minutes from when you execute the command.) Does it show as enabled in the menu, then? If so, can you then _disable_ it via the menu?

**Comment by jkotra** [comment] 2019-10-04 07:40
> @jkotra
> 
> What if you run this command in a shell?
> 
> ```shell
> gsettings \
> --schemadir ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/schemas/ \
> set org.gnome.Shell.Extensions.GSConnect donotdisturb $(($(date +%s) + 120))
> ```
> 
> (That'll manually enable DND for a period of 2 minutes from when you execute the command.)
> 
> Does it show as enabled in the menu, then? If so, can you then _disable_ it via the menu?

Yes, command works and it's showing as enabled.I can disable it via menu.

**Comment by ferdnyc** [comment] 2019-10-04 11:06
OK, cool, so it's just the user menu entry that's not working — probably a failure launching the DND timeout dialog.

If you could reproduce the issue in a Generate Support Log session and post the results, that'd hopefully show us the exact nature of the problem. Literally just...
1. Open Mobile Settings
1. Activate "Generate Support Log" in hamburger menu
1. Wait for the log-collection dialog to appear
1. Go into the user menu and click on "Do Not Disturb"
1. Click "Review Log" in the log-collection dialog
1. Post whatever messages it brings up

Thanks!

**Comment by ferdnyc** [comment] 2019-10-04 11:07
(Note: Just to state the obvious, DND should be _off_ before starting the process, so that the click in step 4 is an attempt to activate it.)

**Comment by jkotra** [comment] 2019-10-04 11:13
```

GSConnect Version: 26
GSConnect Install: user
GJS: 15800
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Fri 2019-09-27 15:57:35 IST, end at Fri 2019-10-04 16:42:42 IST. --
Oct 04 16:42:32 dbus-daemon[781]: [session uid=1000 pid=781] Activating service name='org.gnome.gedit' requested by ':1.84' (uid=1000 pid=1936 comm="gjs /home/th4n0s/.local/share/gnome-shell/extensio")
Oct 04 16:42:32 dbus-daemon[781]: [session uid=1000 pid=781] Successfully activated service 'org.gnome.gedit'
Oct 04 16:42:32 gnome-shell[828]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c000f8
Oct 04 16:42:42 gnome-shell[828]: JS ERROR: TypeError: this._getDurationLabel is not a function
                                  Dialog@/home/th4n0s/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/donotdisturb.js:186:17
                                  MenuItem/<@/home/th4n0s/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/donotdisturb.js:300:30
                                  toggle@resource:///org/gnome/shell/ui/popupMenu.js:374:9
                                  activate@resource:///org/gnome/shell/ui/popupMenu.js:361:13
                                  _onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:135:9
Oct 04 16:42:42 gnome-shell[828]: value "-1.000000" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'

```

**Comment by andyholmes** [comment] 2019-10-04 19:37
Thanks for reporting, I believe all of these issues were fixed in 234d4d2.

**Comment by jkotra** [comment] 2019-10-04 20:33
Thanks. Any ETA on when this commit(s) land on extensions.gnome.org?

**Comment by andyholmes** [comment] 2019-10-04 22:41
There's no ETA, but hopefully before October 17th when Ubuntu 19.10 is due to be released.

**Comment by andyholmes** [comment] 2019-10-06 05:09
Closing since this is fixed in `master`.

**Closed** 2019-10-06 05:09 UTC
Labels: fixed in master, needs testing
