### ISSUE TITLE
Make old notifications expire to avoid lag

### ISSUE THREAD

**Issue by rainbyte** [andyholmes/gnome-shell-extension-gsconnect#748] opened 2020-01-07 03:57 UTC
**Is your feature request related to a problem? Please describe.**
When there are many notifications accumulated, gnome shell starts to show some kind of lag

**Describe the solution you'd like**
It would be better to keep only the last N notifications, making old ones expire

**Describe alternatives you've considered**
Other option could be making each notification expire after some time

**System Details (please complete the following information):**
 - GSConnect version: 30
 - Installed from: Arch Linux AUR

**Comment by andyholmes** [comment] 2020-01-14 03:23
This is an upstream issue in GNOME Shell ([#209 Notification list can potentially grow ad infinitum](https://gitlab.gnome.org/GNOME/gnome-shell/issues/209)) that's difficult to address because of how notifications work in KDE Connect.

We basically get two kinds of information: there's a notification open on the device and a notification was closed on the device. Although we can request the remote device's notifications, we don't get a "digest" or list of the device's notifications, just a series of notifications.

This means there's no way to ask the remote device if a particular notification is still open, and if GSConnect is disconnected when the notification is closed, we'll just never know. This is complicated by the fact that a device can handle it's local notification however it wants, by reusing id's, having unclosable notifications, not keeping track of open notifications, etc.

duplicate of #364

**Closed** 2020-01-14 05:57 UTC
Labels: duplicate, upstream
