### ISSUE TITLE
V 12 Not working on Ubuntu18.10

### ISSUE THREAD

**Issue by wada3n** [andyholmes/gnome-shell-extension-gsconnect#257] opened 2018-10-24 20:43 UTC
hi 
I use the latest version and get this error:

> Gio.DBusError: Erreur lors de l’appel de StartServiceByName pour org.gnome.Shell.Extensions.GSConnect : GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Shell.Extensions.GSConnect exited with status 1
> 
> Stack trace:
>   _init@/home/home/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:33:9
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _parent@resource:///org/gnome/gjs/modules/_legacy.js:39:12
>   _init@/home/home/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:695:9
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _init@/home/home/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:100:23
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   buildPrefsWidget@/home/home/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
>   _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
>   @<main>:1:43
>

**Comment by lorek123** [comment] 2018-10-24 21:02
Duplicate of https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/186

**Comment by andyholmes** [comment] 2018-10-24 21:03
It sounds like you are using v12 on Gnome 3.30. You should update to v13 by following the instructions on [Install from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) page.

**Comment by andyholmes** [comment] 2018-10-25 00:17
You should report upstream, probably in Launchpad, although I'm not sure what their policy for updating packages during a release are.

**Comment by wada3n** [comment] 2018-10-25 11:45
@andyholmes Of course I'm using the last version from zip file

**Comment by wada3n** [comment] 2018-10-25 11:50
After restarting and loading the file again
Everything works wonderfully
Sorry and thank you so much

**Comment by andyholmes** [comment] 2018-10-25 12:34
> init@/home/home/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:33:9

This file here does not exist in v13. Either you have installed GSConnect from the extensions website, not yet restarted Gnome Shell or the install was not clean (leftover files from v12).

**Comment by andyholmes** [comment] 2018-10-26 07:02
I'm going to close this now since v13 has been released on the official extensions website.

**Closed by andyholmes** 2018-10-26 07:02 UTC
