### ISSUE TITLE
Error displayed after upgrade

### ISSUE THREAD

**Issue by Fabioah** [andyholmes/gnome-shell-extension-gsconnect#259] opened 2018-10-25 17:22 UTC
Hi, I have just updated this app and this error occurs.
![schermata da 2018-10-25 19-19-26](https://user-images.githubusercontent.com/34600288/47518370-1b9b0c80-d88b-11e8-86ab-a3dae830bff2.png)

Sorry but I am quite ignorant and I don't know if I have to post something else

**Comment by andyholmes** [comment] 2018-10-25 20:22
That's okay. The bug you're seeing has been fixed in `master` (the newest, but unreleased code). For now you can install the updated Zip file below by following the [Install from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) instructions again:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2496021/gsconnect.andyholmes.github.io.zip)

I'll close this now, because it's a duplicate of #246. If you need more help, there are users and comments on that issue that may be of some help, or even be helped by your comments. Thanks for the report.

**Closed by andyholmes** 2018-10-25 20:22 UTC
