### ISSUE TITLE
Huawei Mate 20 lite message issues.

### ISSUE THREAD

**Issue by torbbang** [andyholmes/gnome-shell-extension-gsconnect#462] opened 2019-02-14 21:43 UTC
**Describe the bug**

Huawei Mate 20 Lite does not sync messages.

**To Reproduce**
Pair a Huawei Mate 20 Lite with GSConnect and open messages.

**Expected behavior**
Messages syncing to GSConnect so that one can browse through them.

**Screenshots**
![image](https://user-images.githubusercontent.com/45107069/52819073-bc1a7400-30a8-11e9-955c-4f889adafea1.png)

**Debug output**

```

```

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: Distro repository
 - GNOME/Shell version: 3.30
 - Distro/Release: Fedora 29
**GSConnect environment (if applicable):**
 - Paired Device(s): Huawei Mate 20 lite
 - KDE Connect app version: Not sure, new to android and could not find the version.
 - Plugin(s): All available plugins enabled. Does not make a difference whether I disable everything but SMS.

**Additional context**
I am able to send messages.

**Comment by andyholmes** [comment] 2019-02-15 03:57
Hi, if you can please report this information upstream, preferably with a logcat from Android. The bug has been reported for a number of phones and Android version, but still lacks the logs KDE Connect developers need to fix this in the Android app.

https://bugs.kde.org/show_bug.cgi?id=401677

Duplicate of #320

**Closed** 2019-02-15 03:57 UTC
Labels: duplicate, upstream
