### ISSUE TITLE
Incomprehensible UX with respect to missing extensions or features

### ISSUE THREAD

**Issue by fbruetting** [andyholmes/gnome-shell-extension-gsconnect#354] opened 2018-11-22 17:23 UTC
**Describe the bug**
GSC annoys with showing warnings about missing extensions repeatedly over and over again.

![bildschirmfoto von 2018-11-22 18-29-18](https://user-images.githubusercontent.com/10520767/48917124-80935380-ee85-11e8-8d18-6cb0158d0da8.png)

1. Every time I lo-in to my system, I get a warning about some missing feature due to Wayland being used. Do I want to click-away the same stupid warning every time I log in to my system? Certainly not!
2. Additionally, I always get a notification about missing extensions, while the message points me to the GSC settings window. When I then click on that, I see the settings window, with a lot of spinners, which turn into warning symbols after about 10 seconds. These warnung symbols then show a timeout error when hovering.

I really don’t understand the intention about all this. I don’t want to repeatedly get error messages about the exact same error, which may not even be an error if I don’t need that specific feature. That’s one of the reasons why I don’t use Windows. I also don’t get the purpose of the second issue. I get a warning without having an issue at all, then being led to the options window, which than can show me absolutely no useful information. Why all this…?!

![bildschirmfoto von 2018-11-22 18-06-05](https://user-images.githubusercontent.com/10520767/48916700-9869d800-ee83-11e8-9eb7-e33445c4d82d.png)

![bildschirmfoto von 2018-11-22 18-06-09](https://user-images.githubusercontent.com/10520767/48916704-9b64c880-ee83-11e8-82c2-5ca694760300.png)

**To Reproduce**

1. Install GSC (maybe it’s due to Fedora Silverblue systems with Wayland running only, I don’t know).
2. Install no GSC extension.
3. Re-log-in to Gnome shell with Wayland, while GSC is active.

**Expected behavior**
I expect to get warnings about missing features/extensions just once and/or permanently in the extensions options or the extension manager, but never ever repeatedly without any reason.

**System Details (please complete the following information):**
 - GSConnect version: I think 15, the about window doesn’t work.
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30
 - Distro/Release: Fedora 29

**GSConnect environment (if applicable):**
 - Paired Device(s): Nexus 5X
 - KDE Connect app version: [e.g. ]

**Comment by andyholmes** [comment] 2018-11-22 17:54
duplicate of #344

**Closed by andyholmes** 2018-11-22 17:54 UTC
Labels: UX, duplicate
