### ISSUE TITLE
Errore nel chiamare StartServiceByName per org.freedesktop.UPower: Failed to activate service 'org.freedesktop.UPower': timed out (service_start_timeout=25000ms)

### ISSUE THREAD

**Issue by open-antux** [andyholmes/gnome-shell-extension-gsconnect#962] opened 2020-09-20 09:31 UTC
```
GSConnect Version: 41
GSConnect Install: system
GJS: 16404
XDG_SESSION_TYPE: x11

_init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/upower.js:18:14
_initComponents@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:436:37
vfunc_startup@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:592:14
vfunc_handle_local_options@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1011:18
@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074:17
```

**Comment by andyholmes** [comment] 2020-09-20 20:05
Thanks for reporting, duplicate of #948. Please upgrade to v42.

**Closed by andyholmes** 2020-09-20 20:05 UTC
