### ISSUE TITLE
Contacts not showing in the messages window

### ISSUE THREAD

**Issue by pedrofleck** [andyholmes/gnome-shell-extension-gsconnect#277] opened 2018-10-28 04:40 UTC
I was using an older git version since I'm using Gnome 3.30, I was having a problem that the only contacts shown in the SMS window was the ones that I received SMS, then I decided to update to the Shell Extensions version (uninstalled and installed again). Now, I can't configure my devices (they don't show up in configurations (pairing again won't fix) and no contacts at all show when I try to send a SMS. Sending ping, SMS to a number, browsing files and other stuff works normally.

**Comment by andyholmes** [comment] 2018-10-28 06:30
Hmm, it's tricky because a lot of things changed during that period that were not at all backwards or forwards compatible.

In particular, I moved the cached contacts file on purpose, because GData (direct to Google) support was removed and the file format changed to support the upcoming Android contacts sync plugin. This was probably when your contacts disappeared.

If you're okay starting from scratch, I'd recommend you uninstall and wipe everything listed in [File Locations](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#file-locations). At this point you might as well pull from master since it's quite close to v14, and you could even grab a build of the Android app from the new [nightly build server](https://binary-factory.kde.org/view/Android/job/kdeconnect_android/) and test out some of the experimental stuff like SMS history and contacts sync.

In any case, if a full wipe doesn't fix this let me know because the problem is probably deeper (maybe in the libfolks wrapper).

**Comment by pedrofleck** [comment] 2018-11-02 01:29
Uninstalling and cleaning all gsconnect files worked (wasn't working just reinstalling)! I went conservative with Play Store and v13 because I need to be sure it's working since I use it for productivity. Looking forward to v14 final version though! Thanks.

**Comment by pedrofleck** [comment] 2018-11-02 01:33
My devices are showing in the config window now! But I still can't see any contact. I went conservative with Play Store and v13 because I need to be sure it's working since I use it for productivity. Looking forward to v14 final version though.

**Comment by andyholmes** [comment] 2018-11-02 02:01
Sound good, there are still some changes happening in Android before SMS/Contacts lands and we might have to make some changes afterwards to make it work.

If you have your contacts in Google, and have the dependencies for Desktop Contacts installed, you will still need to have the account registered in Gnome Online Accounts for that to work. I'll try and remember to clarify that in the Wiki.

v14 was uploaded with a single fix that was affecting a lot of people, but all of this work is almost ready to be released as v15. We just need to clean up a few things since it's a big release in a lot of ways.

**Comment by pedrofleck** [comment] 2018-11-10 11:38
I guess I'm using v14 now (nothing happens when I click "about") and the new SMS history is great! I still can't send a message to a new contact (only number), but if the person already sent a message, it shows up (and that's enough functionality for me, although I know it's not the desired behaviour). I have my contacts in Google, the dependencies and the account in Gnome settings, gnome-contacts app shows all my contacts by the way. It's weird that this is happening since the names and pictures appear correctly if I already exchanged messages with the person.

**Comment by andyholmes** [comment] 2018-11-11 01:06
Oh okay, maybe something went wrong during the contacts sync the first time. Try this then instead:

* Disable Contacts plugin
* Delete `~/.cache/gsconnect/<device-id>/contacts.json`
* Enabled Contacts plugin
* Open SMS window, select "_Sync Contacts_" in app-menu (the menu in the panel beside _Activities_)
* Wait a few seconds, then close/open window

If you have two devices it might be hard to tell which `<device-id>` is right, but you can delete both `contacts.json` because if the plugin is still enabled it will have that info in memory.

If that still doesn't work, might be a problem with Unicode characters if you have non-English names. I made a few names with special characters for testing, but maybe I missed something and we can track that down in the log files.

**Comment by pedrofleck** [comment] 2018-11-11 15:44
Done, it wasn't difficult to find which device was right because the tablet folder was full of contact pictures. It didn't work again, and even the contacts that were showing disappeared. I don't think it's related with Unicode characters since I have the same Google Account and contacts on my tablet, but the non english characters are:
`á é í ó ô ã ç`
What would happen if I copy `contacts.json` from the tablet folder to the phone folder? Since theoretically they're the same contacts?

**Comment by andyholmes** [comment] 2018-11-12 05:13
> I don't think it's related with Unicode characters since I have the same Google Account and contacts on my tablet...

That is strange, there's definitely nothing different done for tablets and phones.

> What would happen if I copy contacts.json from the tablet folder to the phone folder? Since theoretically they're the same contacts?

Yep, that should work. The two files should be exactly the same, just make sure you have the plugin disabled for your phone when you copy the `contacts.json` file over. The images are absolute paths though, so they will point to your tablet's cache directory. As long as you don't delete those files this should work.

**Comment by andyholmes** [comment] 2018-11-14 07:58
I know you said you're using this at work, but if you're playing with the cache files, maybe you want to give something new a shot. I've been trying to find time to redo the messaging UI, but there's been a lot of bug reports lately.

Anyways, this Zip is basically v16 (just released), only changes are a newer SMS UI and all the old, unused telephony junk has been stripped out:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2579689/gsconnect.andyholmes.github.io.zip)

**Comment by logix2** [comment] 2018-11-27 10:59
I too am having this issue. No contacts are synchronized on my desktop. I'm currently using GSConnect v17, but this feature didn't work in previous versions either. I do have the required dependencies installed. Using Ubuntu 18.10 and Samsung Galaxy S6.

**Comment by andyholmes** [comment] 2018-11-27 21:18
Are the contacts not being stored in contacts.json or are they just not showing in the messaging UI? Could you try this Zip that includes two contact related fixes?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2621885/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment] 2018-11-28 00:08
Sorry, small error in the previous Zip, try this one if you have a chance:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2622314/gsconnect.andyholmes.github.io.zip)

**Comment by logix2** [comment] 2018-11-28 10:41
Using either the latest release or your zip, the contacts file is empty (only contains ``{}``). Could there be some issue with Samsung's Android mod that prevents this from working?

**Comment by andyholmes** [comment] 2018-11-28 20:12
> Could there be some issue with Samsung's Android mod that prevents this from working?

Ah, that might very well be. I hadn't thought of that honestly :confused:

I can't find any obvious answers on Google about where Samsung stores their contacts. The only way I could think to test is if you were to "disconnect" the Samsung contact app from Google or whatever cloud, then add a fake contact and see if it's present in Google's contact app (which you may have to install).

The alternative is to sync your contacts with a provider supported by GNOME Online Accounts (Google, NextCloud, etc), [install libfolks support](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#desktop-contacts) and disable the device contacts plugin. Probably you would have to restart the service, too.

**Comment by andyholmes** [comment] 2018-12-01 22:52
@ferdnyc your contacts *are* syncing properly with GSConnect, right?

**Comment by ferdnyc** [comment] 2018-12-01 23:49
> @ferdnyc your contacts _are_ syncing properly with GSConnect, right?

Let's see... yep, sure are. Even a brand-new, just-created contact appears in GSConnect a minute or two later. (It might've appeared sooner, that's the time that passed between me creating it and checking for it.)

I'm not seeing SMS history, even though I use Android Messages, but Contacts sync seems fine.

**Comment by ferdnyc** [comment] 2018-12-01 23:54
In fact, I just created two more contacts, one directly on my Phone, one in my Samsung account (there's a dropbox selector at the top of the "Create contact" interface, normally I leave it set to "Google" and manage all of my contacts within my GMail account) — both of _those_ were also synced to GSConnect, almost immediately.

**Comment by ferdnyc** [comment] 2018-12-01 23:59
Heh. And after linking those three together within the phone's contact manager, I now have a _fourth_ contact representing the linked version — but I also still have the three individual contacts as well. So, that probably explains some of the duplication I'm seeing in my GSConnect contacts list. 

![image](https://user-images.githubusercontent.com/538020/49334102-e0cb7900-f59a-11e8-8034-827700b97608.png)

But, yeah, if anything Contacts are _over_-syncing, for me. :grin:

**Comment by andyholmes** [comment] 2018-12-06 19:52
> But, yeah, if anything Contacts are over-syncing, for me.

I think I managed to fix this one before my laptop died, it just wasn't cropping old contacts at all :/

**Comment by andyholmes** [comment] 2018-12-24 23:02
I think all of the contact sync bugs have been fixed in v18 now. Please re-open if the same issue persists after upgrading.

**Comment by jjaone** [comment] 2019-01-10 04:40
Contacts sync problem is still here. I am using Ubuntu 18.10 Desktop (Gnome-Shel 3.30 + GSConnect-plugin v19 in About screen) with Nokia6/Android8 in which I have KDE Connect app installed from Google Play store and no Contacts or Messaging converstaions get synced from the phone to desktop.

**Comment by andyholmes** [comment] 2019-01-10 04:43
Hi, can you please update to the latest release on Github, [v20](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v20), using the [instructions in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) and see if that solves the problem?

**Comment by andyholmes** [comment] 2019-01-14 00:16
Hi, can you confirm the Android app has contacts permissions, the contacts plugin enabled and what contacts app you are using?

Can you also please use the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) feature, then open the messaging window and press the [+] button to sync and post the output?

**Comment by andyholmes** [comment] 2019-03-13 23:32
I've removed the [bug] tag since I'm not convinced this is a bug in GSConnect, but more likely another Android vendor specific problem with contacts storage. We'll need a debug log with errors showing GSConnect making a mistake or an empty contacts packet to be sure of either.

**Comment by andyholmes** [comment] 2019-05-05 20:24
Closing since there's been no activity or logs supplied in ~4 months. Please re-open if you can still reproduce this bug and supply logs.

**Closed by andyholmes** 2019-05-05 20:24 UTC
Labels: needs info

**Comment by tukusejssirs** [comment] 2019-08-30 11:34
CentOS 7 AMD64
GSConnect installed from `extensions.gnome.org` (v24)
Installed `folks` (`PackageKit` and `gnome-packagekit` were already installed)
All Android permissions for KDE Connect (v1.12.93) are enabled.
I use Google Contacts.

First I tried to enable Contacts plugin (in both Android and CentOS). Messages synced, but not the contacts.

Then I disabled the Contacts plugin (in both Android and CentOS). Installed `folks` package. I was already signed into Gnome Contacts using my Google credentials. Still, the messages synced, but not the contacts.

I tried to generate support log, but I have no idea if I did it right. Here is the output:

```bash
# GSConnect support log:
GSConnect Version: 24
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
journalctl: unrecognized option '--no-host'


```bash
# journalctl tail:
Aug 30 13:30:43 srvr-lnv-e531 org.gnome.Shell.Extensions.GSConnect[9932]: [/service/device.js:loadPlugin:779]: OnePlus: "loading 'contacts' plugin"
Aug 30 13:30:43 srvr-lnv-e531 org.gnome.Shell.Extensions.GSConnect[9932]: [/service/__init__.js:JSON.load/</<:145]: Error opening file /home/ts/.cache
                                                                          JSON.load/</<@/home/ts/.local/share/gnome-shell/extensions/gsconnect@andyhol
                                                                          @/home/ts/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
Aug 30 13:30:43 srvr-lnv-e531 org.gnome.Shell.Extensions.GSConnect[9932]: [/service/protocol/core.js:send:220]: OnePlus: {
                                                                            "id": 1567164643526,
                                                                            "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                                            "body": {}
                                                                          }
Aug 30 13:30:47 srvr-lnv-e531 org.gnome.Shell.Extensions.GSConnect[9932]: [/service/device.js:unloadPlugin:814]: OnePlus: "unloading 'contacts' plugin
Aug 30 13:30:47 srvr-lnv-e531 gjs[9932]: gsignal.c:2641: instance '0xc6cf970' has no handler with id '331814'
```

**Comment by andyholmes** [comment] 2019-08-31 09:30
Unfortunately there are no relevant errors related to GSConnect here. This just shows the contacts plugin being loaded, GSConnect requesting the contacts, you phone not sending any contacts and then the plugin being unloaded.

I'd recommend you file an upstream report on the [KDE Connect Bug Tracker](https://bugs.kde.org/buglist.cgi?component=android-application&list_id=1659025&product=kdeconnect). If you phone is not sending any contacts, this is likely a bug in the Android app.

If you want to you folks, you may have to restart GNOME Shell, I'm not aware if GSConnect will detect if you install it while running.

**Comment by talesam** [comment] 2019-11-23 17:01
I have a Mi5 running MIUI 11 European, no contact appears in SMS. Does anyone know what it can be?

**Comment by krodelabestiole** [comment] 2024-04-19 17:16
same here using grapheneOS.

unfortunalety the _review log_ button doen't open any window or show any info. it just closes the popup :/

is the log stored somewhere ?
