### ISSUE TITLE
SMS no longer works and unable to mount the file system

### ISSUE THREAD

**Issue by JPThiel** [andyholmes/gnome-shell-extension-gsconnect#495] opened 2019-03-20 18:52 UTC
March 20, 2019:
I tested GSconnect v21 and also Mconnect with an Android device (Huawei P9 Lite) on which I installed KDEconnect v.1.12.3 (with Play Store).
**1)** Send SMS no longer works
**2)** Can not mount the file system of the Android device !
I think this is a regression that is not due to GSconnect or Mconnect ???

**Comment by andyholmes** [comment] 2019-03-20 19:15
> 1) Send SMS no longer works

This is detailed in the changelog on Google Play:

> NOTE: This version doesn't support SMS due to Google's new policy!
> 
> 1.12.3:
> - Fix crash on Android 4

> 2) Can not mount the file system of the Android device !

This is a duplicate of #491, there is currently no fix.

**Closed** 2019-03-20 19:19 UTC
Labels: duplicate, upstream
