### ISSUE TITLE
Logging Issue - disk space saturation

### ISSUE THREAD

**Issue by Lolorase** [andyholmes/gnome-shell-extension-gsconnect#800] opened 2020-03-29 13:48 UTC
Hi,

Several times, I found in the morning my computer with the root partition with disk space full.
After investigation, I found each time the /var/log/syslog.1 was over 40GB size.

Unfortunately the file size does not allow me to go through it and provide log assertion just before it started. I can only make a tail command on last lines (100) which show this recursive assertion :

Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: #0   55ae7243fd78 i   /home/laurent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1135 (7fcad07851f0 @ 1293)
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: == Stack trace for context 0x55ae721d11a0 ==
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: The offending callback was SourceFunc().
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: #0   55ae7243fd78 i   /home/laurent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1135 (7fcad07851f0 @ 1293)
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: == Stack trace for context 0x55ae721d11a0 ==
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: #0   55ae7243fd78 i   /home/laurent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1135 (7fcad07851f0 @ 1293)
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: The offending callback was SourceFunc().
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: == Stack trace for context 0x55ae721d11a0 ==
Mar 29 00:00:17 ASUS-Vivo org.gnome.Shell.Extensions.GSConnect[1584]: #0   55ae7243fd78 i   /home/laurent/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1135 (7fcad07851f0 @ 1293)
Mar 29 00:00:17 ASUS-Vivo gjs[2087]: The offending callback was SourceFunc().

**Expected behavior**

It seems that a recursive test is failing and logging too much. It should stop at some point and may need to restart trying after a certain amount of time or ask for a user action.

**System Details (please complete the following information):**

 - **GSConnect version: 33
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.2
 - **Distro/Release:** Ubuntu 19.10

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Huawei MATE 20 Lite (SNE LX1)
 - **KDE Connect app version:** 1.13.7

I open this new defect because previous ones have been closed on the same topic.

**Comment by andyholmes** [comment] 2020-03-29 19:36
Hard to track this one down without more information. We have very few explicit uses of GSources and none of them should touch finalized objects.

Since I can't reproduce this, there's not much I can do to fix it until there's a hint of what's triggering it.

**Comment by ferdnyc** [comment] 2020-03-30 03:55
It's worth noting a couple of things:
1. `daemon.js:1135` is the end of the file, making the source reference not _particularly_ useful, as such.
1. The GC _itself_ is a recursive algorithm.

Hmm... unless it really _is_ complaining about the last line of the file. As you say, @andyholmes, there aren't many instances of `GSources`, but I'm guessing there is an implicit use of `SourceFunc()` in the `run()` that sets the whole thing in motion.

Is it possible that, with no explcit references to the `Service` object, the GC is trying to reap the entire daemon for some reason? Any chance this change would make some sort of difference?
```js
let srv = new Service();
srv.run([imports.system.programInvocationName].concat(ARGV));
```

**Comment by andyholmes** [comment] 2020-03-30 18:23
> Hmm... unless it really is complaining about the last line of the file.

Oh, the reason it's tagging the last line is that's where the [`GMainLoop`](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html) is started from, which is where all `GSources` get queued (at least in GJS). So the stack trace to GJS just looks like `GMainLoop` -> `GSource`, because it doesn't know/care where the source was created and why it's not very helpful.

The fact that it's tagging a `SourceFunc()` and re-occurring probably means it's an explicit source we created, as opposed to a GTask callback. But there's only a few of those in GSConnect and most of them are try-catch wrapped, so :man_shrugging:

**Comment by andyholmes** [comment] 2020-04-04 00:30
These stack traces seem to be [logged with `g_critical`](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/gi/function.cpp#L182), so these should be able to caught with `gdb`. You'd want to find a way to reproduce this though, as GSConnect would run pretty slow in a debugger.

**Comment by Lolorase** [comment] 2020-04-18 10:54
Hi,

I tried several way to reproduce it like shutting down wifi connection (from pc), my internet box (which is the wifi dhcp srever) or phone... Nothing generated a single line of log.

I have read also comment from ferdnyc to check `deamon.js:1135` but in my version it is not the the end of file. 
`
1134           if (options.contains('share-file')) {
1135              this._cliShareFile(id, options);
1136           }
1137
1138            if (options.contains('share-link')) {
1139                this._cliShareLink(id, options);
1140            }
1141            return 0;
1142        } catch (e) {
1143            logError(e);
1144            return 1;
`
I may have misunderstood.
I kind of understand that it is linked to a share file function... seems odd to me since I never used this functionality until now. I mainly use the music player control and have 2 commands (launch rhythmbox client and close rhythmbox client). I tried once the mouse distant control.
Anyway, I tried a share file from the phone to the PC and then... It started to log like hell... 
[syslog.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4496464/syslog.zip)

So it seems that the function itself have a logging problem.
While transferring the file, I shut down my internet box to break the wifi signal and it seems to have stopped logging then.
Put it back on and it started logging again.

Then, I cancelled the transfer from the phone. The signal seems to work since it stopped logging.
But the app is still notifying me a a file sending... very odd... I'll check for fix with app developer.

Still if it is the problem, I can't understand how this function was activated... Is there some "shadow" file exchange that could have start the crazy logging ?

Hope it helps.

**Comment by andyholmes** [comment] 2020-04-18 19:26
The only errors I see in that log seem to be related to the MPRIS plugin, but I don't see any errors from the share plugin. The errors from the MPRIS plugin seem to be caught correctly, so I don't see those causing any stack traces.

The only stack traces I see in the log are from gnome-shell. Are you sure this is not another extension interfering with notifications or something else GSConnect does?

**Comment by Lolorase** [comment] 2020-04-24 15:27
New test, I have done this :
- Shut all other gnome extension
- reboot my computer
- clear the syslog
- try to send a file from the phone

And the syslog stayed empty. So I guess you're right that there are some interaction with another extension... Which one is to be determined. I put back on MPRIS, do a file transfer again. Still got an empty syslog.

BUT, actually there is still something strange that might get to the bad interaction with the unkown extension.

Even if the file is correctly sent to the computer, I've got an error message notification
![Capture d’écran de 2020-04-24 17-24-56](https://user-images.githubusercontent.com/62840252/80229419-af9c8e80-8650-11ea-8e84-5532cea2c37e.png)

I don't know exactly how to progress now...

**Comment by andyholmes** [comment] 2020-04-24 17:18
If the problem was caused by another extension, you should figure out which one and open an issue for that extension.

For the file transfer error, you should open a new issue and [Generate a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

**Comment by Lolorase** [comment] 2020-04-27 13:21
OK thanks. I think what got me confuse can be also some the interaction with the use of media control and MPRIS... I continue some testing and it seems also to be defects with mpd control...

**Comment by andyholmes** [comment] 2020-08-20 04:11
Going to close this one, since at best it seems to be a duplicate of #891 which has better logging (not the reporter's fault though). Feel free to follow that issue if you still experience the logging problem.

**Closed by andyholmes** 2020-08-20 04:11 UTC
Labels: needs info
