### ISSUE TITLE
Notification freezes gnome shell on popup

### ISSUE THREAD

**Issue by glenfordwilliams** [andyholmes/gnome-shell-extension-gsconnect#181] opened 2018-09-01 01:17 UTC
As the title says, whenever i get a notification my display noticeably freezes for about half a second

using the Gsconnect listed here - https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by andyholmes** [comment] 2018-09-01 03:54
Is this receiving a notification from a remote device, or from your desktop?

**Comment by glenfordwilliams** [comment] 2018-09-01 15:12
from a device  @andyholmes

**Comment by andyholmes** [comment] 2018-09-13 05:09
Sorry, it's been so long before I got back to this. I've reviewed the code path for receiving notifications and there doesn't seem to be anything that would cause a delay that long. If you open the debug log in the *About* page are there any related error messages?

**Comment by andyholmes** [comment] 2018-09-26 04:46
I believe this issue might have been instigated by GSConnect, but has more to do with Gnome Shell choking on a high number of notifications, since notifications are handled in a different process, transferred in a thread and sent asynchronously.

I'm going to mark this a _fix committed_ and close it when v13-rc1 is out.

**Comment by jgoulet1994** [comment] 2019-05-07 16:46
A similar issue to this is actually plaguing me, but I can't really find a way to reproduce it.  Most notifications come through without and freezing, but sometimes my shell will just freeze for a second or two and a notification will appear (from this extension).  

Should I make a new issue?

**Comment by ferdnyc** [comment] 2019-05-07 18:21
@jgoulet1994 It's possible that's just the JavaScript garbage collector making itself known, deciding to kick in when the shell process is rudely yanked out of its slumber by the notification. (Even though that moment is the exact _worst_ time to fire off the garbage collector, which Murphy's Law of GC would indicate is therefore the most likely time for it to happen.)

...On the other side of the coin, if you typically run with enough memory pressure that the Shell would end up getting swapped out , that delay could just be the virtual memory system frantically paging it back into active RAM. (Which is a roundabout way of saying, "There may not really be a problem to solve, there.")

OTOH, if you're seeing network-communication errors in the journal, like in nicber's logs at #199, that'd be a different story.

**Comment by jgoulet1994** [comment] 2019-05-07 18:30
I don't think it is the memory issue.  I typically have ~7GB of memory unused out of 12GB.  I don't think it's similar to [#199](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/199) because usually it is just a single notification (could be from text, messenger, etc).

**Comment by andyholmes** [comment] 2019-05-08 07:15
I can reopen this issue, but there's really no blocking code in the notification plugin and even if there were this is all done in a separate process from gnome-shell.

I expect this is probably in GNOME Shell, but either way without more information there's not much I can do.

**Comment by andyholmes** [comment] 2019-05-13 21:32
@glenfordwilliams you can observe the logs from gnome-shell with:

    $ journalctl -f -o cat /usr/bin/gnome-shell

Or gjs processes with:

    $ journalctl -f -o cat /usr/bin/gjs

Although unless there's an actual error, it might be hard to track down what is happening, unless there's some common circumstances when this slowdown happens.

**Comment by andyholmes** [comment] 2019-06-15 04:10
Closing due to inactivity and lack of actionable information. Please reopen if the issue persists and you can gather logs.

**Closed by andyholmes** 2019-06-15 04:10 UTC
Labels: needs info
