### ISSUE TITLE
Gnome-shell fails to start with core dumped error with this extension

### ISSUE THREAD

**Issue by alexryndin** [andyholmes/gnome-shell-extension-gsconnect#174] opened 2018-08-22 12:29 UTC
I'm trying to install this extension on my Arch Linux OS. No matter where I'm trying to install it from, aur or extension.gnome.org, gnome-shell refuses to start after installation with core-dumped error. Log is above:
https://pastebin.com/raw/5VDj4UDf

**Comment by alexryndin** [comment] 2018-08-22 20:53
@andyholmes yes, Shell started right after I removed GSConnect and restarted gdm. Nothing special with PulseAudio on my system. Logs were shrunk to core dump and some lines before, so you may not see all other errors. All of this is referred to my Arch Linux OS on Dell Latitude 5480. 
Today I've tryed to install the extension on my old Asus K55DR with Ubuntu 18.04. Everything were going well (after all, KDE Connect is amazing with all its "move pc's cursor with you smartphone" and many other things), but then I've been dropped to login screen. Again, I couldn't login unlit I deleted extension through tty. This time, I didn't found any core dumped errors or any other suspicious messages.

**Comment by alexryndin** [comment] 2018-08-22 20:55
I will test it again more thoroughly on next weekend.

**Comment by andyholmes** [comment] 2018-08-31 03:59
Sorry I haven't been back to this in awhile.

One thing that might help is to start a log command like `journalctl -f -o cat /usr/bin/gnome-shell` in a tty, then try logging into Gnome Shell. When it crashes you can check the full GJS log instead of just the C/C++ level dump. I think that if this is a JS error that will be more useful and if it's not a JS error that will narrow down the possibilities a lot.

**Comment by alexryndin** [comment] 2018-08-31 08:28
@andyholmes thx. I've upgraded my arch last weekend and installed gsconnect again. Problem's gone and plugin works now. Unfortunately I didn't managed to know what exactly caused this error.
 I didn't test it yet on Ubuntu 18.04, sure your log command will help.

**Comment by andyholmes** [comment] 2018-09-13 05:17
Is this issue still a problem or can I close it for now?

**Comment by linuxarcher** [comment] 2018-09-17 17:09
I can reproduce this on a fresh install of Arch. dmesg says:
> [ 2268.523631] pool[12931]: segfault at 0 ip 00007fc31376b635 sp 00007fc300c92818 error 4 in libc-2.28.so[7fc31362e000+14b000]
> [ 2268.523635] Code: 00 00 0f 1f 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1 
> [ 2268.523701] audit: type=1701 audit(1537203778.289:374): auid=1000 uid=1000 gid=1000 ses=30 pid=12738 comm="pool" exe="/usr/bin/gnome-shell" sig=11 res=1

`journalctl -f -o cat /usr/bin/gnome-shell` says:
> GNOME Shell started at Mon Sep 17 2018 19:03:05 GMT+0200 (CEST)
> ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 pid=12961 comm="pool" exe="/usr/bin/gnome-shell" sig=11 res=1

Sorry, I can see that this doesn't help much, but I don't know how else I could help...

**Comment by andyholmes** [comment] 2018-09-18 01:01
Hmm, segfaults are really bad, especially if this prevents you from logging in with extension at all. It's somewhat worse because "debug mode" has to be turned on in the extension, which may be why there's not much help here.

I wasn't too hopeful, but after a quick Google for "libc-2.28.so segfault", this issue seems to be coming up in many projects. It seems it might have something to do with the toolchain used to build `glibc-2.28` on Arch. I'm not familiar with how package dependencies work in Arch, but is it possible for you to downgrade to 2.27 without breaking your system or that there is newer build of 2.28 you can try?

**Comment by linuxarcher** [comment] 2018-09-18 17:52
Today I got an update to gnome-shell-3.30, and now everything is working flawlessly (using the zip from #186 ). Bug solved itself, if it really was a bug in your extension (which seems doubtful), sorry.....

**Comment by andyholmes** [comment] 2018-09-18 19:09
Glad to hear it got fixed! The only way I really know how to cause a segfault in GJS is with a programmer error with GSettings (like accessing a non-existent setting), so I'm really careful about that.

A big focus of the rewrite I've been working on has been to try and anticipate critical bugs and fail gracefully, so hopefully that gets better. It's always a good idea to report any bugs even related to GSConnect because it helps me plan for those, so open as many issues as possible! That way I can add it to the FAQ if it's commonly reported, too.

**Closed by andyholmes** 2018-09-18 19:09 UTC
