### ISSUE TITLE
Queue and postpone sending files and URL to away device

### ISSUE THREAD

**Issue by yann-morin-1998** [andyholmes/gnome-shell-extension-gsconnect#493] opened 2019-03-20 15:21 UTC
**Is your feature request related to a problem? Please describe.**
Since WiFi consumes quite some power, it is not unusual for it to be disabled until it is used. Alternatively, the device can be momentarily out of reach (too far from AP, or away with wife/husband...).

Still, it would be interesting to queue up and postpone sending files and/or URLs to that device for when it becomes reachable again: devices comes back in sight, or is powered ON.

One typical use-case is sending URLs to the tablet that is lysing downstairs on the couch with WiFi OFF.

**Describe the solution you'd like**
Add an option for accepting to queue files/URLs/… If option is ON, then when sending a file/URL to an away device, the file/URL is queued (cached) and the actual sending is postponed until the device is accesible again, at wqhich point all queued transfers take place, in the order they wetre queued. If option is OFF, then the behaviour is as it is today (sending is not even possible).

**Describe alternatives you've considered**
None.

Note that is not a protocol feature, but is only purely local to the computer, and thus does not (should not!) break compatibility with KDEConnect.

**Comment by ferdnyc** [comment] 2019-03-24 04:52
@yann-morin-1998 

My take on this is, for _URLs_ I could see it, a queue could be a handy thing. It sort of depends on how KDE Connect would handle being peppered with multiple web links in quick succession, immediately after reconnecting, but I can see the utility in it.

For _files_, this feels like a can of worms just waiting to be opened. Once you can queue file transfers, then at some point someone's going to have a problem and need to _unqueue_ them. (Say they accidentally queued a multi-gigabyte file; or they lined up 10 copies of the same file because they didn't realize they were being enqueued; or their phone battery is super low and they want to enable WiFi, but they can't because they know as soon as they do GSConnect will start firing file transfers at it; or they simply don't need the file on their device anymore because they ended up just dealing with it on their desktop; or...) 

So, now you need queue management. And you also need to deal with the situations where someone queued a file transfer in GSConnect, then deleted the file out from under it before the queue processed. And you need to deal with annoyed _complaints_ from that user, because they assumed that even though they deleted the source file, it would still be transferred because "the file was already in the queue".

If it seems like I'm just trying to come up with problems, guilty as charged. And it was way too easy. As I said, I _absolutely_ see the value of being able to queue up web links for device handoff, even when the device isn't currently online. (Though I think there should be a cap. Maybe 4 or 5 at the **most**.) 

But for delayed file transfers... isn't that what cloud services like Dropbox are for? GSConnect's ability to do quick one-off file tosses is a handy convenience, but it's not a replacement for cloud storage. The immediacy of the transfers kind of feels like a feature, not a bug — purely IMHO.

**Comment by yann-morin-1998** [comment] 2019-03-24 09:08
@ferdnyc Thanks for the feedback! :-)

So, my primary use-case for queuing is indeed with URLs. I would be already pretty happy that this be available.

> depends on how KDE Connect would handle being peppered with multiple web links in quick succession

Well, it could be as simple as sending them with a one-second delaay in-between each URL.

As for files, I see your concerns. I don't think it would be overly complicated to overcome, though.

1. When an item can't be sent right-away, show a popup that request if it should be queued instead (and an option in the settings to never queue, to ask, or to always queue)
2. Queue management: add a _queue_ menu/window with all the queued items, where people could simply dequeue if so they wanted.
3. When a file is queued, it is copied (or hard-linked) to a queueing area, to ensure it is available. (but then one needs a way to cleanup that area...)

> If it seems like I'm just trying to come up with problems, guilty as charged.

Oh don't worry! ;-) It is what I'd expect, though: that you (who knows the stuff better than I) point out the pitfalls in my suggestions. And right you are, because I hadn't thought about the minute details about it.

> for delayed file transfers... isn't that what cloud services like Dropbox are for?

Sorry, no, because they are a _third-party_, require a sustainable upstream bandwidth, and one needs to entrust them with their own data, which is definitely not my case.

>  The immediacy of the transfers kind of feels like a feature, not a bug

I can see that, indeed. TBH, files are my second concern, indeed, and URLs would be what I really need.

**Comment by andyholmes** [comment] 2019-03-24 12:25
I have put a little thought to this, which I why I did mark it as an enhancement, although I'm not 100% on it. There's two larger reasons I'm hesitant about this.

The first is that kdeconnect-android has some known problems dropping packets while connecting. Basically due to loading/enabling plugins in a thread, which isn't always done by the time packets start getting popped off the queue. That's not something we can fix is GSConnect and puts a pretty big wrinkle into making a queuing system viable.

The second is that it will require a lot of refactoring and rethinking about how devices work when they're offline:

* Whether a device action, like `shareFile`, is activatable is subject to a number of conditions:
  * is it connected
  * is it paired
  * is the plugin enabled
  * is the action itself enabled
* the shell code would have to be refactored to show offline devices, which has some UX issues as it could be confusing.
* as @ferdnyc points out we'd need a UI for handling queued actions, checks for moved/missing files and probably want pause/resume/retry functionality

This is all possible, but requires a lot of thinking, planning and code.

**Comment by andyholmes** [comment] 2019-08-12 00:35
Going to close this as it's off the radar for the forseeable future, given the amount of work it would entail. PRs would still be welcome though.

**Closed by andyholmes** 2019-08-12 00:35 UTC
Labels: enhancement, maybe
