### ISSUE TITLE
Window not showing

### ISSUE THREAD

**Issue by grg3** [andyholmes/gnome-shell-extension-gsconnect#486] opened 2019-03-14 13:29 UTC
Suddenly not working after no issues for months - Specifically, must restart extension and windows not showing

Don't know if this is due to recent gnome updates. Suddenly, extension no longer starts at login. Starts after restarting from installed extension page.

Try text window and it shows as transparent - see screenshot.

I am using Arch. I tried current and lts kernel both wayland and xorg. Happens both. I downgraded gtk2libs and that does not affect issue.

Love the extension and I appreciate the work. I realize there is lots of churn in Arch right now and issue may resolve. Just wanted to give my feedback. Thanks!

Cannot get version, but it is latest from gnome shell extensions
Gnome shell 3.30.2

paired with LG G6 
`

**Comment by BERNARDO31P** [comment] 2019-03-14 13:44
+1 GSConnect not working anymore. The settings window doesn't open (It's just white and minimized) and there is a thread which uses a full 100% of a core. So there's something not working anymore.

**Comment by andyholmes** [comment] 2019-03-14 20:42
This is probably another duplicate issue or related to #468, however I'd need logs from `journalctl` or GNOME Logs to know for sure.

**Comment by terencode** [comment] 2019-03-15 14:07
I think the problem is this:
``Extension "gsconnect@andyholmes.github.io" had error: TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)``

**Comment by grg3** [comment] 2019-03-16 18:36
3.32 plus is streaming into Arch. I would like to test fix. but I forget how to install from zip.

**Comment by grg3** [comment] 2019-03-16 18:44
found the instructions

**Comment by andyholmes** [comment] 2019-03-19 00:04
Closing this since I think this should be fixed in v21.

**Closed by andyholmes** 2019-03-19 00:04 UTC
Labels: fixed in master, upstream
