### ISSUE TITLE
gsconnect flooded my syslog created around 10GB of log data

### ISSUE THREAD

**Issue by Mannshoch** [andyholmes/gnome-shell-extension-gsconnect#954] opened 2020-09-18 06:23 UTC
**Describe the bug**

gsconnect filled /var/log/syslog with 10GB of data

**Steps To Reproduce:**
don't know

**Expected behavior**
no system message about running out of diskspace

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.
ther is no texteditor open if I follow -> https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log

syslog (only a little part from it)
```
.......
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc gjs[2576]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
Sep 17 10:44:23 USER-pc gjs[2576]: The offending callback was SourceFunc().
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: == Stack trace for context 0x559958a011a0 ==
Sep 17 10:44:23 USER-pc org.gnome.Shell.Extensions.GSConnect[2576]: #0   559958ab2090 i   /home/USER/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074 (36580828d178 @ 1350)
.....
```

**System Details (please complete the following information):**

 - **GSConnect version:** 41
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Ubuntu 20.04

**GSConnect environment (if applicable):**
At moment gsconnect shows me an unknown device as unpaired. Normally there should be at least three paired devices.

**Comment by andyholmes** [comment] 2020-09-18 19:15
This seems like a duplicate of #891, can you try the latest from `master` to see if it fixes your problem ([Instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip))?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5247706/gsconnect%40andyholmes.github.io.zip)

**Comment by Mannshoch** [comment] 2020-09-19 08:35
thanks!

**Comment by andyholmes** [comment] 2020-09-19 21:54
Closing since the fix has been released in v42.

**Closed by andyholmes** 2020-09-19 21:54 UTC
