### ISSUE TITLE
"Launch Camera" Not Supported

### ISSUE THREAD

**Issue by MatthewGitter** [andyholmes/gnome-shell-extension-gsconnect#543] opened 2019-05-20 22:17 UTC
**Describe the bug**
KDE Connect Android app has a plugin "PhotoPlugin" that shows a "Launch Camera" item in the app's "Plugin settings" list activity, but there is no GUI to it in the GSConnect GNOME API.

**To Reproduce**
1. Go to KDE Connect Android app
2. Tap on 3-dot menu icon; tap on "Plugin settings" item
3. Scroll down to "Launch Camera", defaults to checked, says "Launch the camera app to ease taking and transferring pictures"
4. Go to GSConnect UI in GNOME desktop; click for UI menu; no camera UI

**Expected behavior**
GSConnect UI in GNOME desktop would have "Launch Camera" or "Take Picture" menu item; clicking it would open phone's camera app; when picture taken picture would be transferred to PC's Downloads folder

**System Details (please complete the following information):**
 - GSConnect version: 24
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28.2
 - Distro/Release: Ubuntu 19.04

**GSConnect environment (if applicable):**
 - Paired Device(s):
 - KDE Connect app version: 1.12.7
 - Plugin(s): All defaults bundled with installed distribution

**Additional context**
In GSConnect's [Mobile Settings / Devices / Keyboard Shortcuts / Photo] settings, setting a keyboard shortcut works; typing it executes the plugin on the device correctly. But there's no other UI to execute it on the PC.

**Comment by andyholmes** [comment] 2019-05-20 22:35
Thanks for reporting, this is a duplicate of #494.

**Closed by andyholmes** 2019-05-20 22:35 UTC
Labels: duplicate
