### ISSUE TITLE
[Bug] Duplicate context menu entries appear for a single mobile device

### ISSUE THREAD

**Issue by kabe-inc** [andyholmes/gnome-shell-extension-gsconnect#1019] opened 2020-11-17 18:17 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
Two "Send To Mobile Device" entries appear in nautilus instead of one.

**Steps To Reproduce:**

1. Right click on file in nautilus
2. See error

**Expected behavior**

There to be only one instance, not two.

**Screenshots**

![Screenshot from 2020-11-18 01-03-37](https://user-images.githubusercontent.com/72587902/99429528-b8c9b180-293a-11eb-880f-8cd38ac5541b.png)

**Support Log**
--------------------------------------------------------------------------------
-- Logs begin at Mon 2020-11-02 17:06:40 +07, end at Wed 2020-11-18 01:11:02 +07. --
Nov 18 01:10:11 kernel: rtw_8822ce 0000:01:00.0: timed out to flush queue 1
Nov 18 01:10:23 wpa_supplicant[1025]: nl80211: send_and_recv->nl_recvmsgs failed: -33
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 dbus-daemon[979]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.154' (uid=1000 pid=6909 comm="gjs /home/hugh/.local/share/gnome-shell/extensions" label="unconfined")
Nov 18 01:10:31 systemd[1]: Starting Hostname Service...
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:31 dbus-daemon[979]: [system] Successfully activated service 'org.freedesktop.hostname1'
Nov 18 01:10:31 systemd[1]: Started Hostname Service.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor panelBox is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel-Panel is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor panel is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StBin is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor dashtopanelTaskbar is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StDrawingArea is on because it needs an allocation.
Nov 18 01:10:32 gnome-shell[2283]: Can't update stage views actor StDrawingArea is on because it needs an allocation.
Nov 18 01:10:33 wpa_supplicant[1025]: nl80211: send_and_recv->nl_recvmsgs failed: -33
Nov 18 01:10:35 gnome-shell[2283]: libinput error: client bug: timer event7 debounce short: scheduled expiry is in the past (-10ms), your system is too slow
Nov 18 01:10:35 kernel: rtw_8822ce 0000:01:00.0: timed out to flush queue 2
Nov 18 01:10:37 gjs[6909]: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
Nov 18 01:10:39 kernel: rtw_8822ce 0000:01:00.0: timed out to flush queue 2
Nov 18 01:10:42 wpa_supplicant[1025]: nl80211: send_and_recv->nl_recvmsgs failed: -33
Nov 18 01:10:51 wpa_supplicant[1025]: nl80211: send_and_recv->nl_recvmsgs failed: -33
Nov 18 01:11:01 systemd[1]: systemd-hostnamed.service: Succeeded.
Nov 18 01:11:02 gnome-shell[2283]: *** BUG ***
Nov 18 01:11:02 gnome-shell[2283]: In pixman_region32_init_rect: Invalid rectangle passed
Nov 18 01:11:02 gnome-shell[2283]: Set a breakpoint on '_pixman_log_error' to debug
Nov 18 01:11:02 gnome-shell[2283]: *** BUG ***
Nov 18 01:11:02 gnome-shell[2283]: In pixman_region32_init_rect: Invalid rectangle passed
Nov 18 01:11:02 gnome-shell[2283]: Set a breakpoint on '_pixman_log_error' to debug
Nov 18 01:11:02 gnome-shell[2283]: *** BUG ***
Nov 18 01:11:02 gnome-shell[2283]: In pixman_region32_init_rect: Invalid rectangle passed
Nov 18 01:11:02 gnome-shell[2283]: Set a breakpoint on '_pixman_log_error' to debug
Nov 18 01:11:02 gnome-shell[2283]: *** BUG ***
Nov 18 01:11:02 gnome-shell[2283]: In pixman_region32_init_rect: Invalid rectangle passed
Nov 18 01:11:02 gnome-shell[2283]: Set a breakpoint on '_pixman_log_error' to debug```

```

**System Details (please complete the following information):**

GSConnect: 44 (user)
GJS:       16601
Session:   wayland
OS:        Pop!_OS 20.10
Installed via APT/GNOME Extensions website
GNOME v3.38.1
KDE Connect Android version 1.15.1
Paired devices - Oneplus 6 (Android v10)

**Comment by ferdnyc** [comment] 2020-11-19 16:33
@kabe-inc Sorry for the delay getting back to you.

Can you post the `ls -l` contents of these two paths?
```sh
ls -l $HOME/.local/share/nautilus-python/extensions
ls -l /usr/share/nautilus-python/extensions
```

Duplicate context menu entries is _usually_ caused by multiple copies of the extension being loaded, possibly under different names or from different paths.

**Comment by kabe-inc** [comment] 2020-11-20 04:22
Aha, I see. Here' the output below:

ls -l $HOME/.local/share/nautilus-python/extensions:
```
total 8
lrwxrwxrwx 1 hugh hugh   99 Nov  3 12:08 nautilus-gsconnect.py -> /home/hugh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/nautilus-gsconnect.py
drwxrwxr-x 2 hugh hugh 4096 Nov  3 12:09 __pycache__
```

ls -l /usr/share/nautilus-python/extensions:

```
total 20
-rw-r--r-- 1 root root 4216 Jan 10  2019 nautilus-gsconnect.py
-rw-r--r-- 1 root root 5316 Apr 22  2019 open-tilix.py
drwxr-xr-x 2 root root 4096 Nov 18 16:58 __pycache__

```
Does that mean I have two active copies? If so, which one should I remove/disable?

**Comment by ferdnyc** [comment] 2020-11-22 01:22
Yup, that was exactly it. The copy in `/usr/share/...` was interfering with your local GSConnect install.

That file probably comes from a distro package, I'd check whether there's a `gnome-shell-extension-gsconnect` package or the like installed on the system in `apt`. There shouldn't be, when running GSConnect from your `$HOME/.local/share/gnome-shell/extensions/` dir. 

Redundant distro packages of GSConnect don't cause quite as much trouble as having _`kdeconnect`_ installed (which just breaks GSConnect completely), but as you've seen they can still cause some minor issues.

I'm going to close this issue as solved. But feel free to reopen, or file a new issue, if you encounter any more of the same or different problems (respectively).

**Closed by ferdnyc** 2020-11-22 01:22 UTC
Labels: needs info
