### ISSUE TITLE
Ubuntu 20.04 . Integration error with Gnome.

### ISSUE THREAD

**Issue by opsaaspo** [andyholmes/gnome-shell-extension-gsconnect#906] opened 2020-08-07 10:09 UTC
**Describe the bug**
I've installed the latest ubuntu version 20.04.  Update GSConnect from https://extensions.gnome.org/local/ .  After update the extension has status "Error"
The bugs are:
1. The computer doesn't show any mobile actions (notifications, telephony)
2. Menu doesn't contain GSConnect

**Steps To Reproduce:**

1. Install GSConnect from https://extensions.gnome.org/local/
2. Integrate mobile phone and GSConnect
3. Call on phone\Send SMS\etc.

**Expected behavior**
1. Show mobile actions - notifications, telephony
2. Menu contains GSConnect

**Screenshots**

**Support Log**
The log is:
```
GSConnect Version: 39
GSConnect Install: user
GJS: 16403
XDG_SESSION_TYPE: wayland
GDMSESSION: ubuntu-wayland
--------------------------------------------------------------------------------
-- Logs begin at Tue 2020-05-12 20:00:57 UTC+3, end at Fri 2020-08-07 12:59:24 UTC+3. --
авг 07 12:59:14 gnome-shell[4043]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1600008 specified for 0x1600034.
авг 07 12:59:24 gnome-shell[4043]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
                                      notify@resource:///org/gnome/shell/ui/messageTray.js:865:23
                                      addNotification@/home/op/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:241:18
                                      AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:771:16
                                      _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
                                      _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
авг 07 12:59:24 gnome-shell[4043]: JS ERROR: Error: No signal 'acknowledged-changed' on object 'Gjs_ui_notificationDaemon_GtkNotificationDaemonNotification'
                                      pushNotification@/home/op/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:257:22
                                      showNotification@resource:///org/gnome/shell/ui/messageTray.js:854:14
                                      notify@resource:///org/gnome/shell/ui/messageTray.js:869:22
                                      addNotification@/home/op/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:241:18
                                      AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:771:16
                                      _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
                                      _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
```

**System Details (please complete the following information):**

 - **GSConnect version:** [39]
   - **Installed from:** [GNOME Extensions Website ]
 - **GNOME/Shell version:** [3.36.3]
 - **Distro/Release:** [Ubuntu 20.04.1 LTS]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [Galaxy S8+]
 - **KDE Connect app version:** [?]
 - **Plugin(s):** [?]

**Additional Notes:**

The button "Configure this extension" is working.
The mobile client is working too.

**Comment by andyholmes** [comment] 2020-08-07 17:29
You'll just have to restart GNOME Shell after upgrading the extension.

duplicate of #817

**Closed by andyholmes** 2020-08-07 17:29 UTC
