### ISSUE TITLE
[DISCUSSION] Failed mount operations

### ISSUE THREAD

**Issue by mj0123456789** [andyholmes/gnome-shell-extension-gsconnect#578] opened 2019-08-03 13:06 UTC
Hello all, Hi Andy,

GSConnect first installation on my Ubuntu was stunning and really wonderful. 
Great job thanks a lot Andy!

I have a problem I don't know how to fix it and why it happens.
Everything was ok before I tried to change some parameters on my ufw.

GSConnect (Ubuntu 19.04 GNOME 3.32.1) and KDE (Smartphone Android Huawei P20 Pro, EMUI 9.0.0.270) works perfectly apart from the Mount function.

I have uninstalled and reinstalled both sides once yet.

Here is a copy of the log (sorry for the French in it) :

```
août 01 13:51:41 org.gnome.Shell.Extensions.GSConnect[2623]: [/service/protocol/core.js:receive/<:177]: Smartphone: {
                                                                "id": 1234567890123,
                                                                "type": "kdeconnect.sftp",
                                                                "body": {
                                                                  "ip": "192.168.xx.xx",
                                                                  "port": 1739,
                                                                  "user": "XXXXXXXXXXXXX",
                                                                  "password": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                                                                  "path": "/",
                                                                  "multiPaths": [
                                                                    "/Smartphone"
                                                                  ],
                                                                  "pathNames": [
                                                                    "Smartphone"
                                                                  ]
                                                                }
                                                              }
août 01 13:51:41 gjs[2623]: JS ERROR: Smartphone (sftp): [b]Gio.IOErrorEnum: Connexion refusée par le serveur[/b]
                             _mount/</<@/home/utilisateur1/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:160:33
                             @/home/utilisateur1/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
août 01 13:51:41 org.gnome.Shell.Extensions.GSConnect[2623]: [/service/plugins/sftp.js:_remove_host:272]: "removed host key for [192.168.xx.xx]:1739"
```

On the ufw, I allow everything to and from the smartphone IP address and nothing changes if I temporarily disable it.

May be a very simple trick I did not think about.
Any idea?

Regards,

Marc

**Comment by mj0123456789** [comment] 2019-08-04 18:39
Hello all, Andy,

I promise it's not a joke: My Smartphone is back in my Nautilus without taking any action relative to the problem neither on my Linux nor on the smartphone !!!

I really don't understand what could explain the automatic fix of my problem.

Cheers,

Marc

**Comment by ferdnyc** [comment] 2019-08-04 19:51
Hmm, I got email of an update to this that's since disappeared, does that mean the issue is _not_ fixed after all? If so, was it _briefly_ fixed or something? That might be useful information.

**Comment by mj0123456789** [comment] 2019-08-10 21:40
Hi, Deleted since I confused the smartphone's media with an SD card and thought it was running.
FYI, have reinstalled a brand new Ubuntu, & GSConnect, and cannot mount the smartphone with the same log messages.
Maybe a misconfig on my Smartphone?
Regards,
Marc

**Comment by ferdnyc** [comment] 2019-08-10 22:38
@mj0123456789 Gotcha, well that's too bad.

> Maybe a misconfig on my Smartphone?

It doesn't _seem_ like it, the logged packet shows that there's a path shared on the phone and the app obviously _thinks_ it can provide the SFTP service, plus it's communicating just fine for other services you said, so... I'm not sure why this one in particular would be failing.

After you make a failed Mount request to the phone, what happens if you try to manually connect to the port(s)? 

(Here are some commands to try, along with their output on my Fedora 30 system. Fedora packages `nmap-ncat` as its `netcat` replacement, not sure if Ubuntu does the same, but these commands should work with `netcat` as well.)

```console
$ # Test TCP connections
$ for p in $(seq 1739 1764); do nc -z -v $PHONE_IP $p; done
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1739.
Ncat: 0 bytes sent, 0 bytes received in 0.12 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1740.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1741.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1742.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1743.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1744.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1745.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1747.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1748.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1749.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1750.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1752.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1755.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1756.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.12.106:1757.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection refused.
```
You could also test UDP connections by adding a `-u` to the command, i.e.:
```
for p in $(seq 1739 1764); do nc -u -z -v $PHONE_IP $p; done
```

I tested this _while_ my phone's share was mounted (via port `1757`), and that was the highest port for which a TCP connection attempt succeeded, which I suppose makes some sense.

For this _particular_ situation, I'd actually be more interested in the results **after** GSConnect has been communicating with your phone for a while via other services that connected successfully, vs. the previous just-restarted debug log, where the SFTP connection appears to have been the first attempt (as indicated by the port number being 1739).

Beyond that... well, we'll see what the results are. Or, @andyholmes may have other ideas.

**Comment by andyholmes** [comment] 2019-08-12 00:47
Not sure, all I can say is you need ports 1716-1764 open for TCP and UDP. Your best bet is to undo the changes you made to ufw. :)

**Comment by mj0123456789** [comment] 2019-08-13 19:20
Hello,
The results from the 
`$ for p in $(seq 1739 1764); do nc -z -v 192.168.1.65 $p; done` are confusing since they vary.
Nota: ufw disabled for the tests.
The 1st time I did it:
`marcj0711@Marco-Desktop:~$ for p in $(seq 1739 1764); do nc -z -v 192.168.1.65 $p; done
Connection to 192.168.1.65 1739 port [tcp/*] succeeded!
Connection to 192.168.1.65 1740 port [tcp/*] succeeded!
Connection to 192.168.1.65 1741 port [tcp/*] succeeded!
Connection to 192.168.1.65 1742 port [tcp/*] succeeded!
Connection to 192.168.1.65 1743 port [tcp/*] succeeded!
nc: connect to 192.168.1.65 port 1744 (tcp) failed: Connection refused
same up to port 1764`
The 2nd time I do (without doing anything else in between) : 
`marcj0711@Marco-Desktop:~$ for p in $(seq 1739 1764); do nc -z -v 192.168.1.65 $p; done
nc: connect to 192.168.1.65 port 1739 (tcp) failed: Connection refused
Connection to 192.168.1.65 1740 port [tcp/*] succeeded!
Connection to 192.168.1.65 1741 port [tcp/*] succeeded!
nc: connect to 192.168.1.65 port 1742 (tcp) failed: Connection refused
same up to port 1764`
Then all times I try I get the same as the last one. 
Then I make the phone ring and try to mount again.
Then I get repetitively : 
`marcj0711@Marco-Desktop:~$ for p in $(seq 1739 1764); do nc -z -v 192.168.1.65 $p; done
Connection to 192.168.1.65 1739 port [tcp/*] succeeded!
Connection to 192.168.1.65 1740 port [tcp/*] succeeded!
Connection to 192.168.1.65 1741 port [tcp/*] succeeded!
nc: connect to 192.168.1.65 port 1742 (tcp) failed: Connection refused
same up to port 1764`
But still no positive result for the mount request.
Regards,
Marc

**Comment by ferdnyc** [comment] 2019-08-13 22:22
Hmm. That's sort of interesting, my results are the same every time. I also get **far** more successful connections than you do, the three runs I did just now only showed 7 closed ports.

That may come down to Android version, my phone is still running Android 7. Perhaps later versions use a more aggressive firewall.

Still, clearly you _can_ connect to several ports on the phone, so the fact that GSConnect is logging "connection refused" for the port that the phone _advertised_ as being open and ready to mount is extremely odd. I'm kind of stuck for ideas about how to solve it, though.

**Comment by mj0123456789** [comment] 2019-08-14 09:11
Hi @ferdnyc 
Thanks for you attention and comments.
Trying this morning gives other combinations of successes... But still no success in mounting the device.
Cheers,
Marc

**Comment by andyholmes** [comment] 2019-08-21 00:54
Have you tried force closing the app in Android?

**Comment by mj0123456789** [comment] 2019-08-26 16:09
Hi all, 
Can't really explain (since I don't understand) why it works now but it does.
Cheers,
Marc

**Comment by csaba215** [comment] 2019-09-10 15:46
I am also having the same issue can't mount storage but can send files.

**Comment by csaba215** [comment] 2019-09-10 16:36
Somehow it solved itself ... When I tried to connect manually it failed with signature mismatch. Manually removing the mismatch didn't solve it, but allowed me to connect sftp command and was able to list directories. Rebuilding the same version from git and installing fixed it somehow.

**Comment by stuaxo** [comment] 2019-10-03 22:48
Hi,
   I've hit the same problem, how do I get some log info to try and work out why it's not working ?
It would be good if GSConnect could at least give some feedback when this doesn't work, instead I click "mount" and then nothing happens with no feedback.

S

**Comment by andyholmes** [comment] 2019-10-04 19:31
@stuaxo There is a built-in function for gathering debug information, described in the wiki as [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

There are a number of reasons why mounting the remote device can fail, and not all of them are due to GSConnect failing or directly related to mounting itself. Some examples:

* the SFTP server may fail to start on the remote device
* the remote device may simply not respond to a request to mount
* the remote SFTP plugin may be disabled
* the connection may simply time out

In the past we received complaints about GSConnect printing too many errors to the log and showing too many notifications, so many messages are now simply muted while others are only printed when debug mode is enabled. A number of users had left debug mode enabled accidentally, leading them to believe GSConnect was leaking private information, so eventually the option to enable debug mode manually was removed. :man_shrugging:

**Comment by stuaxo** [comment] 2019-10-04 22:53
Feedback wise, I don't know where the log is, but it would be useful if the user clicks the mount option if there was some sort of notification that mount failed (+ maybe even a reason, ie user needs to install some package).

**Comment by andyholmes** [comment] 2019-10-04 23:23
As I said, virtually nothing will be printed to the log, unless you use the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) function specifically created for this.

There are no packages that need to be installed to mount devices, but the most common reason mounting "fails" is because the remote device simply doesn't respond at all. The process works like this:

1) We send a packet to the device requesting information necessary to attempt mounting
2) Device responds with this information
3) We attempt to open an SFTP connection
4) The connection is either accepted or fails because
   * the connection times out
   * the connection is refused
   * the connection is not allowed by a firewall or router
   * the remote SFTP server fails to start
   * the connection is accepted but the remote host key has changed

If (2) never happens, we will never know why or know when to reasonably assume it's because of an error, since we will never get an error and there is no timeout period for the request. This happens pretty frequently, sometimes just because your phone's screen is off.

The first four possible errors are not related to or fixable by GSConnect and the first three of those happen so regularly in all network applications you will be swamped with error messages. So much so it's possible we could fill up your hard drive with log messages.

The last case actually happens quite frequently as a result of users pairing and unpairing or re-installing the Android app. However in the rare case that it's not, it is a sign that you are the subject of a man-in-the-middle attack or an attacker is trying to otherwise impersonate your device, so the sanest course of action is to wipe all remote host keys and close the connection.

The truth is, KDE Connect is probably the least reliable way to mount a device over SFTP and keep it mounted, it just happens to be convenient.

**Comment by stuaxo** [comment] 2019-10-04 23:46
> The truth is, KDE Connect is probably the least reliable way to mount a device over SFTP and keep it mounted, it just happens to be convenient.

Heh, convenience is a big pull, it would be nice to get some kind of user facing notification (popup or whatever) after some timeout (say 3-5 seconds?) that mounting was unsuccessful.

I'm only talking about a user facing notification/popup for user-initiated actions - i.e. actually clicking mount, and it was unsuccessful after say 3 seconds.

Otherwise, if you're a new user, then you won't know if you are just doing something wrong and can't find the mount or that it hasn't worked without a bit more digging.

**Comment by andyholmes** [comment] 2019-10-05 02:09
Sorry, I just don't know how to explain it any better. In most cases there just is no error to display. In every other case they are so frequent that your screen will be covered in notifications.

If you still think this a good idea I'll do it, but stable releases are iften 4-6 months apart so if you change your mind it will be awhile before that changes.

**Comment by ferdnyc** [comment] 2019-10-05 04:14
> If you still think this a good idea I'll do it, but stable releases are often 4-6 months apart so if you change your mind it will be awhile before that changes.

Since this affects everyone, I'd urge caution on that. As you say, it could work out... badly.

Currently, the Mount functionality silently makes the SFTP connection, then updates the user menu to display a list of shared directories, which can be clicked on to open them in the file manager. Because the menu dismisses itself in between, there's limited utility in that, honestly; it's just extra clicks.

What if, as a compromise, Mount itself actually launched a file manager window to the device root? If the mount is successful the user will see a folder for each shared location on the device. If it's not, the file manager can deal with alerting the user to the mount's inaccessibility.

**Comment by andyholmes** [comment] 2019-10-05 07:45
> What if, as a compromise, Mount itself actually launched a file manager window to the device root?

I was considering doing that at the same time as when we dropped `sshfs`, but by that time the Android app had switched to SAF. Since you can now specify multiple mount points, which don't have to share a common exposed root, I'm not sure there is such a thing as a guaranteed device root any more. I think that's true anyways; I'll double check tomorrow, time for sleep :sleeping:

**Comment by ferdnyc** [comment] 2019-10-05 09:54
> Since you can now specify multiple mount points, which don't have to share a common exposed root, I'm not sure there is such a thing as a guaranteed device root any more.

At least with current KDE Connect, that doesn't appear to be an issue. No matter where the shared paths are on the remote device, they're exposed as top-level directories in the SFTP filesystem. 

Just to double-check, I shared a third, non-top-level path from my device, and:
```console
$ gio list sftp://192.168.12.106:1744/
Pictures
Android_data_com.dropbox.android_files_u########_scratch_Comics
Download
```

The middle one is `/sdcard/Android/data/com.dropbox.android/files/u########/scratch/Comics/` on the device Unwieldy, but useful!

**Comment by andyholmes** [comment] 2019-10-08 22:36
So there's a snag here that didn't occur to me. Generally, once we successfully mount the SFTP volume, we go through all the active mounts in the global `GVolumeMonitor` until we find one that matches the provided `ip:port` sent by the device. We then connect to `GMount::unmounted` so we know if the device is unmounted either remotely, in Nautilus or some other gvfs process. If device manages to disconnect without the SFTP volume disconnecting (which can happen), [we have a contingency for that](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/plugins/sftp.js#L180-L183) and we still connect to the `::unmounted` signal.

However, it seems like there is some case where we're just not getting that signal. In that case we kind of need the dropdown menu otherwise we can't manually unmount the device, which is necessary for GSConnect to know it can attempt remounting. This behaviour might be new to GNOME 3.34 though, since I don't recall it happening last release.

The other gotcha, is still that the most common reason the device "fails" to mount is that the device simply doesn't respond to our request for the connection information (`ip:port`). In this case, we'll never get an error message from KDE Connect and since we don't have the information necessary to attempt mounting, we can't leave it to Nautilus to get us an error either. We could show an error notification after a timeout, but actually isn't any timeout for these requests (or any packets for that matter) and the device can really take as long as it wants to respond. So we could show an error, only to have the user pick up their phone and have it suddenly mount.

So, I'm still unsure what the best option here is, but since I really don't use this feature I don't exactly have a vested interest or particularly care :D

**Comment by stuaxo** [comment] 2019-10-08 23:26
In my case I must have been doing something silly, I missed a notification that pops up when the phone connects to gnome shell.

```
htc:  SFTP
No storage locations configured
```

Still, the GSConnect app has a mount option I can click on inspite of that (that doesn't do anything).

**Comment by ferdnyc** [comment] 2019-10-09 02:04
> Still, the GSConnect app has a mount option I can click on inspite of that (that doesn't do anything).

Yeah, until GSConnect attempts to mount the remote device's files, there's really no way for it to _know_ that there are no shares available. If the Filesystem Expose plugin is enabled on the device, then it advertises filesystem mounts as one of its available capabilities, and GSConnect takes it at its word.

...Seems like GSConnect should be able to alert the user to the no-shared-locations situation _**after**_ it attempts to mount the device, though, no @andyholmes ? If not, I'd say that's a deficiency in the kde-connect protocol, that it doesn't provide an actionable response to the request for a service it _advertised_ as being available.

**Comment by andyholmes** [comment] 2019-10-09 06:37
> If the Filesystem Expose plugin is enabled on the device, then it advertises filesystem mounts as one of its available capabilities, and GSConnect takes it at its word.

Actually, it's worse than that. We realized that using `incomingCapabilities` or `outgoingCapabilities` as an indication that a remote device has a plugin loaded, or that a local device should load a plugin is a chicken-egg problem. In fact all a capability means is that the device may, possibly handle/provide a packet, not whether it actually will or what will happen when it does.

We had some talk about adding a third field, which would basically correspond to GSConnect's (`supported-plugins` - `disabled-plugins`) settings, but no one has got around to actually doing it.

> Seems like GSConnect should be able to alert the user to the no-shared-locations situation after it attempts to mount the device, though...

That's basically what the (relatively) new `errorMessage` field of the `kdeconnect.sftp` packet is for. Currently, I think that's actually the only error message we can receive. Probably one of two things is happening, but it's definitely related to auto-mounting:

* The notification is being sent by GSConnect when the user logs in, somehow before the notification server is ready to receive notifications. The notification server is a part of gnome-shell, so I don't think that's likely given that extensions are one of the last things to be loaded, but I could be wrong.

* The first notification is shown (marked urgent, so won't ever auto-hide or dismiss), but is overridden by some other notification, possibly urgent also. Once that happens, the second time the error notification is sent, it's not shown but merely replaces the original that somehow got hidden.

Hard to say for sure, because I'm not sure what the behaviour actually looked like to @stuaxo. Last week before that Android bug was fixed, I was definitely getting them every time I restarted GSConnect and they were super annoying. So I can't say that's reproducible for me.

**Comment by andyholmes** [comment] 2019-11-27 07:22
Going to close this one down, since the original bug seemed to be a storage location not being selected and there's no good way to know what to do if the phone just doesn't respond. All other errors should be notified by the Android app.

**Closed by andyholmes** 2019-11-27 07:22 UTC
Labels: UX
