### ISSUE TITLE
can't convert undefined to object

### ISSUE THREAD

**Issue by ury2000** [andyholmes/gnome-shell-extension-gsconnect#972] opened 2020-09-21 12:25 UTC
```
GSConnect: 42 (user)
GJS:       16403
Session:   x11
OS:        Pop!_OS 20.04 LTS

_addSubmenu@/home/pop/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:386:44
async*_onMountAdded@/home/pop/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:137:14
@/home/pop/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2020-09-21 19:15
Thanks for reporting, duplicate of #967, fixed in 79b0a88.

**Closed by andyholmes** 2020-09-21 19:15 UTC
