### ISSUE TITLE
System hangs when trying to access sshfs folders

### ISSUE THREAD

**Issue by stark-dev** [andyholmes/gnome-shell-extension-gsconnect#66] opened 2018-03-18 15:58 UTC
Hi! Sorry to disturb again. I have a problem related to sshfs mounting since a few months, but I wanted to investigate before opening a new issue. Unfortunately, I'm here :stuck_out_tongue:
First of all, I'm running Arch Linux with Gnome 3.26. I've installed the modified version of this extension which comes from #26 (though that fix is now available in upstream). 
The problem is the following: when I enable "Browse Files" toggle, all folders are shown in the menu as expected. However, when I click on it, the whole system hangs for a while, and once it works again there is no folder mounted. 
I checked previous bugs opened and already tried solution in #52, but here seems different. 

Here's the log from debug shell

```
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: _prepare()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: unmount()
JS LOG: Sftp: Timeout waiting for prompt
``` 

Between `_prepare` and `unmount`there are about 30 seconds of freeze. I tried to connect using `sshfs` manually, with all options specified in `service/plugins/sftp.js`:

```
sshfs -o IdentityFile=/home/stark/.config/gsconnect/private.pem -o HostKeyAlgorithms=ssh-dss -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o uid=1000 -o gid=100 -o password_stdin -F /dev/null kdeconnect@192.168.1.247:/storage/emulated/0 /run/user/1000/gsconnect/1a209975927f6c1c -p 1739
```
I noticed the `password_stdin` option, hence I copied password from debug log and pasted into shell. It actually works, I can access all files without problems. Could it be that there is something on my pc which is redirecting `stdin`, preventing the extension from reading password?

I also tried automounting when enabling "Browse File". The system doesn't hang, but log is the same as before. Checking with `mount | grep gsconnect` shows the device for the usual 30 seconds, during which I can't accesss files however.

Thanks for your help, if you need any other info tell me.

Mauro

**Comment by andyholmes** [comment] 2018-03-19 22:40
I'm not sure what is causing this, there is sometimes a hang if the device screen is turned off, but if it works from a terminal I'm not sure.

    JS LOG: [gsconnect@andyholmes.github.io]: SFTP: handlePacket()
    JS LOG: [gsconnect@andyholmes.github.io]: SFTP: _prepare()
    JS LOG: [gsconnect@andyholmes.github.io]: SFTP: unmount()
    JS LOG: Sftp: Timeout waiting for prompt

This last message shouldn't be printed, since that's one of the stderr messages GSConnect knows to watch out for.

There shouldn't really be anything in the local environment that could affect `stdin`, since GSConnect writes the password directly to the process and not through a shell. Is there any relevant output in the debug log for Gnome Shell that might give more clues?

**Comment by stark-dev** [comment] 2018-03-20 00:31
Okay, maybe I missed something important in last message, the IP is different from the one I used manually. Here's the full log:

```
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(sftp, true)
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: mount()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1a209975927f6c1c, {"id":0,"type":"kdeconnect.sftp.request","body":{"startBrowsing":true}})
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1a209975927f6c1c)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1521503137456,"type":"kdeconnect.sftp","body":{"ip":"10.0.2.15","port":1739,"user":"kdeconnect","password":"PNtrtCOWLwrd6YtomDWf54a8j61d","path":"/storage/emulated/0","multiPaths":["/storage/uicc0","/storage/emulated/0","/storage/emulated/0/DCIM/Camera"],"pathNames":["SD card","Internal storage","Camera pictures(Internal storage)"]}}
JS LOG: Received from 'Xiaomi'
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: _prepare()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: unmount()
JS LOG: Sftp: Timeout waiting for prompt
```
First time I guessed that `10.0.2.15` was used to avoid binding to a specific IP address, but now I'm not sure of that.
In fact I tried to manually set my device IP in `service/plugins/sftp.js` (line 103) and now it works!
Should `packet.body.ip` return the actual IP address of the device?

Thanks,

Mauro

**Comment by andyholmes** [comment] 2018-03-20 01:04
Yes, that's definitely incorrect. I think I can fix this in GSConnect by just grabbing the IP address from the active TLS connection, but I'm going to report this on the KDE Connect bug tracker since this is a regression of a bug that fixed in the past.

Could you tell me what version of Android you're running for the bug report I'm filing?

**Closed** 2018-03-20 02:28 UTC

**Comment by stark-dev** [comment] 2018-03-20 09:57
Hi! Thanks a lot for your answer. I tried the build, but now when open extension settings, it shows this error :/

```
There was an error loading the preferences dialogue for GSConnect:

TypeError: metadata is undefined

Stack trace:
  Stack<._addDaemon@/home/stark/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:296:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Stack<._init@/home/stark/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:262:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  PrefsWidget<._init@/home/stark/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:102:29
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/stark/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
```
If it is a regression from kdeconnect you can revert changes and I'll wait for app fix, no worries ;)

Thanks again!

Mauro

**Comment by stark-dev** [comment] 2018-03-20 10:26
Ok, I downloaded master from git and tried to build locally. Everything works fine, I don't know if there was something missing in the previous build, but should be fine now ;) thanks again!

Mauro
