### ISSUE TITLE
Enabling or Disabling GSConnect is Disabled in Extensions as well as gnome-tweak-tool

### ISSUE THREAD

**Issue by guerrilla** [andyholmes/gnome-shell-extension-gsconnect#783] opened 2020-03-09 19:42 UTC
**Describe the bug**

So, I just updated to gnome shell 3.36.0 and GSConnect 33 and it stopped working. I went to GNOME Extensions and noticed that it's enable/disable button is disabled. Clicking on the Preferences doesnt show any devices but rather "Waiting for device..." in grey. The enable/disable button is also disabled in gnome-tweak-tools. I have used "dconf read /org/gnome/shell/disable-user-extensions" to check that it is set to false and it was. On a hunch, I wrote it to false again and suddely GSConnect started working (tested from android phones) but the enable/disable buttons in both Extensions and gnome-tweak-tool are both still disabled. Clicking on 'Preferences' now tells us that the device is ready and it immediately found all the devices connected to it but it didn't before.

**Steps To Reproduce:**

1. Go to 'Extensions'
2. Scroll down to 'GSConnect'
4. See that it can't be enable or disabled (button is grey)

**Expected behavior**

I would expect to be able to enable or disable GSConnect from Extensions or gnome-tweak-tool. I would not expect wiriting a value of 'false' to "/org/gnome/shell/disable-user-extensions" via dconf to do anything when that value is already set to false. I would also expect that if it is set to false that the enable/disable button would work in the first place.

**Screenshots**
I\m using the default theme. 

![image](https://user-images.githubusercontent.com/1262389/76250578-e572e880-6245-11ea-98cc-40335bd6d61b.png)

**Support Log**

GSConnect Version: 33
GSConnect Install: user
GJS: 16400
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Sun 2020-02-02 16:32:43 CET, end at Mon 2020-03-09 20:37:20 CET. --
Mar 09 20:37:01 tracker-store[5914]: OK
Mar 09 20:37:01 systemd[1944]: tracker-store.service: Succeeded.
Mar 09 20:37:02 systemd[1]: systemd-timedated.service: Succeeded.
Mar 09 20:37:02 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timedated comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 09 20:37:02 kernel: audit: type=1131 audit(1583782622.060:146): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-timedated comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 09 20:37:15 systemd[1]: systemd-hostnamed.service: Succeeded.
Mar 09 20:37:15 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 09 20:37:15 kernel: audit: type=1131 audit(1583782635.333:147): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 09 20:37:20 dbus-daemon[417]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.728' (uid=1000 pid=6032 comm="gjs /home/media/.local/share/gnome-shell/extension")
Mar 09 20:37:20 systemd[1]: Starting Hostname Service...
Mar 09 20:37:20 dbus-daemon[417]: [system] Successfully activated service 'org.freedesktop.hostname1'
Mar 09 20:37:20 systemd[1]: Started Hostname Service.
Mar 09 20:37:20 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 09 20:37:20 kernel: audit: type=1130 audit(1583782640.953:148): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

```

**System Details (please complete the following information):**

 - **GSConnect version:** 33
   - **Installed from:** extensions.gnome.org via firefox (and also tried reinstalling with epiphany- no difference)
 - **GNOME/Shell version:** 3.36.0
 - **Distro/Release:** Arch Linux updated 2020-03-09 19:000 Central European Time.

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy Xcover 3, Moto G4 Play, motorola one macro
 - **KDE Connect app version:** 1.13.7 (on all)
 - **Plugin(s):** none

**Additional Notes:**

**Comment by andyholmes** [comment] 2020-03-09 20:28
v33 does not support GNOME 3.36.

duplicate of #750

**Closed by andyholmes** 2020-03-09 20:28 UTC
