### ISSUE TITLE
SD-Card empty

### ISSUE THREAD

**Issue by mikail0** [andyholmes/gnome-shell-extension-gsconnect#835] opened 2020-04-29 14:33 UTC
**Describe the bug**

I can not see any files in my SD-Card folder. Internal storage works.
I have Android 8.

**Steps To Reproduce:**
1. Add SD-Card as a storage location in the KDE Connect app.
2. Mount in on the GSConnect extension.
3. Open the SD-Card folder

**Support Log**

It doesnt give me anything regarding gsconnect.

**System Details (please complete the following information):**

 - **GSConnect version:** 37
   - **Installed from:**  GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Arch
**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S7 Edge
 - **KDE Connect app version:** 1.14.2

**Comment by andyholmes** [comment] 2020-04-29 19:33
This sounds like it's probably a problem in kdeconnect-android, especially if there are no errors in GSConnect.

Does this work if you mount it manually with `sshfs`? The host/port to mount it should be available in the mount properties or even the tooltip.

**Comment by ferdnyc** [comment] 2020-04-30 00:39
My current phone has so much internal storage, I had to check the manual to be sure whether it even _supports_ microSD expansion.

It does, so I popped in one of my old cards.

Sharing the SD Card works for me, on my Galaxy Note 8 with Android 9. It's handled exactly the same as the internal storage.

One question: You say you added "SD-Card" as a shared location, @mikail0, but did it actually show up that way? When I selected my card as a shared storage location in KDE Connect, it was shared using the name of the filesystem on the card (the default `Exxx-xxxx` code) both as the mount location and the share name.

So, in my Filesystem expose settings list I now have two items:

> **Exxx-xxxx**
> Exxx-xxxx:
> 
> **primary**
> primary:

And after mounting via GSConnect, Nautilus is able to browse both of those folders. Was the card shared the same way for you?

**Comment by mikail0** [comment] 2020-05-01 09:51
@ferdnyc 
Yes, it showed up the same way.

I am not sure if I my try to mount it is correct:
`sudo sshfs sftp:host=192.168.0.205,port=1739/primary /mnt/phone`
It gives me
`read: Connection reset by peer`

**Comment by ferdnyc** [comment] 2020-05-01 09:59
Hmm. The first time I tried to test, Mount actually wasn't working at all. I had to `kill -HUP` the `daemon.js` process to unconfuse it. Then everything worked.

But it'd be _extremely weird_ if you could use only ONE of the two shares, but not the other, due to any sort of issue with the GSConnect `daemon.js`, so I have very little confidence that your issue is anything like that or would be fixed the same way.

Rather than mounting the share, one option is to test by exploring it interactively:
```sh
$ sftp -P $PORTNUM kdeconnect@$DEVICE_IP
Connected to $DEVICE_IP.
sftp> ls
Exxx-xxxx  primary
sftp> ls Exxx-xxxx
Exxx-xxxx/Android   Exxx-xxxx/Backup
(etc...)
```

**Comment by mikail0** [comment] 2020-05-01 10:07
When I try `ls` on that sd-card folder, it gives me the error
`Couldn't read directory: Failure`

I have to say that my SD-card is encrypted, but my phone is too.
I think that could be the issue, because I have read that when I encrypt the SD-card with my phone and the phone breaks, I can no longer access that SD-card. So I think that I can access that SD-card only with my phone.

**Comment by ferdnyc** [comment] 2020-05-01 10:54
That sounds like a real possibility, yeah. It could be that KDE Connect doesn't support encrypted filesystems.

You _might_ want to check the KDE bugzilla for existing reports of this issue, and/or file one, just in case it's **not** an intentional/known limitation and merely a bug. Perhaps there's some way they can add encrypted mount support to the app. (Most likely not, though, if the restriction is indeed intended as a security measure, which sounds likely to me as well.)

It's odd that it would allow the encrypted mount to be published as a broken share, though, instead of refusing to create that share in the first place and displaying some sort of error message instead. That's the only reason I'm less than 100% sure the current behavior is intentional and not a bug.

**Comment by mikail0** [comment] 2020-05-01 11:27
I have tried it with an unencrypted SD-Card and that is empty, too.

I will file a bug at KDE bugzilla.

**Comment by ferdnyc** [comment] 2020-05-01 14:08
Ah, yeah that's definitely odd then. Could be something on the device is playing security-nanny. Or maybe they're just not establishing the right permissions.

The weird thing, though, is that I've done this in Android 9 on my current Note 8, _and_ I've done it in Android 7 on my previous GxS6. Seems odd the S7 Edge would be different from two very similar devices that basically bookended it — unless there's some sort of carrier tweak gumming up the works, which I suppose is a possibility.

...Come to think of it, though, I just remembered a friend who had an S7 _Edge_, specifically, reporting a lot of unexpected deviations from even the other devices in the Galaxy product line at the time. It was never quite clear to him/us exactly what Samsung was doing there. `¯\_(ツ)_/¯`

**Comment by mikail0** [comment] 2020-05-01 15:12
S6 Edge was the first one with Edge.

**Comment by nicofooo** [comment] 2020-06-26 16:10
I have the same problem with GSConnect.
Not possible to mount the **root** folder of the SD card (not encrypted on my phone - Android 8).
However it is possible to mount **subfolder** of SD card. Very strange...

Using sftp, this is also reproduceable:
```
$ sftp -P 1748 kdeconnect@192.168.1.2 
 Connected to 192.168.1.2.
sftp> ls
 Carte SD  Galaxy    
sftp> cd Carte\ SD/
sftp> ls
 Couldn't read directory: Failure
sftp> cd Vidéos
sftp> ls
 video1.mpg
 video2.mpg
sftp> pwd
 Remote working directory: /Carte SD/Vidéos
sftp>
```
I think it is an old known issue: https://bugs.kde.org/show_bug.cgi?id=377058

**Comment by andyholmes** [comment] 2020-06-30 19:42
Marking this as upstream for now, since I don't see any indication this is a problem in GSConnect.

**Comment by andyholmes** [comment] 2020-08-03 18:37
Closing since this appears to be an upstream problem.

**Closed by andyholmes** 2020-08-03 18:37 UTC
Labels: needs info, upstream
