### ISSUE TITLE
No sms history on wiko jerry2

### ISSUE THREAD

**Issue by simomMe** [andyholmes/gnome-shell-extension-gsconnect#521] opened 2019-04-24 08:55 UTC
Wiko JERRY2, Android 7.0 vanilla, everything works except sms history. I use the default sms app "messages" provided by google (I've tried some others like textra but nothing changes).
Seems to be caused by connection error or a permission denied ... ? 

GSConnect Version: 21
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-02-03 04:10:30 CET, end at Wed 2019-04-24 10:47:39 CEST. --
Apr 24 10:47:02 gjs[3828]: GtkDialog mapped without a transient parent. This is discouraged.
Apr 24 10:47:05 gedit[7087]: Failed to load module "unity-gtk-module"
Apr 24 10:47:05 gedit[7087]: Failed to load module "unity-gtk-module"
Apr 24 10:47:05 gedit[7087]: Attempting to read the recently used resources file at '/home/simon/.local/share/recently-used.xbel', but the parser failed: Failed to open file “/home/simon/.local/share/recently-used.xbel”: Permission denied.
Apr 24 10:47:05 org.gnome.Shell.desktop[2329]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3200084 (*gsconnect)
Apr 24 10:47:08 org.gnome.Shell.desktop[2329]: [28688:28722:0424/104708.868179:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -202
Apr 24 10:47:08 org.gnome.Shell.desktop[2329]: [28688:28722:0424/104708.903847:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -202
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:16 gjs[3828]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 24 10:47:24 org.gnome.Shell.desktop[2329]: [28688:28722:0424/104724.637395:ERROR:ssl_client_socket_impl.cc(962)] handshake failed; returned -1, SSL error code 1, net_error -202
Apr 24 10:47:39 gjs[3828]: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by andyholmes** [comment] 2019-04-24 20:12
This is a duplicate of #320.

More than likely this is due to a change in the SMS database used by your phone's Android OS. There are no errors in your log related to GSConnect and SMS.

If you like, you can use the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) feature to log more detailed information from GSConnect while try to refresh the SMS window.

More helpful for KDE Connect developers would be to do so while logging the apps output in logcat. Once `adb` is installed and debug mode enabled on your phone, you can connect it by USB and run the following command to get output while trying to refresh:

    adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)

Any relevant logs should be reported upstream at https://bugs.kde.org/show_bug.cgi?id=401677

**Closed** 2019-04-24 20:13 UTC
Labels: duplicate, upstream
