### ISSUE TITLE
Weird layout on Ubuntu 18.04

### ISSUE THREAD

**Issue by PlugaruT** [andyholmes/gnome-shell-extension-gsconnect#122] opened 2018-05-21 19:42 UTC
In the screenshot is how the extension looks on Ubuntu 18.04 with the Gnome Shell 3.28.2. The theme is the Communitheme and also it looks the same with the default one.

![screenshot from 2018-05-21 22-36-02](https://user-images.githubusercontent.com/6437932/40326491-19ecde04-5d48-11e8-9d03-ad73e98d7846.png)

**Comment by andyholmes** [comment] 2018-05-22 20:21
I think this is a duplicate of #44 (menu rendering) and #116 (wrong size icons with Humanity icon theme). The first is fixed in v11, the second is fixed in master but I made a Zip which includes a fix for it already:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2028436/gsconnect.andyholmes.github.io.zip)

**Comment by PlugaruT** [comment] 2018-05-22 20:40
Thanks. :+1:

**Closed** 2018-05-22 20:41 UTC
Labels: fix committed
