### ISSUE TITLE
TslCertificate.get_common_name() returns undefined

### ISSUE THREAD

**Issue by fabrixxm** [andyholmes/gnome-shell-extension-gsconnect#142] opened 2018-06-15 15:59 UTC
On my system:

    $ uname -a
    Linux piccettino 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
    $ gnome-shell --version
    GNOME Shell 3.28.2
    $ openssl version
    OpenSSL 1.1.0h  27 Mar 2018
    $ cat ~/.config/gsconnect/certificate.pem | openssl x509 -noout -subject -inform pem
    subject=CN = d4b70e62-71f0-47e5-be50-236d44651b7f

This break the split and the function returns undefined.

**Comment by andyholmes** [comment] 2018-06-15 16:47
Seems like a duplicate of #26. This should [be fixed](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/22d93f096c293d5d841772f57c8186b60a7b5e3a/src/common.js#L171) in [v11](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v11) already:

```js
return /[a-zA-Z0-9\-]{36}/.exec(output)[0];
```

Please re-open if update doesn't fix the problem.

**Closed by andyholmes** 2018-06-15 16:47 UTC

**Comment by fabrixxm** [comment] 2018-06-15 18:53
Oh well. Sorry for the noise :+1:
