### ISSUE TITLE
Can't bind keyboard shortcut  

### ISSUE THREAD

**Issue by gautierlabarre** [andyholmes/gnome-shell-extension-gsconnect#523] opened 2019-04-29 19:21 UTC
Hello, a tiny bug for you :

**Describe the bug**
I want to affect a keyboard shortcut to any action and a messages displays : "already used" for any combination of keyword I type.

**To Reproduce**
1. Go to 'Raccourcis clavier' ( keyboard shortcut ?)'
2. Click on a line
3. press any combination of keys
4. Message displayed : CTRL + 8 (i.e) is already used

**Screenshots**
![Capture d’écran de 2019-04-29 21-14-56](https://user-images.githubusercontent.com/13676992/56920643-0c0fb100-6ac4-11e9-89fb-65159b7dd90b.png)

**Debug output**
```
GSConnect Version: 21
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Mon 2019-04-29 17:26:10 CEST, end at Mon 2019-04-29 21:09:44 CEST. --
avril 29 21:09:00 gnome-shell[1780]: JS ERROR: TypeError: text is null
                                     _parseClipboardText@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:211:13
                                     _createDesktopBackgroundMenu/</<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:350:58
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:02 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:09 gjs[2032]: JS WARNING: [/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/device.js 929]: reference to undefined property "sms"
avril 29 21:09:10 gjs[2032]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
avril 29 21:09:10 gjs[2032]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
avril 29 21:09:18 gnome-shell[1780]: JS ERROR: TypeError: text is null
                                     _parseClipboardText@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:211:13
                                     _createDesktopBackgroundMenu/</<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:350:58
avril 29 21:09:33 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:33 gnome-shell[1780]: Ignoring excess values in shadow definition
avril 29 21:09:44 gjs[2032]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
avril 29 21:09:44 gjs[2032]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
avril 29 21:09:44 systemd-resolved[862]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
```

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.32.1
 - Distro/Release: Ubuntu 19.04

**GSConnect environment (if applicable):**
 - Paired Device(s): Oneplus 6
 - KDE Connect app version: latest

**Additional context**
It worked on my latest Ubuntu (18.10) with gnome 3.30, from last week.

**Comment by andyholmes** [comment] 2019-05-01 02:51
Thanks for reporting, I think this is a duplicate of #522 though, which was fixed in de44f41. I guess I should do a new release sometime soon.

**Closed** 2019-05-01 02:51 UTC
Labels: duplicate, fixed in master
