### ISSUE TITLE
missing getter for read-only property active

### ISSUE THREAD

**Issue by nahuelwexd** [andyholmes/gnome-shell-extension-gsconnect#960] opened 2020-09-20 04:58 UTC
```
GSConnect: 42 (user)
GJS:       16600
Session:   wayland
OS:        Fedora 33.20200918.n.0 (Silverblue Prerelease)

_generateAccessors/propdesc.get@resource:///org/gnome/gjs/modules/core/_common.js:66:19
start@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:450:13
_loadBackends@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/var/home/nahuelwexd/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2020-09-20 05:18
Thanks for reporting, duplicate of #959.

**Closed by andyholmes** 2020-09-20 05:18 UTC
