### ISSUE TITLE
It does not start on Wayland, it works only on X11.

### ISSUE THREAD

**Issue by Kerrung** [andyholmes/gnome-shell-extension-gsconnect#684] opened 2019-10-30 11:08 UTC
It does not start on Wayland, it works only on X11.

**Comment by andyholmes** [comment] 2019-10-30 18:49
Sorry, I'll need a little more information:

**Describe the bug**

A clear and concise description of what the bug is.

**Steps To Reproduce:**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 20, 24, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by Kerrung** [comment] 2019-10-30 19:21
I use Arch Linux, More info will be later...

**Comment by Kerrung** [comment] 2019-11-10 10:36
I discovered new details. Starting with GNOME 3.34, it is now possible to configure GNOME Mutter so that the launch of XWayland does not happen absolutely always, but only on demand, only when X11 applications are launched. But this does not work for all X11 applications, that is, the launch of not every X11 application leads to the automatic launch of XWayland, so such applications simply do not work if XWayland is not started in advance, that is, always.

So that you can reproduce this problem, use dconf-editor to go to /org/gnome/mutter/experimental-features
Here, add the new experimental option 'autostart-xwayland', and as soon as you do this, go back to the Wayland session or restart it, after which you will find that GSConnect extension does not start at all, does not work completely.

I believe that the best solution to this problem would be to add full Wayland support for your extension so that it no longer requires XWayland to work on the Wayland session.

Thanks you.

**Comment by andyholmes** [comment] 2019-11-10 10:42
GSConnect has had full supported Wayland for some time now.

In order to support clipboard on Wayland, we run a small XWayland subprocess to access the desktop clipboard. This process should start XWayland if it's not already running.

This may be the problem, but without proper logs there's no way to tell why this isn't working for you.

**Comment by Kerrung** [comment] 2019-11-10 10:49
> GSConnect has had full supported Wayland for some time now.
> 
> In order to support clipboard on Wayland, we run a small XWayland subprocess to access the desktop clipboard. This process should start XWayland if it's not already running.
> 
> This may be the problem, but without proper logs there's no way to tell why this isn't working for you.

Can you make XWayland no longer required for your extension?

**Comment by andyholmes** [comment] 2019-11-10 11:12
Nope. That would mean breaking Clipboard support for all Wayland users.

If you want that to happen, you'll have to convince the users on #454 first.

**Comment by andyholmes** [comment] 2019-11-15 23:19
Closing due to lack of information. Feel free to re-open if you can provide the necessary logs to debug this issue.

**Closed by andyholmes** 2019-11-15 23:19 UTC
Labels: needs info
