### ISSUE TITLE
Ghost notification issue

### ISSUE THREAD

**Issue by ghost** [andyholmes/gnome-shell-extension-gsconnect#737] opened 2019-12-18 17:53 UTC
**Describe the bug**

GsConnect shows a ghost notification in the gnome shell's notifications list. No app that should show that notification is open (on both desktop and android)

**Steps To Reproduce:**
1. Turn on Gsconnect
2. Wait to pair
3. The notification pops up and wont go away.

**Expected behavior**

The notification doesn't show up in the first place

**Support Log**

```
dec 18 19:46:27 org.gnome.Shell.Extensions.GSConnect[4800]: [/service/protocol/core.js:receive/<:283]: P20 Pro: {
                                                              "id": 1576691187257,
                                                              "type": "kdeconnect.mpris",
                                                              "body": {
                                                                "playerList": [
                                                                  "Muzică"
                                                                ]
                                                              }
                                                            }
dec 18 19:46:27 org.gnome.Shell.Extensions.GSConnect[4800]: [/service/protocol/core.js:send:329]: P20 Pro: {
                                                              "id": 1576691187871,
                                                              "type": "kdeconnect.mpris.request",
                                                              "body": {
                                                                "player": "Muzică",
                                                                "requestNowPlaying": true,
                                                                "requestVolume": true
                                                              }
                                                            }
dec 18 19:46:27 org.gnome.Shell.Extensions.GSConnect[4800]: [/service/protocol/core.js:receive/<:283]: P20 Pro: {
                                                              "id": 1576691187269,
                                                              "type": "kdeconnect.mpris",
                                                              "body": {
                                                                "player": "Muzică",
                                                                "nowPlaying": "Anne-Sophie Mutter; Ayami Ikeba - Dvořák - 8 Humoresques, Op. 101, B. 187 : Humoresque, Op.101, No.7 - Arranged By Fritz Kreisler",
                                                                "title": "8 Humoresques, Op. 101, B. 187 : Humoresque, Op.101, No.7 - Arranged By Fritz Kreisler",
                                                                "artist": "Anne-Sophie Mutter; Ayami Ikeba - Dvořák",
                                                                "album": "Dvořák",
                                                                "isPlaying": false,
                                                                "pos": 2256,
                                                                "length": 192147,
                                                                "canPlay": true,
                                                                "canPause": true,
                                                                "canGoPrevious": true,
                                                                "canGoNext": true,
                                                                "canSeek": true,
                                                                "volume": 0
                                                              }
                                                            }
dec 18 19:46:27 org.gnome.Shell.Extensions.GSConnect[4800]: [/service/plugins/mpris.js:_onBusAcquired:527]: {
                                                              "0": {},
                                                              "1": "org.mpris.MediaPlayer2.GSConnect.P20ProMuzic"
                                                            }
dec 18 19:46:27 org.gnome.Shell.Extensions.GSConnect[4800]: [/service/protocol/core.js:receive/<:283]: P20 Pro: {
                                                              "id": 1576691187309,
                                                              "type": "kdeconnect.mpris",
                                                              "body": {
                                                                "player": "Muzică",
                                                                "nowPlaying": "Anne-Sophie Mutter; Ayami Ikeba - Dvořák - 8 Humoresques, Op. 101, B. 187 : Humoresque, Op.101, No.7 - Arranged By Fritz Kreisler",
                                                                "title": "8 Humoresques, Op. 101, B. 187 : Humoresque, Op.101, No.7 - Arranged By Fritz Kreisler",
                                                                "artist": "Anne-Sophie Mutter; Ayami Ikeba - Dvořák",
                                                                "album": "Dvořák",
                                                                "isPlaying": false,
                                                                "pos": 2256,
                                                                "length": 192147,
                                                                "canPlay": true,
                                                                "canPause": true,
                                                                "canGoPrevious": true,
                                                                "canGoNext": true,
                                                                "canSeek": true,
                                                                "volume": 0
                                                              }
                                                            }

```
**System Details (please complete the following information):**

 - **GSConnect version:** 30
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.2
 - **Distro/Release:** Fedora 31

**GSConnect environment (if applicable):**

 - **Paired Device(s):** P20 Pro
 - **KDE Connect app version:** 1.13.5

**Comment by andyholmes** [comment] 2019-12-18 18:50
This looks like Android is sending information about a music player on your device. If that's so, it's probably GNOME Shell showing an MPRIS notifications. Can you show me a screenshot of the notification?

**Comment by DanielValahul** [comment] 2019-12-18 20:10
Weirdly, it dissapeared now. But it persisted there for some time, even after some reboots

**Comment by ferdnyc** [comment] 2019-12-19 09:10
@DanielValahul 

Did it look anything at all like this?

![image](https://user-images.githubusercontent.com/538020/71160233-2a721a80-2215-11ea-8f1f-a7a1af93bc74.png)

If so, that's an MPRIS media control panel ­— GNOME Shell will show one whenever it detects an application running that supports MPRIS controls / metadata. Since it's not a notification (even though it looks like one, just to be confusing) it can't be dismissed, and applications don't have any control over whether or not it's shown (other than by disabling their MPRIS interfaces).

**Comment by DanielValahul** [comment] 2019-12-19 10:08
Yes, it looked exactly like that. However no app was running at the time on my android. Maybe it was in the background?

**Comment by andyholmes** [comment] 2019-12-19 22:04
I think that's likely. From the log you posted Android seemed to think there was Music player running, although playback was stopped.

There was a bug in the Android app about this some months ago, so there might be a regression. Possibly the media player exited but the app didn't register it. You're welcome to leave this one open for awhile in case it happens again, in which case we can bump it upstream and link to this bug.

**Comment by ferdnyc** [comment] 2019-12-20 07:10
> Yes, it looked exactly like that. However no app was running at that time on my android. Maybe it was in the background?

It'll also react to applications on the local system, so that's another possibility. Media players like VLC and Totem will trigger it, at least with the right plugins enabled (which they probably are by default), and in recent versions of Google Chrome, you'll also get one when visiting a YouTube video page or similar.

(And as you can see here, it's not limited to just _one_ either. **Both** of these are now showing due to local applications, specifically my music player and a YouTube video in Chrome:)
![Screenshot from 2019-12-20 02-07-35](https://user-images.githubusercontent.com/538020/71236766-c5c6c680-22cd-11ea-8184-2146a34625a4.png)

**Comment by andyholmes** [comment] 2020-02-08 21:22
Closing since it seems like the reporting user has deleted their account.

**Closed by andyholmes** 2020-02-08 21:22 UTC
Labels: needs info
