### ISSUE TITLE
missing getter for read-only property active

### ISSUE THREAD

**Issue by shemgp** [andyholmes/gnome-shell-extension-gsconnect#966] opened 2020-09-20 14:21 UTC
```
GSConnect: 42 (user)
GJS:       16600
Session:   x11
OS:        Ubuntu Groovy Gorilla (development branch)

_generateAccessors/propdesc.get@resource:///org/gnome/gjs/modules/core/_common.js:66:19
start@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:450:13
_loadBackends@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/shemgp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2020-09-20 20:04
Thanks for reporting, duplicate of #959.

**Closed by andyholmes** 2020-09-20 20:04 UTC
