### ISSUE TITLE
I got this, I dont know much but I believe you can use it.

### ISSUE THREAD

**Issue by leoheck** [andyholmes/gnome-shell-extension-gsconnect#858] opened 2020-05-14 19:30 UTC
I got this, I don't know much but I believe you can use it.
I am using ubuntu 20.04 with the pre-releases enabled.

![image](https://user-images.githubusercontent.com/1277920/81977250-1aae0500-9600-11ea-9abe-c8cd4708e267.png)

**Comment by andyholmes** [comment] 2020-05-14 20:21
Sorry, you've forgotten to add any information about GSConnect. What version are you using?

What are the package versions of `gnome-shell`, `gjs` and `libgjs0g` on your system?

**Comment by leoheck** [comment] 2020-05-15 15:40
Sorry, I didn't know what do you need to understand the issue.

Do you have any practical way to retrieve these infos? By practical I mean, just copy and paste on the terminal to get the output?

**Comment by andyholmes** [comment] 2020-05-15 17:18
What version of GSConnect are you running?

What versions of `gnome-shell`, `gjs` and `libgjs0g` are installed?

```
$ apt list gnome-shell
$ apt list gjs
$ apt list libgjs0g
```

**Comment by leoheck** [comment] 2020-05-16 03:44
```
gnome-shell/focal-proposed,now 3.36.2-1ubuntu1~20.04.1 amd64 [installed]
gjs/focal-proposed,now 1.64.2-1ubuntu1~20.04.1 amd64 [installed,automatic]
libgjs0g/focal-proposed,now 1.64.2-1ubuntu1~20.04.1 amd64 [installed,automatic]
```

**Comment by andyholmes** [comment] 2020-08-03 18:34
Closing since I can't reproduce and we don't know what version of GSConnect this is. Feel free to reopen if the issue persists.

**Closed by andyholmes** 2020-08-03 18:34 UTC
Labels: needs info
