### ISSUE TITLE
GS Connect extension update error

### ISSUE THREAD

**Issue by likhithravula** [andyholmes/gnome-shell-extension-gsconnect#922] opened 2020-08-18 06:08 UTC
I received a new update for GS Connect in my desktop notifications. 
This image shows GS Connect extension error after the update.
![image](https://user-images.githubusercontent.com/38804309/90476326-ebe78380-e146-11ea-86b6-fc724e4ff5af.png)
I have tried reinstalling the extension and still there was an error. 
Also, there is no integration in control panel on the top right drop down menu in Ubuntu.

**Comment by andyholmes** [comment] 2020-08-18 06:17
duplicate of #817.

You must restart GNOME Shell after upgrading an extension.

**Closed by andyholmes** 2020-08-18 06:17 UTC
