### ISSUE TITLE
Hey guys this is the problem when i updated GSConnect it shows error 

### ISSUE THREAD

**Issue by suvotheking007** [andyholmes/gnome-shell-extension-gsconnect#915] opened 2020-08-15 05:20 UTC
Error screenshot :- 
![Screenshot from 2020-08-15 10-38-20](https://user-images.githubusercontent.com/46703628/90305881-09b5ae00-dee5-11ea-8e1c-ce6e4d080ba4.png)

System info :- 
![Screenshot from 2020-08-15 10-48-03](https://user-images.githubusercontent.com/46703628/90305890-205c0500-dee5-11ea-9b62-f13b23200160.png)

**Comment by blain1972** [comment] 2020-08-15 07:32
I had the same issue - reboot resolved it for me.

Ubuntu 20.04.1 LTS
Gnome 3.36.3

**Comment by andyholmes** [comment] 2020-08-15 07:37
Yup, duplicate of #817. We'll just have to wait until extensions.gnome.org is fixed to address this issue.

**Closed by andyholmes** 2020-08-15 07:37 UTC
