### ISSUE TITLE
gjs consumes up to ~30 gigabytes of RAM, then crashes

### ISSUE THREAD

**Issue by lwbt** [andyholmes/gnome-shell-extension-gsconnect#806] opened 2020-04-01 14:42 UTC
**Describe the bug**

I observe that suddenly my desktop RAM usage jumps from normal to use 30GB more and the desktop starts to stutter. I get messages from Gnome shell that a gjs process crashed. I was able to open a terminal and investigate this time.

```
livewire@za25:~$ ps -ef | grep gjs
livewire 20203     2 98 15:48 ?        00:00:18 /usr/bin/python3 /usr/share/apport/apport 23716 11 0 1 23716 !usr!bin!gjs-console
livewire 20721 20386  0 15:48 pts/9    00:00:00 grep --color=auto gjs
livewire 23716  8357  0 Mär31 ?       00:02:27 gjs /home/livewire/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```
![https://i.imgur.com/AOEKjxH.png](https://i.imgur.com/AOEKjxH.png)

Edit: These spikes seem to occur about every 24-30h.
![https://i.imgur.com/eID1FOJ.png](https://i.imgur.com/eID1FOJ.png)

**Steps To Reproduce:**

Unfortunately I don't have steps to reproduce at this moment.

1. I installed GSConnect.
2. I configured 2 devices and used them for a while now.
3. Only recently I started to notice these very unusual spikes.

**Expected behavior**

That the extension consumes less than 1 GB of RAM.

**Screenshots**

See description.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu-communitheme-snap
--------------------------------------------------------------------------------
-- Logs begin at Thu 2020-01-30 21:34:24 CET, end at Wed 2020-04-01 16:20:16 CEST. --
Apr 01 16:20:16 gjs[838]: GtkDialog mapped without a transient parent. This is discouraged.
```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions
 - **GNOME/Shell version:** GNOME Shell 3.28.4
 - **Distro/Release:** Ubuntu 18.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel XL, Pixel 4
 - **KDE Connect app version:** Pixel XL has 1.13.6, Pixel 4 has 1.13.7
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

I now followed instructions in [this post](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/666#issuecomment-541378600) and keep an eye on it.

**Comment by andyholmes** [comment] 2020-04-01 19:42
Is there a backtrace in apport for this crash?

**Comment by lwbt** [comment] 2020-04-02 06:31
I have to check where I can find the old apport data, if it still exists. I also have logcheck running on my workstation running and this is what occurred in the time frame:

```
Apr  1 15:48:18 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) event8  - Logitech USB Receiver: SYN_DROPPED event - some input events have been lost.
Apr  1 15:48:21 za25 /usr/lib/gdm3/gdm-x-session[8381]: (EE) client bug: timer event8 debounce: offset negative (-31ms)
Apr  1 15:48:24 za25 /usr/lib/gdm3/gdm-x-session[8381]: (EE) client bug: timer event8 debounce: offset negative (-102ms)
Apr  1 15:48:24 za25 /usr/lib/gdm3/gdm-x-session[8381]: (EE) client bug: timer event8 debounce: offset negative (-158ms)
Apr  1 15:48:24 za25 /usr/lib/gdm3/gdm-x-session[8381]: (EE) client bug: timer event8 debounce: offset negative (-79ms)
Apr  1 15:48:24 za25 /usr/lib/gdm3/gdm-x-session[8381]: (EE) client bug: timer event8 debounce short: offset negative (-92ms)
Apr  1 15:48:26 za25 kernel: Code: 0f 84 b7 fc ff ff 8d 45 ff 48 8d 6c 24 28 45 31 ff 48 8d 04 c5 08 00 00 00 48 89 44 24 08 0f 1f 40 00 48 8b b4 24 e0 00 00 00 <4a> 8b 04 3b 41 b8 01 00 00 00 48 89 e9 4c 89 f2 4c 89 e7 4c 01 fe
Apr  1 15:48:26 za25 kernel: gjs[23716]: segfault at 0 ip 00007fdda96e8258 sp 00007ffd15e7f920 error 4 in libgjs.so.0.0.0[7fdda96c0000+c7000]
Apr  1 15:48:59 za25 dbus-daemon[8397]: [session uid=1000 pid=8397] Monitoring connection :1.2117 closed.
Apr  1 15:49:01 za25 chromium-browser.desktop[13224]: [13268:13282:0401/154901.141354:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
Apr  1 15:49:01 za25 dbus-daemon[8397]: [session uid=1000 pid=8397] Connection :1.2578 (uid=1000 pid=21149 comm="gjs /home/livewire/.local/share/gnome-shell/extens" label="unconfined") became a monitor.
Apr  1 15:49:01 za25 gjs[21149]: g_variant_new_string: assertion 'string != NULL' failed
Apr  1 15:49:02 za25 chromium-browser.desktop[13224]: [13268:13282:0401/154902.582308:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): EDID vendor "DEL", prod id 53358
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
…
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): Printing DDC gathered Modelines:
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): Using hsync ranges from config file
Apr  1 15:49:06 za25 /usr/lib/gdm3/gdm-x-session[8381]: (II) modeset(0): Using vrefresh ranges from config file
Apr  1 15:49:32 za25 gjs[21870]: Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
Apr  1 15:49:32 za25 gjs[21870]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Apr  1 15:49:32 za25 gjs[21870]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Apr  1 15:49:32 za25 gjs[21870]: Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
Apr  1 15:49:32 za25 gjs[21870]: message repeated 2 times: [ Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link']
Apr  1 15:49:43 za25 chromium-browser.desktop[13224]: [13268:13282:0401/154943.538269:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
Apr  1 15:51:28 za25 apport-gtk[24548]: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by lwbt** [comment] 2020-04-02 16:43
It just happened again. The error message says in German that there is not enough memory available. Which is not true, gjs process uses 51,x % of my RAM and there should be at least 10 GB more RAM available. I was not doing much on this machine with 64 GB. A few web browser windows and so forth. It's currently at 8,4 GB usage. I had the log open as mentioned before, but I can't find anything particularly related.

I had already reduced the amount of active modules from all to MPRIS, notifications, and system volume.

![https://i.imgur.com/7GPj08z.png](https://i.imgur.com/7GPj08z.png)

Any advice how to continue?

**Comment by andyholmes** [comment] 2020-04-02 19:14
There's not a whole lot of guidance I can give here. I don't see much in the commit log that stands out, which means this probably an old bug in GJS or one of the other dozen or so libraries we use.

Unfortunately we aren't doing any more releases for older versions of GNOME, pretty much because of problems like this. If this were a more modern setup, the next step would probably be to run gsconnect through sysprof to find out where the memory is being allocated, but I'm not sure sysprof even had GJS support in 3.28.

Since I haven't had a report like this in a long time, my best advice would be to upgrade your system. My second best advice would just be to follow the steps for [completely removing GSConnect](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) and then to re-install. It may be this is a configuration problem?

**Comment by Aerilius** [comment] 2020-04-06 08:22
I'm seeing the same issue. I'm using stable Ubuntu (18.04), so even if old it's the latest LTS I can use for production.

Three observations:
- The issue happens while I have no other devices connected at the moment.
- The issue persisted after disabling GSConnect.
- The issue disappeared when I disabled clipboard sync (which maybe was still running in the background or assumed devices still connected).

**Comment by andyholmes** [comment] 2020-04-06 19:58
It could be in the clipboard, but I don't see anything obvious that would cause any kind of object leak.

There seem to be a couple fixes since gjs-1.52 that weren't backported upstream, related to selection data and atoms. I have no idea if these were backported downstream by Ubuntu or if they're the cause.

There are no reports of this since GNOME 3.28, so I can only assume this something fixed in GJS, Gtk or GLib that only affects older distributions.

**Comment by themreza** [comment] 2020-04-10 15:45
This happens when something large is copied in the clipboard or when moving large files (CTRL+X, CTRL+V).

**Comment by andyholmes** [comment] 2020-04-10 21:08
Could be an issue with file-list URIs.

Unfortunately I'm going to have to close this issue up. We no longer support older versions of GNOME, pretty much because of issues like this. I no longer have the time to support versions of a half-dozen distributions going back ~2 years, along with the dozen or so libraries and desktop components we rely on.

If someone wants to step up and continue maintainership for Ubuntu 18.04, you can branch off at tag v28 and I'll give you permissions to maintain an upstream branch. Other than that, there's not much I can do for you.

**Closed by andyholmes** 2020-04-10 21:08 UTC
Labels: unsupported
