### ISSUE TITLE
Notifications are shared between GSConnect instances despite beeing disabled

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#306] opened 2018-11-05 17:06 UTC
Same devices/specs as in https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/266.

I now have "share notifications" disabled **on both devices**, but apparently it still shares all notifications.

I even tested it with `zenity --window-icon="./tools/icon.png" --notification --title "GSConnectTest" --text "What the fuck is happening?3fsdfsd3"` to make sure it is no other thing.

Also disconnected all other devices.

```
DEBUG: [notification.js:sendNotification:305]: (Zenity-Benachrichtigung) What the fuck is happening?3fsdfsd3: 
DEBUG: [core.js:send:450]: DEVICE TWO: {
  "id": 1541437525359,
  "type": "kdeconnect.notification",
  "body": {
    "appName": "Zenity-Benachrichtigung",
    "id": "fdo|null|0",
    "title": "What the fuck is happening?3fsdfsd3",
    "text": "",
    "ticker": "What the fuck is happening?3fsdfsd3: ",
    "isClearable": false
  }
}
```

**Comment by andyholmes** [comment] 2018-11-06 08:05
I'm at a loss at how this could happen. The related code is here (apparently Github snippets not working):

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/b6c09c65f0cfadcf5d9668b61d96a17a68f9f94f/src/service/plugins/notification.js#L294-L299

```js
async sendNotification(notif) {
    try {
        // Sending notifications is forbidden
        if (!this.settings.get_boolean('send-notifications')) {
            return;
        }
```

So the setting is actually read each time, not cached, and exits the functions immediately if not enabled. I don't know what could happen for that guard clause to fail.

**Comment by scde** [comment] 2018-11-06 13:55
This is most likely an issue with v13 - which @rugk seems to be using - and the code snippet posted seems to be a recent change. I actually have the same version and problem and it definitely runs different code. Although I have not tested newer versions. I'm just waiting for the update from the GNOME Shell Extensions website.

@rugk As temporary workaround you can toggle the setting on and off and it should work as intended (no notifications get sent to the device). Although after a disconnect the bug occurs again, so it is not a really useful solution. Other than that you can try to manually install newer versions (instructions are in the wiki: [1](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) or [2](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git)) and see if those work correctly.

**Comment by rugk** [comment] 2018-11-06 15:49
Oh thanks, you are right, toggling the setting "fixes" it. :smile:

**Comment by andyholmes** [comment] 2018-11-10 12:12
Closing this since v15 is being distributed.

**Closed by andyholmes** 2018-11-10 12:12 UTC
Labels: fix committed
