### ISSUE TITLE
GSconnect Not Working

### ISSUE THREAD

**Issue by Tomoghno** [andyholmes/gnome-shell-extension-gsconnect#993] opened 2020-10-06 07:56 UTC
The settings of extension gsconnect@andyholmes.github.io had an error:
```
Error: GSConnect: Failed to install DBus Service
```

Stack trace:
```
installService@/home/tomoghno/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/utils.js:174:19
init@/home/tomoghno/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:13:11
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:205:25
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by andyholmes** [comment] 2020-10-06 19:54
Sorry, I can't reproduce this. Can you provide this information?

> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

A clear and concise description of what the bug is.

**Steps To Reproduce:**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by andyholmes** [comment] 2020-12-04 02:23
Closing due to lack of information and activity.

**Closed by andyholmes** 2020-12-04 02:23 UTC
Labels: needs info
