### ISSUE TITLE
Can't access phone filesystem (Error with SFTP)

### ISSUE THREAD

**Issue by mezojm10** [andyholmes/gnome-shell-extension-gsconnect#963] opened 2020-09-20 10:44 UTC
**Describe the bug**

When I try to access the phone filesystem the file explorer crashes, I tried both nautilus and nemo.

**Steps To Reproduce:**

1. Go to GSConnect
2. Click on phone
3. Mount filesystem
4. Try to access it
4. File explorer crashes

**Expected behavior**

Being to access the filesystem normally without the explorer crashing

**Support Log**

```
Sep 20 12:32:09 tracker-miner-f[1116]: g_str_has_suffix: assertion 'str != NULL' failed
Sep 20 12:32:09 tracker-miner-f[1116]: g_str_has_prefix: assertion 'str != NULL' failed
Sep 20 12:32:09 tracker-miner-f[1116]: g_str_has_prefix: assertion 'str != NULL' failed
Sep 20 12:32:09 tracker-miner-f[1116]: g_str_has_prefix: assertion 'str != NULL' failed
Sep 20 12:32:19 org.gnome.Shell.Extensions.GSConnect[6695]: [/service/device.js:sendPacket:446]: Mezojm10: {
                                                              "id": 1600597939040,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Sep 20 12:32:19 org.gnome.Shell.Extensions.GSConnect[6695]: [/service/device.js:_readLoop:338]: Mezojm10: {
                                                              "id": 1600597925002,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "192.168.43.1",
                                                                "port": 1739,
                                                                "user": "kdeconnect",
                                                                "password": "KGLSZLP1VEUQS0z26yrAhRCjCTdl",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/primary",
                                                                  "/primary/Books"
                                                                ],
                                                                "pathNames": [
                                                                  "primary",
                                                                  "Books"
                                                                ]
                                                              }
                                                            }
Sep 20 12:32:21 nemo[9180]: Current gtk theme is not known to have nemo support (Yaru-dark) - checking...
Sep 20 12:32:22 nemo[9180]: File has symlink target, but  is not marked as symlink
Sep 20 12:32:22 kernel: nemo[9180]: segfault at 0 ip 00007f8c8dea7494 sp 00007ffc036835d8 error 4 in libglib-2.0.so.0.6400.3[7f8c8de83000+84000]
Sep 20 12:32:22 kernel: Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 a3 cf fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
```

**System Details:**

 - **GSConnect version:** 42
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.4
 - **Distro release:** Ubuntu 20.04 LTS

**GSConnect environment:**

 - **Paired Device(s):** Huawei Y9s
 - **KDE Connect app version:** 1.14.2
 - **Plugin(s):** SFTP

**Comment by andyholmes** [comment] 2020-09-20 20:24
This seems like a duplicate of #857. This is [bug](https://github.com/linuxmint/nemo/issues/2387) they'll have to fix in nemo.

**Closed** 2020-09-20 20:25 UTC
Labels: can't fix

**Comment by mezojm10** [comment] 2020-09-23 11:20
The issue is not with nemo, it's happening with nautilus too.

**Comment by andyholmes** [comment] 2020-09-23 18:41
If there's a segfault in nautilus, you should report it on [Gitlab](https://gitlab.gnome.org/GNOME/nautilus/-/issues). I can't fix crashes that happen in Nautilus.
