### ISSUE TITLE
My phone can't find my computer.

### ISSUE THREAD

**Issue by leoheck** [andyholmes/gnome-shell-extension-gsconnect#463] opened 2019-02-15 00:00 UTC
**Describe the bug**
Can't connect my smartphone. It was working some weeks ago

**To Reproduce**
The phone does not see my computer, even if I add manually the Ip or hostname
I already tried to remove and install the Android app and Gnome extension again. Nothing have improved.

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28.2
 - Distro/Release: Ubuntu 18.04 (Using Vanilla Gnome insted of the Ubuntu Gnome) 

**GSConnect environment (if applicable):**
 - Paired Device(s): Google Pixel 3 XL
 - KDE Connect app version: 1.10.1 (29th November 2018)
 - Plugin(s):

**Comment by andyholmes** [comment] 2019-02-15 04:04
Hi, can you please confirm that you can ping the phone from the computer running GSConnect?

    $ ping 192.168.#.#

Can you also post the output of `lsof`:

    $ lsof -i UDP:1716

**Comment by 1989gironimo** [comment] 2019-02-15 20:17
Same behavior, the mobile device is pingable and the port is open, running GSConnect on PureOS with a Nexus5X as the paired device.
Firewall could be an issue, so I added the iptables rules written on the kde-connect manualpage and rebooted several times.

I suppose it's not an issue with the app, but it would be nice to have some documentation about troubleshooting the connection maybe?

**Comment by leoheck** [comment] 2019-02-15 21:26
Here, in my work. I installed GSConnect now, from the gnome extensions page.
The phone found my computer. It is paired now, it took me 3 tries to make it work properly.

It looks working from the smartphone side, but the extension on my computer looks stuck not responding.

I have to test it from my home, but here  at my work I got this
```
~ took 7s 
➜ lsof -i UDP:1716 
COMMAND   PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
gjs     29141 lheck   16u  IPv4 1240377      0t0  UDP *:1716 
```

**Comment by leoheck** [comment] 2019-02-16 02:13
Can ping at my home but not connect. 

Same result for the lsof

```
➜  ~ lsof -i UDP:1716
COMMAND  PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gjs     2313 lheck   16u  IPv4  46709      0t0  UDP *:1716 
```

**Comment by andyholmes** [comment] 2019-02-16 06:24
> I suppose it's not an issue with the app, but it would be nice to have some documentation about troubleshooting the connection maybe?

There's some help [in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#connecting-an-android-device) for connecting Android devices, but these are usually local networking problems that are difficult to detect.

> Can ping at my home but not connect.

It may be that UDP broadcasts are being blocked somehow on your network. You can use the [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) feature to gather extra debug logging from GSConnect while you try to connect. You should keep the dialog open while you try to connect, then close it when you're sure the connection has failed. If there are no errors in the log, then the problem is likely not GSConnect.

**Comment by leoheck** [comment] 2019-02-16 14:25
@andyholmes I have google wifi on both networks. They are pretty the same networks.

However, I tested it on diferent computers. Same Dell XPS but a different version on them. Same Ubuntu 18.04 version. It might be the configs that are wrong. I will take a look in the Wiki to see if I can fix it.
I'm thinking about just remove the configs folder to see if I can start it fresh

I believe the issue should be in the app because I can't see the following screen working on my computers. The screen is buggy on both computers. 

![image](https://user-images.githubusercontent.com/1277920/52901022-cd689b00-31e4-11e9-86eb-ea550f2cf500.png)

**Comment by leoheck** [comment] 2019-02-16 14:33
I'am seeing some issues here
```
GSConnect Version: 19
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Tue 2018-11-06 23:10:32 -02, end at Sat 2019-02-16 12:32:15 -02. --
fev 16 12:32:00 gjs[2790]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f703c093310 native@0x56346bb61560]
fev 16 12:32:05 gjs[2790]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f703c093460 native@0x56346bb246c0]
fev 16 12:32:10 gjs[2790]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f703c49ecd0 native@0x56346ba46870]
fev 16 12:32:15 gjs[2790]: GtkDialog mapped without a transient parent. This is discouraged.
fev 16 12:32:15 org.gnome.Shell.Extensions.GSConnect[2790]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
fev 16 12:32:15 gjs[2790]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f703c099c10 native@0x56346b9723b0]
```

**Comment by leoheck** [comment] 2019-02-16 14:43
Awesome!
I just removed the `~/.cache/gsconnect/` folder
Reinstalled the latest release zip from here. It is working!!
Cool @andyholmes thank you.

**Closed** 2019-02-27 05:39 UTC
