### ISSUE TITLE
gsconnect not working anymore

### ISSUE THREAD

**Issue by lepidas** [andyholmes/gnome-shell-extension-gsconnect#626] opened 2019-09-17 03:21 UTC
I thought it was a network problem but it's not.
gsconnect was working fine, pairing with my phone, until a week ago.
Now phone can't discover desktop and the other way around.
Can you help troubleshoot please :D 
 
**Support Log**

```
GSConnect Version: 26
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Tue 2019-09-17 04:54:22 CEST, end at Tue 2019-09-17 05:19:44 CEST. --
Sep 17 05:19:05 dbus-daemon[1788]: [session uid=1000 pid=1788] Reloaded configuration
Sep 17 05:19:05 gnome-software[3099]: failed to rescan: Failed to parse /home/blades/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 17 05:19:05 gjs[4455]: Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
Sep 17 05:19:10 gnome-software[3099]: Only 0 apps for recent list, hiding
Sep 17 05:19:10 gnome-software[3099]: failed to call gs_plugin_add_updates on fwupd: Not compatible with bootloader version: failed predicate [BOT03.0[0-1]_* regex BOT03.02_B0009]
Sep 17 05:19:10 gnome-software[3099]: hiding category audio-video featured applications: found only 0 to show, need at least 9
Sep 17 05:19:10 gnome-software[3099]: g_path_get_basename: assertion 'file_name != NULL' failed
Sep 17 05:19:10 gnome-software[3099]: g_regex_match_full: assertion 'string != NULL' failed
Sep 17 05:19:10 gnome-software[3099]: g_path_get_basename: assertion 'file_name != NULL' failed
Sep 17 05:19:10 gnome-software[3099]: g_regex_match_full: assertion 'string != NULL' failed
Sep 17 05:19:10 gnome-software[3099]: tried overwriting io.snapcraft.gcompris-QC7aattxeOlCUpGwG4BzvMZxeprZm7Wy key GnomeSoftware::FeatureTile-css from border-color: #000000;
                                      text-shadow: 0 1px 1px rgba(255,255,255,0.5);
                                      color: #000000;
                                      outline-offset: 0;
                                      outline-color: alpha(#ffffff, 0.75);
                                      outline-style: dashed;
                                      outline-offset: 2px;
                                      background: url('/home/blades/.cache/gnome-software/cssresource/84686cdf07fe94a29f777d42db719e7cdaa15afd-gcompris-qt.png') left center / auto 100% no-repeat, #FFFFFF;; to border-color: #000000;
                                      text-shadow: 0 1px 1px rgba(255,255,255,0.5);
                                      color: #000000;
                                      outline-offset: 0;
                                      outline-color: alpha(#ffffff, 0.75);
                                      outline-style: dashed;
                                      outline-offset: 2px;
                                      background: url('https://dashboard.snapcraft.io/site_media/appmedia/2019/08/gcompris-qt.png') left center / auto 100% no-repeat, #FFFFFF;;
Sep 17 05:19:17 gjs[4455]: GtkDialog mapped without a transient parent. This is discouraged.
Sep 17 05:19:18 org.gnome.Shell.desktop[1905]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4a00084 (gsconnect.)
Sep 17 05:19:18 gnome-shell[1905]: setup_framebuffers: assertion 'width > 0' failed
Sep 17 05:19:27 gjs[4455]: GtkDialog mapped without a transient parent. This is discouraged.
Sep 17 05:19:28 org.gnome.Shell.desktop[1905]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4a00084 (gsconnect.)
Sep 17 05:19:28 gnome-shell[1905]: setup_framebuffers: assertion 'width > 0' failed
Sep 17 05:19:44 gjs[4455]: GtkDialog mapped without a transient parent. This is discouraged.
```

    GSConnect version: 26
        Installed from: GNOME Extensions Website
    GNOME/Shell version: GNOME Shell 3.28.4
    Distro/Release: Ubuntu 18.04

**Comment by lepidas** [comment] 2019-09-17 03:40
Well everything went back to normal after removing `ipv6.disable=1` from ` /etc/default/grub`  
 I don't want to close this issue yet to see why I had to remove this

**Comment by andyholmes** [comment] 2019-09-17 19:01
This is probably due to the changes made in the LAN backend to close #593. 

Unfortunately, there's nothing in your log showing any errors with GSConnect, but we reuse the UDP sockets for both receiving and sending broadcasts so it could be either or both. The most important step for [Generating a Support log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) is step 2; I'm going to go clarify that in the Wiki after this :)

For this problem (connecting devices), you will have to make sure your mobile device is awake and the app is open. After opening the "logging" dialog, you should hit the *Refresh* button in the top-left corner of GSConnect settings a few times, then swipe down or select refresh in the Android app menu a few times. Only once you've done this should you close the dialog. That should give us a better idea of what's going wrong.

If I get some time later today, I'll try and boot up myself with that GRUB option set to different values. Could you tell me if `ipv6.disable=1` is the default for Ubuntu 18.04 (I'm on 19.04 at the moment)?

**Comment by ferdnyc** [comment] 2019-09-17 23:44
No need to reboot @andyholmes
```console
$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
$ netstat -r6
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
[::]/0                         [::]                       !n   -1  1     0 lo
[::]/0                         [::]                       !n   -1  1     0 lo
$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
$ netstat -r6
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
[::]/0                         [::]                       !n   -1  1     0 lo
localhost.localdomain/128      [::]                       UAn  0   2     0 lo
ff00::/8                       [::]                       U    256 1     0 eno1
[::]/0                         [::]                       !n   -1  1     0 lo
```

**Comment by ferdnyc** [comment] 2019-09-17 23:58
(That may not be _exactly_ the same, since according to [the old-school kernel parameter docs](https://www.kernel.org/doc/Documentation/networking/ipv6.txt)...)
<pre><code>
disable_ipv6

	Specifies whether to disable IPv6 on all interfaces.
	This might be used when no IPv6 addresses are desired.

	The possible values and their effects are:

	0
		IPv6 is enabled on all interfaces.

		This is the default value.

	1
		IPv6 is disabled on all interfaces.

		No IPv6 addresses will be added to interfaces.
</code></pre>
Whereas...
<pre><code>
disable

	Specifies whether to load the IPv6 module, but disable all
	its functionality.  This might be used when another module
	has a dependency on the IPv6 module being loaded, but no
	IPv6 addresses or operations are desired.

	The possible values and their effects are:

	0
		IPv6 is enabled.

		This is the default value.

	1
		IPv6 is disabled.

		No IPv6 addresses will be added to interfaces, and
		<b>it will not be possible to open an IPv6 socket.</b>

		A reboot is required to enable IPv6.
</code></pre>

But, still, worth a try setting `disable_ipv6` first to see if that's enough to repro the issue, before going scorched-earth.

**Comment by andyholmes** [comment] 2019-09-18 00:30
Okay, the former `sysctl` approach I cannot reproduce. The GRUB option I can, and I think I've fixed that (commit in one second).

FWIW, I'm currently testing in Ubuntu 19.10 and things start going wrong all over the place with that option on; I had to reboot again just to get Firefox to stay open. Granted, this is a beta ISO, but worth keeping in mind for the future.

**Comment by lepidas** [comment] 2019-09-18 06:56
> This is probably due to the changes made in the LAN backend to close #593.
> 
> Unfortunately, there's nothing in your log showing any errors with GSConnect, but we reuse the UDP sockets for both receiving and sending broadcasts so it could be either or both. The most important step for [Generating a Support log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) is step 2; I'm going to go clarify that in the Wiki after this :)
> 
> For this problem (connecting devices), you will have to make sure your mobile device is awake and the app is open. After opening the "logging" dialog, you should hit the _Refresh_ button in the top-left corner of GSConnect settings a few times, then swipe down or select refresh in the Android app menu a few times. Only once you've done this should you close the dialog. That should give us a better idea of what's going wrong.
> 
> If I get some time later today, I'll try and boot up myself with that GRUB option set to different values. Could you tell me if `ipv6.disable=1` is the default for Ubuntu 18.04 (I'm on 19.04 at the moment)?
> 
> EDIT: definitely a bug btw, so no need to close until we fix it ;)

`ipv6.disable=1` is not default in Ubuntu 18.04.
I broke it again through grub to make it not working again and this is the bug log with active apps and refreshing both android and pc.
```

GSConnect Version: 26
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Wed 2019-09-18 08:46:50 CEST, end at Wed 2019-09-18 08:51:59 CEST. --
Sep 18 08:51:02 gjs[3401]: GtkDialog mapped without a transient parent. This is discouraged.
Sep 18 08:51:35 org.gnome.Shell.desktop[1959]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4000084 (gsconnect.)
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:38 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[3401]: ../../../../gobject/gsignal.c:2641: instance '0x55d38db54eb0' has no handler with id '7609'
Sep 18 08:51:45 gjs[3401]: ../../../../gobject/gsignal.c:2641: instance '0x55d38db54eb0' has no handler with id '7607'
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:45 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:47 gjs[2428]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Sep 18 08:51:49 dbus-daemon[1331]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.161' (uid=1000 pid=3526 comm="/usr/bin/python3 /usr/bin/gnome-tweaks " label="unconfined")
Sep 18 08:51:49 systemd[1]: Starting Hostname Service...
Sep 18 08:51:49 dbus-daemon[1331]: [system] Successfully activated service 'org.freedesktop.hostname1'
Sep 18 08:51:49 systemd[1]: Started Hostname Service.
Sep 18 08:51:53 dbus-daemon[1805]: [session uid=1000 pid=1805] Reloaded configuration
Sep 18 08:51:53 gnome-software[3151]: failed to rescan: Failed to parse /home/blades/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 18 08:51:53 gjs[3563]: Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
Sep 18 08:51:57 gjs[3563]: GtkDialog mapped without a transient parent. This is discouraged.
Sep 18 08:51:58 gnome-software[3151]: Only 0 apps for recent list, hiding
Sep 18 08:51:58 gnome-software[3151]: failed to call gs_plugin_add_updates on fwupd: Not compatible with bootloader version: failed predicate [BOT03.0[0-1]_* regex BOT03.02_B0009]
Sep 18 08:51:58 gnome-software[3151]: g_path_get_basename: assertion 'file_name != NULL' failed
Sep 18 08:51:58 gnome-software[3151]: g_regex_match_full: assertion 'string != NULL' failed
Sep 18 08:51:58 gnome-software[3151]: g_path_get_basename: assertion 'file_name != NULL' failed
Sep 18 08:51:58 gnome-software[3151]: g_regex_match_full: assertion 'string != NULL' failed
Sep 18 08:51:58 gnome-software[3151]: tried overwriting io.snapcraft.gcompris-QC7aattxeOlCUpGwG4BzvMZxeprZm7Wy key GnomeSoftware::FeatureTile-css from border-color: #000000;
                                      text-shadow: 0 1px 1px rgba(255,255,255,0.5);
                                      color: #000000;
                                      outline-offset: 0;
                                      outline-color: alpha(#ffffff, 0.75);
                                      outline-style: dashed;
                                      outline-offset: 2px;
                                      background: url('/home/blades/.cache/gnome-software/cssresource/84686cdf07fe94a29f777d42db719e7cdaa15afd-gcompris-qt.png') left center / auto 100% no-repeat, #FFFFFF;; to border-color: #000000;
                                      text-shadow: 0 1px 1px rgba(255,255,255,0.5);
                                      color: #000000;
                                      outline-offset: 0;
                                      outline-color: alpha(#ffffff, 0.75);
                                      outline-style: dashed;
                                      outline-offset: 2px;
                                      background: url('https://dashboard.snapcraft.io/site_media/appmedia/2019/08/gcompris-qt.png') left center / auto 100% no-repeat, #FFFFFF;;
Sep 18 08:51:58 gnome-software[3151]: failed to call gs_plugin_refine_app on snap: Invalid string value converting to GVariant
Sep 18 08:51:59 gnome-software[3151]: failed to call gs_plugin_refine_app on snap: Invalid string value converting to GVariant
```

**Comment by lepidas** [comment] 2019-09-18 07:03
Through the `/etc/sysctl.conf` ipv6 it was and it is disabled in my computer
```
'
'
'
'
'
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.enp0s31f6.disable_ipv6 = 1

```

**Comment by ferdnyc** [comment] 2019-09-19 02:07
> Okay, the former `sysctl` approach I cannot reproduce. The GRUB option I can, and I think I've fixed that (commit in one second).

Mmm, looks like the "it will not be possible to open an IPv6 socket" part _was_ the critical bit. With the `sysctl` change, IPv6 would be disabled on all the interfaces, but the socket `bind()` would still succeed (and just never communicate with anything).

**Comment by andyholmes** [comment] 2019-09-19 04:47
> ...but the socket bind() would still succeed (and just never communicate with anything).

Yeah, which is not really great developer experience :P It was my mistake to try closing the socket on failure though, and not really necessary since it happens when the last ref is dropped anyway.

@lepidas It should be okay in master now, tested myself, but FYI there are going to be some problems with the next upgrade and some paired devices wrt b2ebb83. That's also my fault, because what's described in the commit message didn't occur to me.

**Comment by Filbuntu** [comment] 2019-09-19 06:29
Thank you all for working on this!

**Comment by andyholmes** [comment] 2019-10-06 16:12
I think this one's all fixed in `master` now, so I'm going to close it.

**Closed by andyholmes** 2019-10-06 16:12 UTC
Labels: bug, needs testing
