### ISSUE TITLE
Wiko View 2: no sms history

### ISSUE THREAD

**Issue by legluondunet** [andyholmes/gnome-shell-extension-gsconnect#776] opened 2020-03-06 12:48 UTC
Hello,
I can not read my SMS history on the computer (Ubuntu 19.10 with last gnome-shell-extension-gsconnect version from official extension site.

**Comment by andyholmes** [comment] 2020-03-06 19:27
See [SMS Messages Don't Sync](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#sms-messages-dont-sync).

duplicate of #320

**Closed by andyholmes** 2020-03-06 19:27 UTC
Labels: duplicate
