### ISSUE TITLE
Breaks notify-send on Ubuntu 18.04

### ISSUE THREAD

**Issue by egor-tensin** [andyholmes/gnome-shell-extension-gsconnect#156] opened 2018-07-11 10:13 UTC
Reproduce:
* Enable GSConnect.
* Execute `notify-send a b` a number of times.

Expected result:
* Every `notify-send` run results in a notification being shown.

Actual result:
* Usually, only the first notification will be shown.

Every other notification will get an entry like this in the journal:
```
Jul 11 13:04:22 tensin-pc1 gnome-shell[9208]: JS ERROR: Call to GetConnectionUnixProcessID failed: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not get PID of name ':1.97': no such name
                                              _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:71:26
```

The screen number in ":1.97" (it looks like $DISPLAY) gets incremented seemingly with no limit.

Workaround:
* Disable GSConnect, log out & log in (reloading GNOME Shell via Alt+F2 & "r" doesn't work).

I tried installing a couple of other extensions, and they seem to cooperate with `notify-send` properly, which lead me to believe that GSConnect might be misbehaving.

**Comment by andyholmes** [comment] 2018-07-12 19:07
Thanks for the detailed bug report and how to reproduce, it helped me track this down pretty quick.

I'm not sure _why_ this happens, but I know what causes it. GSConnect has two parts; the server and the Shell extension (and WeExtension/Nautilus extension) that communicates with the server. The server "eavesdrops" on the libnotify DBus interface so it can forward notifications to devices and each time `notify-send` is run it makes a opens a new connection to the libnotify DBus interface to send the notification, which is the `:1.97` address you were seeing.

There are two ways to eavesdrop on a DBus interface and GSConnect uses the [older, deprecated way](https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-eavesdropping) that I copied from KDE Connect. Gnome Shell implements the libnotify DBus interface itself, and gets the PID from the notifying application to get some information about it by calling `GetConnectionUnixProcessID` on it's name-owner address (eg. `:1.97`). I guess that the eavesdropping is interfering with that somehow (?), however the [newer method of eavesdropping](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-become-monitor) doesn't seem to cause the same problem.

I'm already using the newer method in wip-rewrite branch, so I'll see about backporting that in time for v12 which will probably be the last version before I merge the wip-rewrite into master.

**Comment by egor-tensin** [comment] 2018-07-12 22:22
Thanks! Looking forward to it. Your extension is amazing!

**Comment by Tazmain** [comment] 2018-07-19 08:52
Hi guys, this is so far the only place I found with the same error. I am however using glibmm from c++ and I get the exact same error only when using Cinnamon DE. Maybe this is a larger bug ?

**Comment by andyholmes** [comment] 2018-07-19 15:39
It's probably related to the way that [Gnome Shell uses the pid](https://github.com/GNOME/gnome-shell/blob/master/js/ui/notificationDaemon.js#L287-L306) of the notifying application to get information about (eg. icon, display name). Apparently, using standard [org.freedesktop.DBus.AddMatch](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-add-match) eavesdropping prevents the `notify-send` process from quitting immediately which confuses Gnome Shell (and probably cinnamon), even though the notification is probably being sent to DBus correctly.

It seems that using [org.freedesktop.DBus.Monitoring.BecomeMonitor](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-become-monitor) for eavesdropping doesn't cause the same problem, and it should be preferred anyways. If you have some program eavesdropping on `org.freedesktop.Notifications` that's probably what is causing it.

**Comment by cyberalex4life** [comment] 2018-07-24 18:01
Hello, I'm having this issue when trying to use notify-send with my [argos-indicator-nvidia-prime](https://github.com/cyberalex4life/argos-indicator-nvidia-prime) -- based on [ARGOS](https://extensions.gnome.org/extension/1176/argos/) and it's not necessarily conditioned by Gsconnect. 
With Gsconnect disabled I can notify from terminal which works terribly or quite doesn't otherwise; but not through Argos, although I use shell commands.  
Just wanted to say this...

**Comment by andyholmes** [comment] 2018-09-22 12:52
I'm going to close this now since it's been fixed in the v13 rewrite and merged into master.

**Closed by andyholmes** 2018-09-22 12:52 UTC
Labels: bug
