### ISSUE TITLE
Service unavailable on Firefox.

### ISSUE THREAD

**Issue by laichiaheng** [andyholmes/gnome-shell-extension-gsconnect#366] opened 2018-11-28 10:42 UTC
**Describe the bug**
Service unavailable on Firefox.

**To Reproduce**
1. install the firefox extension
2. See error

**Expected behavior**
No error

**Screenshots**
![2018-11-28 18-39-16](https://user-images.githubusercontent.com/9532105/49146347-edeb2c80-f33c-11e8-8624-c1ecc80db3c1.png)

**Debug output**

```
[Parent 4007, Gecko_IOThread] WARNING: pipe error (181): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
###!!! [Parent][MessageChannel] Error: (msgtype=0x190084,name=PBrowser::Msg_Destroy) Closed channel: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0x300116,name=PContent::Msg_DetachBrowsingContext) Closed channel: cannot send/recv
[Parent 4007, Gecko_IOThread] WARNING: pipe error (58): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
[Parent 4007, Gecko_IOThread] WARNING: pipe error (111): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
[Parent 4007, Gecko_IOThread] WARNING: pipe error (94): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
[Parent 4007, Gecko_IOThread] WARNING: pipe error (171): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
../../../../gio/gdbusobjectmanagerclient.c:1589: Processing InterfaceRemoved signal for path /org/gnome/Shell/Extensions/GSConnect/Device/e432b799ed73b11b but no object proxy exists
[Parent 5955, Gecko_IOThread] WARNING: pipe error (46): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
[Parent 5955, Gecko_IOThread] WARNING: pipe error (100): 連線被對方重設: file /build/firefox-4jpYyn/firefox-63.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 356
```

**System Details (please complete the following information):**
 - GSConnect version: [17]
   - Installed from: [extensions.gnome.org]
 - GNOME/Shell version: [3.30, 3.28]
 - Distro/Release: [Ubuntu 18.10]

**GSConnect environment (if applicable):**
 - Paired Device(s): [Galaxy A8]
 - KDE Connect app version: [I don't know]
 - Plugin(s): [Browser Add-Ons]

**Additional context**
Nothing.

**Comment by andyholmes** [comment] 2018-11-28 18:45
Thanks for reporting, doesn't look like anything in the log you posted is specifically about this. Have a quick look at the Firefox Add-On log first and we'll go from there:

1. Enable add-on debugging:
    ![screenshot from 2018-11-28 10-42-52](https://user-images.githubusercontent.com/1265208/49174159-709ec800-f2fa-11e8-8831-ccfcc2846e72.png)
2. Hit the *Debug* link and a window should open with some logs
    ![screenshot from 2018-11-28 10-42-52](https://user-images.githubusercontent.com/1265208/49174168-75637c00-f2fa-11e8-8eb4-ef299b2d1141.png)

Something is wrong here, but this will tell is if it's the add-on, GSConnect, or something in between.

**Comment by ferdnyc** [comment] 2018-11-29 20:54
@andyholmes Did you mean to post two identical screenshots there?

**Comment by andyholmes** [comment] 2018-12-24 23:02
Is this bug still occuring, or has it been resolved?

**Comment by laichiaheng** [comment] 2019-05-03 01:26
![2019-05-03 09-25-59 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57116085-7a36cb00-6d85-11e9-9c7c-5302d312b4b7.png)

**Comment by andyholmes** [comment] 2019-05-03 22:19
Can you confirm that the native messaging host is begin started correctly? Your output should look something like this:

    $ ps aux | grep gsconnect
    andrew    2814  0.0  0.5 1660840 22072 tty2    Sl+  10:53   0:00 gjs /home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js /home/andrew/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json gsconnect@andyholmes.github.io
    andrew   23351  0.0  0.0  17612  2696 pts/0    S+   14:14   0:00 grep --color=auto gsconnect

**Comment by HerrBulles** [comment] 2019-05-06 06:44
hello !  It seems I have  the  same  issue here , I just  installed gnome-base-minimal  on  MX Linux ,  in  order  to  obtatin seamless integration of the  Android smartphone  with  the  Linux Desktop ,  and  It  doesn't work flawless . What elements  do  I  need  to  present  to  you  in order  to  allow  you  to take  a  look ?  I  could  also  offer vnc /  teamviewer/  anydesk  credentials for  remote  acces   if  needed ,  just  ask  .   Thank you very  much,  I really  apreciate  you  idea  and  work.

**Comment by laichiaheng** [comment] 2019-05-06 12:31
> Can you confirm that the native messaging host is begin started correctly? Your output should look something like this:
> 
> ```
> $ ps aux | grep gsconnect
> andrew    2814  0.0  0.5 1660840 22072 tty2    Sl+  10:53   0:00 gjs /home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js /home/andrew/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json gsconnect@andyholmes.github.io
> andrew   23351  0.0  0.0  17612  2696 pts/0    S+   14:14   0:00 grep --color=auto gsconnect
> ```

```
[laichiaheng@Julian-PC ~]$ ps aux | grep gsconnect
laichia+  1257  2.6  0.7 2363636 64476 ?       Sl   20:26   0:07 gjs /home/laichiaheng/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
laichia+ 20528  0.0  0.0   6616  2256 pts/0    S+   20:31   0:00 grep --colour=auto gsconnect

```

**Comment by ferdnyc** [comment] 2019-05-06 16:56
@laichiaheng 

Your `ps` output indicates that the native messaging host isn't running on your system. GSConnect potentially has multiple processes:

* `service/daemon.js` (present on your system) is the main process for GSConnect, it supports the Gnome Shell extension.
* `service/nativeMessagingHost.js` (which is **not** running) is the helper process for the browser extensions.

On a system with both the shell extension and the browser extension active, you should see _both_, as on my Fedora 29 desktop:
```console
$ ps -ef |grep gsconnect |fold -w 80
ferd      1372  3103  0 12:35 pts/0    00:00:00 grep --color=auto gsconnect
ferd      2763  1633  0 08:56 ?        00:00:47 gjs /home/ferd/.local/share/gnom
e-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
ferd     21954 21535  0 09:19 tty2     00:00:00 gjs /home/ferd/.local/share/gnom
e-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js
 chrome-extension://jfnifeihccihocjbfcfhicmmgpjicaec/
```

Months ago when you made the initial report, you said you had GSConnect version 17 installed — what version are you using now? The current release is version 23, you can update to that version at [the extensions.gnome.org site](https://extensions.gnome.org/extension/1319/gsconnect/) if necessary.

****

@HerrBulles 

Your `ps` output doesn't show _any_ GSConnect process running. I also don't see any panel icon in the top bar of Gnome Shell that would indicate a paired device. Do you have the GSConnect extension installed and set up in Gnome Shell? (You can get it at [the extensions.gnome.org page for GSConnect](https://extensions.gnome.org/extension/1319/gsconnect/).) 

You need to have GSConnect installed in Gnome Shell, have the [KDE Connect app](https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp) installed on your phone, and the two devices need to be on the same WiFi network so they can communicate. The pairing process is pretty simple once everything's in place, if you have problems consult [the help section of the wiki](wiki/Help#connecting-an-android-device) for some troubleshooting suggestions.

**Comment by laichiaheng** [comment] 2019-05-06 18:22
@ferdnyc It's version 23 now.

**Comment by andyholmes** [comment] 2019-05-10 22:33
@laichiaheng 

Can you confirm these files exist?

    ~/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json
    ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js

The native messaging host has the proper permissions:
 
    $ ls -la ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js
    -rwxr-xr-x 1 andrew andrew 6740 Mar  7 12:27 /home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js

It seems like the problem is the WebExtension is not starting the nativeMessagingHost.js, which is why it can't connect to it.

**Comment by laichiaheng** [comment] 2019-05-11 10:11
@andyholmes Mine is in `/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js`, it is installed by Manjaro.

**Comment by andyholmes** [comment] 2019-05-11 16:55
@laichiaheng Ah, that will be your problem then. If the extension is installed in `~./local/share/gnome-shell/extensions/` then it will expect the `nativeMessageHost.js` to be there as well.

You should install only one or the other. I'm guessing the version in Manjaro is the package from AUR?

**Comment by laichiaheng** [comment] 2019-05-13 12:47
@andyholmes Is there any way to make the add-on read the nativeMessageHost.js from /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/?

**Comment by andyholmes** [comment] 2019-05-13 18:58
@laichiaheng 

If you want to use the version of GSConnect distributed with Manjaro, you should just uninstall the local version distributed by extensions.gnome.org. Either is fine, you just can't have both at the same time.

**Comment by laichiaheng** [comment] 2019-05-13 20:14
@andyholmes I didn't install the extensions.gnome.org version on my computer.

**Comment by andyholmes** [comment] 2019-05-13 20:22
[laichiaheng@Julian-PC ~]$ ps aux | grep gsconnect
    laichia+  1257  2.6  0.7 2363636 64476 ?       Sl   20:26   0:07 gjs /home/laichiaheng/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
    laichia+ 20528  0.0  0.0   6616  2256 pts/0    S+   20:31   0:00 grep --colour=auto gsconnect

^ Here GSConnect is running from a user directory, so either Manjaro is not packaging GSConnect properly or you somehow installed it as user extension also.

**Comment by laichiaheng** [comment] 2019-05-14 01:00
@andyholmes 
![2019-05-14 08-58-35 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57663427-7f6a0480-7626-11e9-945b-cc00d7a5e4b6.png)
![2019-05-14 09-00-24 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57663485-bf30ec00-7626-11e9-8022-5e49dee76bb6.png)
Still the same.

**Comment by andyholmes** [comment] 2019-05-14 03:50
Can you confirm the `nativeMessagingHost.js` file is executable:

    $ ls -la /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js
    -rwxr-xr-x 1 andrew andrew 6740 Mar  7 12:27 /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js

And that the WebExtension manifest has been installed in `/usr/lib` (or whatever libdir on Manjaro is):

    $ cat /usr/lib/mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json 
    {
        "name": "org.gnome.shell.extensions.gsconnect",
        "description": "Native messaging host for GSConnect WebExtension",
        "path": "/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js",
        "type": "stdio",
        "allowed_extensions": [ "gsconnect@andyholmes.github.io" ]
    }

And that the manifest is not being overridden by a manifest installed in the user directory:

    $ cat ~/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json
    cat: /home/andrew/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json: No such file or directory

If any of these are not true, you will probably have to enable/disable the WebExtension after fixing them.

**Comment by laichiaheng** [comment] 2019-05-14 03:56
The last one exist in my home directory. Do I need to remove it?

**Comment by andyholmes** [comment] 2019-05-14 04:07
GSConnect tries to cleanup if it notices it has changed from user to system, but you will need to enable/disable the GNOME Shell extension or restart GNOME Shell for that to happen automatically.

Once started the Shell extension will maintain it's state (thinking it is a user extension), so probably you will have to do that.

**Comment by laichiaheng** [comment] 2019-05-14 04:18
I have reboot the OS, but it still doesn't work.
![2019-05-14 12-17-30 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57670538-50618c00-7642-11e9-80e1-cb4420a2becb.png)

**Comment by andyholmes** [comment] 2019-05-15 20:54
I can't see any reason why the native messaging host is not starting. Can you try running in manually in a terminal:

    $ gjs /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js 
     {"type":"connected","data":true}

It should output that one line if it starts properly.

**Comment by otsoaUnLoco** [comment] 2019-06-21 04:05
I have the same issue on Ubuntu 19.04 in Firefox. The files mentioned above exist but there is an error when I try to run the host manually. GSConnect version 24.

`gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js`

`Gjs-Message: 06:03:16.627: JS WARNING: [/home/otsoa/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js 220]: reference to undefined property "_devices`

**Comment by andyholmes** [comment] 2019-06-22 00:23
Hmm, there was a comment here a few days ago, but it seems to have disappeared. In any case, I fixed the small bug that user reported and here's an updated Zip. I'm not sure if this is actually the problem, but it's worth a shot:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3316358/gsconnect%40andyholmes.github.io.zip)

**Comment by rvanlaar** [comment] 2020-01-27 15:57
The same is happening for me. Attached is a screenshot of the same message happening in gsconnect itself.

![Screenshot from 2020-01-27 16-56-10](https://user-images.githubusercontent.com/710771/73190313-1bd92600-4126-11ea-9c58-9d9efbc031d8.png)

**Comment by andyholmes** [comment] 2020-01-28 01:22
@rvanlaar In your case you can see that the service is simple not running. You should turn it on in the menu:

![Screenshot from 2020-01-27 17-20-38](https://user-images.githubusercontent.com/1265208/73227790-8dff3a00-4129-11ea-8e4a-7b4cbac5bd8c.png)

**Comment by rvanlaar** [comment] 2020-01-28 10:12
It might be that I'm encountering another issue:

1) The menu doesn't show up to turn it on. 

![Screenshot from 2020-01-28 11-05-36](https://user-images.githubusercontent.com/710771/73254181-3363ed80-41be-11ea-9d22-dfd4c33d7e99.png)

2) The detection whether it's on or off doesn't work.
It's on, but the slider on this page says off. Turning the slider on and refreshing page puts the slider back into the off position.
![Screenshot from 2020-01-28 11-09-24](https://user-images.githubusercontent.com/710771/73254425-af5e3580-41be-11ea-9a79-c3aea6cb194f.png)

3) It turns on when I press the 'refresh' button from the configuration menu.
Which I can only seem to open via the configuration button on plugin page (see image above).

**Comment by andyholmes** [comment] 2020-01-28 10:34
It seems like the extension is not properly enabled in the Shell. Maybe try turning on the extension with:

```sh
gnome-extensions enable gsconnect@andyholmes.github.io
```

If that doesn't work, you should open a new issue with your gnome-shell and extension versions.

**Comment by andyholmes** [comment] 2020-04-02 19:32
Is this issue still valid?

**Comment by rvanlaar** [comment] 2020-04-02 21:53
For me it's not. My part was fixed, due to ubuntu disabling all gnome-extensions.

**Comment by andyholmes** [comment] 2020-04-04 20:01
Okay going to close this one up for now.

**Closed by andyholmes** 2020-04-04 20:01 UTC
Labels: webextension

**Comment by windowzytch** [comment] 2021-04-25 10:57
Well, just tried on Ubuntu 21.04 using Google Chrome extension on Microsoft Edge Dev and the same issue happens here. I've installed GSConnect just yesterday and the extension just today.

Here's the error I could capture so far;
![image](https://user-images.githubusercontent.com/39265461/115990847-2c4caa80-a5ce-11eb-8ab9-0bbd1acb589e.png)

**Comment by andyholmes** [comment] 2021-04-26 00:07
Microsoft Edge is not supported, AFAIK. You'd have to figure out where it installs and looks for native messaging host manifests and add it to the setup script.

**Comment by windowzytch** [comment] 2021-04-28 01:47
> Microsoft Edge is not supported, AFAIK. You'd have to figure out where it installs and looks for native messaging host manifests and add it to the setup script.

Well, you're right, issue is where the extension is installed. It installs the extension to somewhere uncommon. :sweat_smile: 
Anyway, thanks for caring and the hard work. Much appreciated! :+1:

**Comment by Adrian-Benavente** [comment] 2021-09-16 22:34
![imagen](https://user-images.githubusercontent.com/11258517/133694164-a7b6970d-31cd-4091-8f12-d47072c7c321.png)
Hi, I'm having the same issue and I see no solution here that works on my case. My debug console shows the following...
Thanks in advance :)

**Comment by Adrian-Benavente** [comment] 2021-12-22 15:56
Still having the "service unavailable" issue on December 2021 :(

**Comment by paven** [comment] 2022-03-05 09:24
I have this problem, The chrome extension on the same computer work. I have a similar problem with "Open All Tabs in X" it does not work in firefox but works in chrome. My assumption is that Firefox on Ubuntu is somehow sandboxed. I found no way to escape the sandbox. :/

**Comment by windowz414** [comment] 2022-03-05 17:01
> I have this problem, The chrome extension on the same computer work. I have a similar problem with "Open All Tabs in X" it does not work in firefox but works in chrome. My assumption is that Firefox on Ubuntu is somehow sandboxed. I found no way to escape the sandbox. :/

If you clean installed Ubuntu after 20.04, they ship Firefox as a Snap package instead of APT. Either use Firefox ESR from APT using this command or don't use it at all:
```bash
sudo apt-get install firefox-esr
```
