### ISSUE TITLE
Device files cannot be accessed from command line

### ISSUE THREAD

**Issue by krupenja** [andyholmes/gnome-shell-extension-gsconnect#167] opened 2018-08-14 15:10 UTC
Steps to reproduce:
1. Install gsconnect.
2. Install sshfs.
3. Pair a phone and enable Browse Files extension.
4. Open Browse files for All files from the menu. Nautilus will open, successfully showing files.
5. Copy the path from Nautilus (e.g. `/run/user/1000/gsconnect/996b8150c6c5f06e`).
6. Open terminal.
7. `cd` into this directory, e.g. `cd /run/user/1000/gsconnect/996b8150c6c5f06e`.
8. Do `ls -a`.

Output is empty, device files cannot be accessed from command line.

PC OS: Manjaro Linux 17.1.11, Gnome 3.28
Phone: Xiaomi Mi A1, Android 8.1

**Comment by andyholmes** [comment] 2018-08-14 22:51
I used to frequently get disconnects during listing the files of a directory, but adding `-o reconnect` to  `sshfs` makes it reconnect if interrupted in the middle of an operation. Here is a copy of v12 due to be released in a few days, which includes that change:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2288700/gsconnect.andyholmes.github.io.zip)

If you could install this [using the Wiki instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip) and give it a try. I can't reproduce that bug myself, so I think this change may have fixed it.

**Comment by andyholmes** [comment] 2018-09-26 04:48
Is this issue still valid in v12?

**Comment by krupenja** [comment] 2018-09-26 16:18
Tried this today with v12 and the same steps, got the following: `ls: reading directory '.': Permission denied`. I also get the same if I do `sudo ls -a`.

**Comment by andyholmes** [comment] 2018-09-29 03:05
What are the permissions of the directory itself?

    ls -la /run/user/1000/gsconnect/996b8150c6c5f06e

**Comment by andyholmes** [comment] 2018-11-08 04:04
Does this bug still affect the latest version (v15)?

**Comment by andyholmes** [comment] 2018-11-28 23:41
Closing since there's been no activity or information for 2 months.

**Closed by andyholmes** 2018-11-28 23:41 UTC
Labels: needs info
