### ISSUE TITLE
Remote input has stopped working

### ISSUE THREAD

**Issue by Scotty-Trees** [andyholmes/gnome-shell-extension-gsconnect#881] opened 2020-06-21 09:34 UTC
Using Solus GNOME 3.36.3 on kernel 5.6.18, but I've noticed maybe in the last week, although I can still connect my Samsung Galaxy S9+ and transfer files, I cannot however use the remote input method. I use it often to control my laptop from my bedside, but recently it's seemed to just stopped working, not sure why, but just wanted to bring it to your attention. Another user besides myself has expressed the same issue from the Gnome Extensions website as well.

**Comment by andyholmes** [comment] 2020-06-21 19:58
Sounds like another duplicate of #869. Should be fixed in c5f42f5, in the next release.

**Closed by andyholmes** 2020-06-21 19:58 UTC
Labels: duplicate
