### ISSUE TITLE
GSConnect will not install from GNOME Extensions website

### ISSUE THREAD

**Issue by theorangepotato** [andyholmes/gnome-shell-extension-gsconnect#920] opened 2020-08-16 17:55 UTC
**Describe the bug**
GSConnect does not install from the GNOME Extensions page. It merely says that it is experiencing an error.

**Steps To Reproduce:**

1. Make sure GSConnect is not installed.
2. Go to https://extensions.gnome.org/extension/1319/gsconnect/
3. Click on toggle to install the extension
4. It will say `ERROR` in a red box.

**Expected behavior**
That the extension cleanly installs without an error.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/15709902/90340556-e1de4d00-dfad-11ea-8949-b96db541ee0d.jpg)

**Support Log**
Since I could not install the extension, instead of the support log, I have followed [these instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/919#issuecomment-674441493) to show the extension's logs.

```
Uncaught (in promise) TypeError: page.tabs[id] is undefined
    stackUnshift moz-extension://1a749c40-a4e3-40bc-b224-d9daebefea03/background/browserAction.js:96
    showDefault moz-extension://1a749c40-a4e3-40bc-b224-d9daebefea03/background/browserAction.js:49
browserAction.js:96:5
Content Security Policy: Couldn’t parse invalid host 'wasm-eval' 2
Promise resolved after context unloaded
dnt.js:52
Promise resolved after context unloaded
fingerprinting.js:331
Content Security Policy: Couldn’t parse invalid host 'wasm-eval' 2
```

**System Details:**

 - **GSConnect version:** 41 (I believe)
   - **Installed from:** GNOME Extensions Website (via Firefox)
 - **GNOME/Shell version:** 3.36.4 (current stable)
 - **Distro/Release:** Ubuntu 20.04

**Additional Notes:**
This worked yesterday morning, immediately preceding the new release. It seems that something changed between that and the current release to cause this issue.

Let me know if there are any additional logs or debugging steps I can take that would be helpful!

**Comment by andyholmes** [comment] 2020-08-16 18:10
Duplicate of #817.

You must restart GNOME Shell after updating an extension. If you uninstall, then re-install, you still need to restart GNOME Shell between those two steps.

**Closed by andyholmes** 2020-08-16 18:10 UTC

**Comment by theorangepotato** [comment] 2020-08-16 18:23
Thank you, you were right! Sorry about the confusion and the extraneous report!

**Comment by andyholmes** [comment] 2020-08-16 18:41
No problem at all. It's a known problem that's confusing for users and a fix is [on its way](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/109#note_829155). If you use the extensions app it will warn you, but the website hasn't caught up yet.
