### ISSUE TITLE
SMS Message history incorrect

### ISSUE THREAD

**Issue by AngusLogan02** [andyholmes/gnome-shell-extension-gsconnect#379] opened 2018-12-06 18:18 UTC
**Describe the bug**
SMS Message history on the left panel (last text sent/received) is correct, but when I click on the contact, it shows the same message from Snapchat confirming my code for every single one of my contacts.

**To Reproduce**
1. Go to messages
2. Click on a contact
3. See that the message is the same for every contact

**Expected behavior**
SMS history is different for everyone.

**Screenshots**
![evidence1](https://user-images.githubusercontent.com/41449334/49603351-ed791400-f982-11e8-8517-6413fdb37651.png)
![evidence2](https://user-images.githubusercontent.com/41449334/49603357-f36ef500-f982-11e8-9e46-821b5ac4edbc.png)

```

```

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: [Latest]
 - Distro/Release: [Arch, system updated a couple days ago]

**GSConnect environment (if applicable):**
 - Paired Device(s): OnePlus 5T
 - KDE Connect app version: [Latest from Google Play Store]
 - Plugin(s): SMS Messaging

**Comment by andyholmes** [comment] 2018-12-06 19:35
HI, thanks for the report.

I think this is similar to #378 and caused by a bug in the Contacts plugin, which had some problems with some unicode usernames and non-numeric phone numbers. If you have `meson` and `git`, GSConnect is easy to install from master which I believe has fixed this:

    git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
    meson gnome-shell-extension-gsconnect/ _build
    ninja -C _build install-zip

Unfortunately there won't be another official release until after I get a new computer :( But master has been very stable for long time now, so it's usually safe to build straight from there.

**Comment by wargreen** [comment] 2018-12-17 15:44
hi,
I got the same issue with debian sid.

Not sure if it's related to this issue, but to you previous post :
After ninja -C _build install-zip and restart gnome-shell, when i try to open the GSconnect configuration windows :
```
Dec 17 16:40:58 fetide gnome-software[20933]: failed to rescan: Failed to parse /home/wargreen/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop
Dec 17 16:40:58 fetide dbus-daemon[20437]: [session uid=1000 pid=20437] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.113' (uid=1000 pid=23202 comm="gnome-shell-extension-prefs gsconnect@andyholmes.g")
Dec 17 16:40:58 fetide dbus-daemon[20437]: [session uid=1000 pid=20437] Activated service 'org.gnome.Shell.Extensions.GSConnect' failed: Failed to execute program org.gnome.Shell.Extensions.GSConnect: Permission denied

```

Thank you

**Comment by andyholmes** [comment] 2018-12-17 15:55
Should be fixed now, thanks for reporting.

**Comment by andyholmes** [comment] 2018-12-24 22:59
I believe this issue has been solved in v18. Please re-open if the issue persists after upgrading.

**Closed by andyholmes** 2018-12-24 22:59 UTC
Labels: bug, good first issue
