### ISSUE TITLE
Add 80% charge notification rather than "Fully Charged Notification"

### ISSUE THREAD

**Issue by meanindra** [andyholmes/gnome-shell-extension-gsconnect#1022] opened 2020-11-24 20:21 UTC
**Is your feature request related to a problem? Please describe. **
> 80-90% charging is a good habit for android users. It helps device use it help for long-lasting battery life. Most battery manufacturers recommend the “40-80 Rule” for lithium-ion. Always 100% charge = heating issue + low battery life cycle

**Describe the solution you'd like**
>Change "Fully Charged Notification" option to 80% Charged Notification

**Describe alternatives you've considered**
>There is no alternative I am just always turn off this feature. Not a use full feature, I think.

**System Details (please complete the following information)**
>  GSConnect version: 44 , Install from https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by andyholmes** [comment] 2020-11-25 01:11
Duplicate of #872

**Closed by andyholmes** 2020-11-25 01:11 UTC
Labels: duplicate
