### ISSUE TITLE
File transfer speed is very slow

### ISSUE THREAD

**Issue by VxMxPx** [andyholmes/gnome-shell-extension-gsconnect#214] opened 2018-09-28 17:17 UTC
Copying files from computer to phone, goes very slow, we're talking dial-up modem type of slow. A normal size MP3 file or an image, would usually just hang / froze Nautilus. 

Copying files from phone to computer, is completely normal though.

**Comment by AdamKane41** [comment] 2018-09-29 05:39
also fast on my end using share button via sys tray

**Comment by andyholmes** [comment] 2018-09-29 07:07
I guess it's worth pointing out that in v13 (`master`), the "direct share" used in the device menu and Nautilus has been improved a lot. Basically it just "attaches" the file to a connection and let's the remote device transfer it as fast as it can (in a dedicate thread). Previously it used to send a ~4kb chunk in a thread and return, then repeat until finished.

`sshfs` is a little different, since it relies on local FUSE performance and the remote device's response time. Nothing much has changed with this in v13, since it's mostly sshfs to do the transferring.

**Comment by VxMxPx** [comment] 2018-09-29 08:36
This is a problem when using `sshfs` (Browse), I've tried share now and that's more interesting... It goes a little bit faster, but then just randomly fails (on the phone message is shown: Failed to receiving file).

If this is of any interest:

```
› sshfs --version
SSHFS version 3.5.0
FUSE library version 3.2.5
using FUSE kernel interface version 7.26
fusermount3 version: 3.2.5
```

```
› uname -a
Linux pc-mistik 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux
```

```
› grep version .local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/metadata.json 
"version": "12",
```

I'll try to upgrade extension to v13 from master.

**Comment by andyholmes** [comment] 2018-09-29 08:36
Are you by chance using Android Oreo?

**Comment by VxMxPx** [comment] 2018-09-29 08:39
Yes, It's Android version 8.0.0.

**Comment by andyholmes** [comment] 2018-09-29 08:41
Ah, I think you need a special build (right now) for Oreo because of the "peristent notification" & background service changes. One sec and I'll see if I can build you one.

**Comment by VxMxPx** [comment] 2018-09-29 13:48
Thanks for this. However when I install it on my phone, the WIFI stops working (I've tried twice, and it happened both times). 

I've upgraded extension to the version 13 and manage to connect with original version of KDE Connect, but transfer speeds are still the same. 

It was working really fine a while back, then some upgrades happened (wish I'd knew what and when) and since then it's really slow.

I've reinstalled Arch yesterday (unrelated problems), and it's still the same. Really interesting that no one else is experiencing this.

Anyhow I'll look around a little bit namely sshfs, and KDE Connect and if I find any solution I'll report back.

**Comment by andyholmes** [comment] 2018-10-02 04:17
For reference, this is what I'm using in Ubuntu 18.04:

    SSHFS version 2.8
    FUSE library version: 2.9.7
    fusermount version: 2.9.7
    using FUSE kernel interface version 7.19

**Comment by andyholmes** [comment] 2018-10-16 00:49
I'm going to close this, since I think in any case it's not a bug in GSConnect. Please re-open if you have reason to think it is.

**Closed by andyholmes** 2018-10-16 00:49 UTC
